# -*- coding: utf-8 -*-
"""Peças do calendário v3 (parte 4: 05/01 a 07/02/2027, inclui a viagem de janeiro). Chaves: ver v3_pecas_1.py."""
from v3_pecas_1 import BCN_MASTER, BCN_TRANS, OUTRAS, ROMA_FOTOS

VIAGEM = "Material futuro: gravado ao vivo na viagem de janeiro (Alemanha, Áustria e Praga, a confirmar). Registro de campo obrigatório: hora de chegada e cada gasto anotados no celular, para o Placar"

PECAS = [
# ───────────────────────── Semana 14 (04 a 10/01) ─────────────────────────
dict(
 d="2027-01-05", h="18:30", f="R", k="bcn", pl="UTIL", nv="A", st="ok",
 t="Sagrada Família: o ingresso que precisa de antecedência",
 ob="Salvamento no começo do ano, quando muita gente planeja as férias: a regra prática do ingresso da Sagrada Família, com o preço que pagamos.",
 mo="Quem vai a Barcelona em 2027. Salva para comprar na hora certa; envia para quem vai junto.",
 g="Não deixe esse ingresso pra depois.", gt="Não faça isso",
 q0="Fachada da Sagrada Família às 9h30, cheia (master ≈ 23:55), com a Placa `NÃO FAÇA ISSO` / `SAGRADA FAMÍLIA`.",
 sc=[("0–2 s","Gancho","Fachada cheia + Placa Não faça."),
     ("2–8 s","Contexto","Master 25:51–26:10: “surreal o passeio, recomendo demais, se programem, abre as vendas um mês antes, foi 25 euros por pessoa”."),
     ("8–13 s","Prova","Interior (planos diferentes do Reel de 24/10). Etiqueta de valor `€ 25`."),
     ("13–17 s","Pico","Bilhete: “compre assim que abrir a venda.”"),
     ("17–19 s","Fechamento","Placa CTA `SALVA PRA VIAGEM →`.")],
 tl="não deixe esse ingresso pra depois · sagrada família · € 25 por pessoa · compre assim que abrir a venda",
 na="Sem narração nova.",
 lg="Não deixe esse ingresso pra depois. 🎟️\n\nA Sagrada Família foi o passeio que mais valeu em Barcelona, e o ingresso esgota. Pagamos € 25 por pessoa e chegamos às 9h30, já com muita gente.\n\nDica: compre assim que a venda abrir para a sua data. [Antecedência e preço de 2027 a confirmar no site oficial.]\n\nCotação: € 1 = R$ [PTAX da data da viagem].\n\nSalva pra sua viagem a Barcelona.",
 cta="Salva pra sua viagem a Barcelona (salvamento).",
 cp="Fachada da Sagrada Família. Texto da capa: “COMPRE ANTES”.",
 so="Falas originais + música da biblioteca baixa.",
 me="Salvamentos por alcance", hi="Dica de antecedência publicada no período de planejamento de férias é muito salva.",
 te=None,
 ma=[BCN_MASTER+": 23:55–26:10 (dia 3)", "IMG_1192.MOV (Sagrada, dia 3)", BCN_TRANS],
 pe=["Conferir no site oficial (sagradafamilia.org) a antecedência de venda e o preço de 2027 (o vídeo diz “um mês antes”)", "Usar planos diferentes do Reel de 24/10"],
 of="Barcelona, dia 3", otr="Master 23:55–26:10"),

dict(
 d="2027-01-06", h="18:00", f="C", k="multi", pl="UTIL", nv="—", st="dad",
 t="Quanto custou cada cidade (por dia, por pessoa)",
 ob="Salvamento e envio no auge do planejamento de 2027: o custo diário real de cada cidade, lado a lado. É o carrossel-referência do perfil (candidato a fixado).",
 mo="Quem decide para onde ir em 2027 com orçamento. Salva como referência; envia para quem vai decidir junto.",
 g="Quanto custou 1 dia em cada cidade.", gt="Preço",
 q0="Capa em papel (variante B do teste T4): Quadro com as cidades e o custo por dia, do mais barato ao mais caro.",
 sl=["1 · Capa (papel): Quadro “1 dia em cada cidade, por pessoa” com as cidades em ordem de custo.",
     "2 · Como contamos (segunda capa): por pessoa, com hospedagem, valores da época da viagem e cotação datada.",
     "3–11 · Um slide por cidade: foto + Recibo curto (hospedagem, comida, transporte, passeios) e custo por dia. Roma já tem dados reais: € 421,50 em 3 dias (≈ € 140,50 por dia com hospedagem).",
     "12 · Dica (Bilhete): o que mais pesou em todas (hospedagem).",
     "13 · Encerramento: Placa CTA `SALVA PRA VIAGEM →` + 1º."],
 tl="Slides acima. Etiqueta `QUANTO CUSTOU`.",
 na="Não se aplica (carrossel).",
 lg="Quanto custou 1 dia em cada cidade, por pessoa. 💶\n\n[cidade]: € [valor]/dia\n[cidade]: € [valor]/dia\n…\nRoma: € 140,50/dia (€ 421,50 em 3 dias, dez/2024)\n\nTudo por pessoa, com hospedagem, com os preços da época de cada viagem.\n\nCotação de cada cidade no slide correspondente.\n\nSalva pra decidir a sua viagem de 2027.",
 cta="Salva pra decidir a sua viagem de 2027 (salvamento).",
 cp="Quadro com o ranking de custo (teste T4, variante B).",
 so="Música instrumental da biblioteca ao postar.",
 me="Salvamentos e envios por alcance", hi="Comparação de custo entre cidades é o conteúdo mais salvável do perfil; candidato a fixado.",
 te="T4:B",
 ma=["Registros de custos de todas as cidades (Diego)", "Roma: ESTUDO_CARROSSEL_ROMA.md, seção 4", "Fotos de cada cidade"],
 pe=["Diego: custos de todas as cidades (Barcelona, Amsterdam, Bruxelas, Bruges, Paris, Disney, Madrid, Lisboa, Florença, Veneza, Milão)", "Se faltar alguma cidade até 30/12, publicar só com as que têm dado e dizer isso no slide 2", "421,50 ÷ 3 = 140,50"],
 of="Vários destinos (custos)", otr="Registro de custos"),

dict(
 d="2027-01-07", h="12:30", f="R", k="multi", pl="UTIL", nv="A", st="ok",
 t="2 erros que a gente não repete",
 ob="Envio e salvamento: dois erros reais de roteiro (um em Paris, um em Roma), com a correção de cada um.",
 mo="Quem planeja a primeira viagem à Europa. Envia para quem vai viajar; salva o checklist.",
 g="2 erros que a gente não repete.", gt="Não faça isso",
 q0="Portão fechado do Jardim de Luxemburgo (IMG_3134) com o Carimbo `NÃO FAÇA` (sobre papel).",
 sc=[("0–2 s","Gancho","IMG_3134 (portão) + Placa `NÃO FAÇA ISSO` + legenda Padrão."),
     ("2–9 s","Erro 1","Paris: deixar o Jardim de Luxemburgo para o fim do dia. Estava fechado. Bilhete: “confira o horário da estação.”"),
     ("9–16 s","Erro 2","Roma: deixar a Capela Sistina para comprar tarde. No site oficial já não tinha, e nas empresas terceiras estava caro demais. Foto de São Pedro (IMG_6653). Bilhete: “compre com antecedência.”"),
     ("16–19 s","Fechamento","Placa CTA `MANDA PRA QUEM VAI →`.")],
 tl="2 erros que a gente não repete · paris: o jardim fechou · roma: a capela sistina esgotou · confira o horário · compre antes",
 na="Narração curta do Diego (até 10 s) contando os dois erros.",
 lg="2 erros que a gente não repete. ❌\n\n1. Paris: deixar o Jardim de Luxemburgo para o fim do dia. Quando chegamos, estava fechado. O horário muda com a estação: confira antes.\n\n2. Roma: deixar a Capela Sistina para comprar tarde. No site oficial já não tinha ingresso, e nas empresas terceiras estava caro demais. Compre com antecedência.\n\nManda pra quem vai viajar e ainda não comprou nada.",
 cta="Manda pra quem vai viajar (envio).",
 cp="Portão fechado com o carimbo. Texto da capa: “NÃO REPITA”.",
 so="Narração + música da biblioteca; *tum* do carimbo (1 só).",
 me="Envios por alcance", hi="Erros reais de duas cidades num Reel só geram mais envios que um erro de cidade única (teste T5, variante B).",
 te="T5:B",
 ma=["IMG_3134.MOV (Paris)", "IMG_6653 (São Pedro)", ROMA_FOTOS, OUTRAS],
 pe=["Carimbo PERRENGUE pede data e hora reais: usar a variante `NÃO FAÇA` (sem data) ou só a placa"],
 of="Paris e Roma", otr="IMG_3134 + IMG_6653"),

dict(
 d="2027-01-09", h="11:00", f="R", k="bcn", pl="SERIE", nv="B", st="ok",
 t="Vale a pena ir a Barcelona? A resposta no aeroporto",
 ob="Conversão e desejo: o veredito final de Barcelona, dito no aeroporto, no clima de despedida. Fecha a série de Barcelona.",
 mo="Quem está decidindo a viagem de 2027. Envia para quem precisa ser convencido; segue para ver as próximas cidades.",
 g="Barcelona vale a pena? Respondemos no aeroporto.", gt="Pergunta",
 q0="Os dois no aeroporto de Barcelona (master ≈ 33:20). Placa Hook `VALE A PENA?` / `BARCELONA`.",
 sc=[("0–2 s","Gancho","Aeroporto + Placa Hook."),
     ("2–10 s","Resposta","Master 33:20–33:50: “cidade surreal, energia muito boa… quem estiver planejando vir para Barcelona: vale muito a pena, você não vai se arrepender”."),
     ("10–16 s","Prova","Montagem rápida de 4 planos dos 3 dias (Snap)."),
     ("16–20 s","Fechamento","Master 33:50–34:05: “para quem não tem Barcelona nos planos: coloque”. Legenda: “manda pra quem precisa de um empurrão.”")],
 tl="barcelona vale a pena? · respondemos no aeroporto · vale muito a pena · coloque nos planos",
 na="Sem narração nova.",
 lg="Barcelona vale a pena? A gente respondeu no aeroporto. ✈️\n\nTrês dias, 18 km no primeiro, Gaudí, tapas e muito frio na praia. A resposta: vale muito a pena. Quem tem Barcelona nos planos não vai se arrepender. Quem não tem, coloca.\n\nManda pra quem precisa de um empurrão pra ir.",
 cta="Manda pra quem precisa de um empurrão pra ir (envio).",
 cp="Os dois no aeroporto. Texto da capa: “VALE A PENA?”",
 so="Falas originais + música da biblioteca.",
 me="Seguidores por 1.000 visualizações e envios", hi="Veredito de despedida, com emoção, gera envios para quem está indeciso (teste T3, variante B: CTA de envio).",
 te="T3:B",
 ma=[BCN_MASTER+": 33:20–34:05 (dia 3)", BCN_TRANS],
 pe=["Checar trilha sob a fala no aeroporto"],
 of="Barcelona, dia 3", otr="Master 33:20–34:05"),

dict(
 d="2027-01-10", h="19:00", f="R", k="multi", pl="SERIE", nv="A", st="dad",
 t="Próximo primeiro dia: [cidade 1]",
 ob="Conversão: anunciar a viagem de janeiro e dar o motivo mais forte para seguir agora (ver os próximos primeiros dias ao vivo).",
 mo="Quem já viu algum Reel e quem vai para a Alemanha, Áustria ou Praga. Segue para acompanhar; comenta pedidos.",
 g="Próximo primeiro dia: [cidade 1].", gt="Afirmação",
 q0="Placa `PRÓXIMO PRIMEIRO DIA` não existe no DS: usar a Placa de abertura `PRIMEIRO DIA EM / [CIDADE 1]` sobre cena de mala ou aeroporto do acervo.",
 sc=[("0–2 s","Gancho","Placa `PRIMEIRO DIA EM / [CIDADE 1]` sobre cena de aeroporto (IMG_1375 ou master 33:20)."),
     ("2–10 s","Recap","Snap com 1 chegada de cada cidade já mostrada (mesma lógica do Reel de 03/11, planos diferentes)."),
     ("10–16 s","Anúncio","Diego (narração ou fala nova, sem quebrar a continuidade: é uma fala de agora sobre o futuro): “dia 20 eu embarco. 3 países, [N] primeiros dias.”"),
     ("16–20 s","Fechamento","Placa `E ISSO FOI SÓ O / PRIMEIRO DIA.` + 1º. Legenda: “segue pra ver ao vivo.”")],
 tl="próximo primeiro dia: [cidade 1] · 8 cidades até aqui · dia 20 eu embarco · segue pra ver ao vivo",
 na="Gravação nova do Diego (até 6 s), em casa: é anúncio do futuro, não mistura com as viagens passadas.",
 lg="Próximo primeiro dia: [cidade 1]. ✈️\n\nDepois de [N] cidades, a próxima viagem é em janeiro: Alemanha, Áustria e Praga [confirmar]. Desta vez, o primeiro dia de cada cidade sai quase ao vivo, com hora e gasto marcados na tela.\n\nO que você quer ver por lá? Pode pedir nos comentários.\n\nSegue pra ver ao vivo.",
 cta="Segue pra ver ao vivo (seguir).",
 cp="Placa com a cidade 1. Texto da capa: “PRÓXIMO: [CIDADE 1]”.",
 so="Música da biblioteca com batida; clack da placa.",
 me="Seguidores por 1.000 visualizações", hi="Anunciar o próximo episódio com data cria motivo concreto para seguir (teste T3, variante A).",
 te="T3:A",
 ma=["Uma chegada de cada cidade (acervo)", "Gravação nova de até 6 s (Diego, em casa)"],
 pe=["Diego: confirmar cidades, ordem e datas da viagem (pendência desde 05/10)", "Atualizar a bio com “próximo destino” no mesmo dia"],
 of="Vários destinos", otr="Acervo + gravação nova"),

# ───────────────────────── Semana 15 (11 a 17/01) ─────────────────────────
dict(
 d="2027-01-12", h="18:30", f="R", k="mad", pl="UTIL", nv="B", st="dec",
 t="Madrid de graça: o que vimos sem pagar",
 ob="Salvamento: lista real do que dá para ver em Madrid sem ingresso, no mesmo espírito do carrossel de Roma de 04/11, em formato Reel.",
 mo="Quem vai a Madrid com orçamento curto. Salva; envia para quem vai junto.",
 g="Madrid de graça: o que vimos.", gt="Lista curta",
 q0="O primeiro lugar gratuito da lista (decupagem) com a Placa `QUANTO CUSTOU` / `MADRID` e Etiqueta `€ 0`.",
 sc=[("0–2 s","Gancho","Primeiro lugar + Placa Série + Etiqueta `€ 0`."),
     ("2–16 s","Lista","Snap entre 4 ou 5 lugares gratuitos que eles visitaram, 2,5 a 3 s cada, nome em legenda Informação."),
     ("16–19 s","Dica","Bilhete com a dica real."),
     ("19–21 s","Fechamento","Placa CTA `SALVA PRA VIAGEM →`.")],
 tl="madrid de graça: o que vimos · [lugar 1] · [lugar 2] · [lugar 3] · [lugar 4] · [dica]",
 na="Sem narração.",
 lg="Madrid de graça: o que vimos sem pagar. 🇪🇸\n\n[lugar 1]\n[lugar 2]\n[lugar 3]\n[lugar 4]\n\n[dica real]\n\nSalva pra sua viagem a Madrid.",
 cta="Salva pra sua viagem a Madrid (salvamento).",
 cp="Primeiro lugar da lista. Texto da capa: “MADRID DE GRAÇA”.",
 so="Música da biblioteca; obturador só no 1º e no último item.",
 me="Salvamentos por alcance", hi="Lista de gratuidades é salva também em formato Reel.",
 te=None,
 ma=["Brutos de Madrid (decupagem pendente)"],
 pe=["Decupagem de Madrid: lugares gratuitos visitados", "Confirmar a gratuidade de cada lugar em 2027 nos sites oficiais"],
 of="Madrid", otr="Decupagem"),

dict(
 d="2027-01-13", h="18:00", f="C", k="ita", pl="UTIL", nv="—", st="dad",
 t="Itália em 9 dias: € [total]",
 ob="Salvamento e envio: o custo completo da viagem de 9 dias por 4 cidades, por pessoa. Fecha a série da Itália e serve de referência para quem planeja 2027.",
 mo="Quem planeja Itália em 2027. Salva como referência; envia para quem vai junto.",
 g="Itália em 9 dias: € [total].", gt="Preço",
 q0="Capa com foto (variante A do teste T4): arena do Coliseu (a capa do carrossel de Roma) ou outra foto forte, com Placa G `QUANTO CUSTOU` / `ITÁLIA`.",
 sl=["1 · Capa (foto): Placa G `QUANTO CUSTOU` / `ITÁLIA` + “9 dias, 4 cidades: € [total]”.",
     "2 · Recibo longo (segunda capa): Roma € 421,50 + Florença + Veneza + Milão + transporte entre cidades = total.",
     "3 · Roma: € 421,50 (3 dias, com hospedagem), foto.",
     "4 · Florença: € [valor], foto.",
     "5 · Veneza: € [valor], foto.",
     "6 · Milão: € [valor], foto.",
     "7 · Trens entre as cidades: € [valor].",
     "8 · O que mais pesou: hospedagem (Roma: 52,6%).",
     "9 · Dica (Bilhete) real.",
     "10 · Encerramento: Placa CTA `SALVA PRA VIAGEM →` + 1º."],
 tl="Slides acima. Etiqueta `QUANTO CUSTOU`.",
 na="Não se aplica (carrossel).",
 lg="Itália em 9 dias, 4 cidades: € [total] por pessoa (≈ R$ [valor]).\n\nRoma (3 dias): € 421,50\nFlorença: € [valor]\nVeneza: € [valor]\nMilão: € [valor]\nTrens entre as cidades: € [valor]\n\nViagem de 24/12/2024 a 04/01/2025, preços da época.\n\nCotação: € 1 = R$ 6,40 (PTAX de 24/12/2024).\n\nSalva pra sua viagem pela Itália.",
 cta="Salva pra sua viagem pela Itália (salvamento).",
 cp="Arena do Coliseu com a Placa G (teste T4, variante A).",
 so="Música instrumental da biblioteca ao postar.",
 me="Salvamentos e envios por alcance", hi="O custo total de uma viagem de várias cidades é referência e candidato a fixado.",
 te="T4:A",
 ma=["Registros de custos da Itália (Diego)", ROMA_FOTOS, "Fotos de Florença, Veneza e Milão (inventário pendente)"],
 pe=["Diego: custos de Florença, Veneza, Milão e trens", "Confirmar se a cotação da viagem toda pode ser a de 24/12/2024 ou se vale usar uma por cidade"],
 of="Itália", otr="Registro de custos"),

dict(
 d="2027-01-14", h="12:30", f="R", k="ams", pl="DESEJO", nv="B", st="dec",
 t="Amsterdam de bicicleta e canal",
 ob="Desejo com gancho escrito (5º ponto A do teste T2).",
 mo="Quem sonha com Amsterdam. Envia para quem iria junto.",
 g="A cidade onde a bicicleta manda.", gt="Afirmação",
 q0="Plano com bicicletas passando em frente a um canal (decupagem). Placa Marca.",
 sc=[("0–2 s","Gancho","Bicicletas + canal + Placa Marca + gancho escrito."),
     ("2–12 s","Desejo","5 planos de 1,5 a 2 s (bicicletas, pontes, canais), diferentes dos Reels de 27/10 e 06/12."),
     ("12–14 s","Fecho","Legenda Padrão: “amsterdam.”"),
     ("14–15 s","Loop","Volta ao quadro 0.")],
 tl="a cidade onde a bicicleta manda · amsterdam.",
 na="Sem narração.",
 lg="A cidade onde a bicicleta manda. 🚲\n\nAmsterdam, entre canais e pontes. Atravessar a rua lá é olhar primeiro para a ciclovia.\n\nManda pra quem iria pra Amsterdam com você.",
 cta="Manda pra quem iria pra Amsterdam com você (envio).",
 cp="Bicicletas no canal. Texto da capa: “AMSTERDAM”.",
 so="Música instrumental da biblioteca + ambiente.",
 me="Retenção média e envios", hi="Gancho escrito (5º ponto A do teste T2).",
 te="T2:A",
 ma=["Brutos de Amsterdam (decupagem pendente)"],
 pe=["Decupagem: planos com bicicletas", "A frase “olhar primeiro para a ciclovia” é observação geral: confirmar com o Diego que reflete o que viveram"],
 of="Amsterdam", otr="Decupagem"),

dict(
 d="2027-01-16", h="11:00", f="R", k="lis", pl="SERIE", nv="B", st="dec",
 t="Primeira noite em Lisboa",
 ob="Série: o primeiro (e quase único) momento em Lisboa, com chegada à noite e manhã seguinte. CTA de envio (teste T3, variante B).",
 mo="Brasileiros que vão a Portugal ou têm escala em Lisboa. Envia para quem vai a Lisboa.",
 g="Chegamos em Lisboa à noite. E agora?", gt="Pergunta",
 q0="Chegada em Lisboa à noite (decupagem) com a Placa `PRIMEIRO DIA EM / LISBOA`.",
 sc=[("0–2 s","Gancho","Chegada + Placa de abertura."),
     ("2–6 s","Contexto","Fala ou legenda Narrativa: “1 noite e 1 manhã.”"),
     ("6–18 s","Entrega","Noite e manhã, cortes de 1,5 a 3 s, na ordem."),
     ("18–22 s","Pico","O momento mais marcante (Ticket, se for surpresa real)."),
     ("22–25 s","Fechamento","Placa `E ISSO FOI SÓ O / PRIMEIRO DIA.` + 1º + bordão.")],
 tl="chegamos em lisboa à noite. e agora? · 1 noite e 1 manhã · [momentos] · e isso foi só o primeiro dia.",
 na="Só se não houver fala de chegada: narração curta (até 6 s).",
 lg="Chegamos em Lisboa à noite. E agora? 🇵🇹\n\nTínhamos 1 noite e 1 manhã. [o que fizeram, a preencher]\n\nManda pra quem vai pra Lisboa.",
 cta="Manda pra quem vai pra Lisboa (envio).",
 cp="Chegada à noite com a placa. Texto da capa: “1ª NOITE: LISBOA”.",
 so="Falas + música da biblioteca.",
 me="Envios e seguidores por 1.000 visualizações", hi="CTA de envio no Reel de série (teste T3, variante B).",
 te="T3:B",
 ma=["Brutos de Lisboa (decupagem pendente)", "Vlog de Lisboa (YouTube, 16/01)"],
 pe=["Decupagem de Lisboa", "Usar planos diferentes do Reel de 01/11 e do carrossel de 02/12"],
 of="Lisboa", otr="Decupagem"),

dict(
 d="2027-01-17", h="19:00", f="R", k="bcn", pl="UTIL", nv="B", st="ok",
 t="Por que ficamos em Gràcia (e não no centro)",
 ob="Salvamento: a escolha de bairro em Barcelona, com os motivos reais (residencial, cafés, mercado, metrô).",
 mo="Quem está escolhendo hospedagem em Barcelona. Salva para decidir; envia para quem reserva.",
 g="Por que não ficamos no centro.", gt="Afirmação",
 q0="Rua de Gràcia com cafés (master ≈ 11:00–11:30) com a Placa `ROTEIRO` / `GRÀCIA · BARCELONA`.",
 sc=[("0–2 s","Gancho","Rua de Gràcia + Placa Série."),
     ("2–9 s","Motivo 1","Master 02:39–03:00: “bairro residencial, mais distante da agonia do centro”."),
     ("9–15 s","Motivo 2","Master 10:57–11:40: “na rua que a gente está tem duas cafeterias, restaurante, barbearia”."),
     ("15–19 s","Motivo 3","Metrô perto + passe de 72 h. Bilhete: “dorme no bairro, passeia no centro.”"),
     ("19–21 s","Fechamento","Placa CTA `SALVA PRA VIAGEM →`.")],
 tl="por que não ficamos no centro · gràcia: residencial · cafés e mercado do lado · metrô perto · dorme no bairro, passeia no centro",
 na="Sem narração nova.",
 lg="Por que não ficamos no centro de Barcelona. 🏘️\n\nEscolhemos Gràcia: um bairro residencial, longe da muvuca do centro, com cafés, mercado e restaurantes na mesma rua, e metrô perto.\n\nCom o passe de 72 horas, ir ao centro era rápido. Dormir no bairro, passear no centro.\n\n[Valor da hospedagem por noite, se o Diego quiser incluir.]\n\nSalva pra escolher a sua hospedagem em Barcelona.",
 cta="Salva pra escolher a sua hospedagem (salvamento).",
 cp="Rua de Gràcia. Texto da capa: “FORA DO CENTRO”.",
 so="Falas originais + ambiente.",
 me="Salvamentos por alcance", hi="Escolha de bairro com motivos reais é muito salva (decisão difícil de quem reserva).",
 te=None,
 ma=[BCN_MASTER+": 02:39–03:09 e 10:57–11:42", BCN_TRANS],
 pe=["Valor da hospedagem (opcional)", "Checar trilha sob as falas"],
 of="Barcelona, dias 1 e 2", otr="Master 02:39–03:09 e 10:57–11:42"),

# ───────────────────────── Semana 16 (18 a 24/01, início da viagem em 20/01) ─────────────────────────
dict(
 d="2027-01-19", h="18:30", f="R", k="par", pl="UTIL", nv="B", st="ok",
 t="Onde ver a Torre Eiffel de graça",
 ob="Salvamento e envio: o lugar real de onde eles viram a Torre de dia (Champ de Mars), sem pagar nada. Peça pré-produzida para a semana da viagem.",
 mo="Quem vai a Paris. Salva para o roteiro; envia para quem vai junto.",
 g="A Torre Eiffel de graça é aqui.", gt="Afirmação",
 q0="IMG_2761 (2–3 s): os dois com a Torre ao fundo, gramado do Champ de Mars. Placa `ROTEIRO` / `CHAMP DE MARS`.",
 sc=[("0–2 s","Gancho","IMG_2761 + Placa Série."),
     ("2–8 s","Onde","Legenda Informação: `CHAMP DE MARS · GRÁTIS` + planos do gramado (decupagem)."),
     ("8–12 s","Prova","IMG_2978 (Torre, usado na apresentação) ou outro plano."),
     ("12–15 s","Fechamento","Placa CTA `SALVA PRA VIAGEM →`.")],
 tl="a torre eiffel de graça é aqui · champ de mars · grátis",
 na="Sem narração.",
 lg="A Torre Eiffel de graça é aqui. 🗼\n\nNo Champ de Mars, o gramado em frente à Torre, você vê a Torre inteira sem pagar nada. Foi de lá que tiramos essa foto.\n\nSalva pra sua viagem a Paris.",
 cta="Salva pra sua viagem a Paris (salvamento).",
 cp="Os dois com a Torre. Texto da capa: “DE GRAÇA AQUI”.",
 so="Música instrumental da biblioteca.",
 me="Salvamentos e envios", hi="Dica de lugar gratuito com foto própria é salva por quem vai a Paris.",
 te=None,
 ma=["IMG_2761.MOV", "IMG_2978 (Torre)", "Brutos de Paris (decupagem)", OUTRAS],
 pe=["Confirmar que a selfie é no Champ de Mars (o fundo indica que sim)", "Editar até 15/01 (semana de viagem)"],
 of="Paris", otr="IMG_2761"),

dict(
 d="2027-01-20", h="18:00", f="C", k="ams", pl="UTIL", nv="—", st="dec",
 t="Amsterdam em 3 dias: o roteiro que fizemos",
 ob="Salvamento: roteiro real de 3 dias em Amsterdam, publicado no dia do embarque (pré-produzido).",
 mo="Quem vai a Amsterdam. Salva o roteiro; envia para quem vai junto.",
 g="Amsterdam em 3 dias: nosso roteiro.", gt="Resultado primeiro",
 q0="Capa em papel (variante B do teste T4): Rota com os 3 dias.",
 sl=["1 · Capa (papel): Rota dos 3 dias.",
     "2 · Dia 1 (segunda capa, foto): chegada, Museumplein, centro (IMG_1384, IMG_1393).",
     "3–5 · Dia 1: fotos + informação das paradas.",
     "6–8 · Dia 2: fotos + informação.",
     "9–11 · Dia 3: fotos + informação.",
     "12 · Dica (Bilhete) real.",
     "13 · Encerramento: Placa CTA `SALVA PRA VIAGEM →` + 1º."],
 tl="Slides acima. Etiqueta `ROTEIRO`.",
 na="Não se aplica (carrossel).",
 lg="Amsterdam em 3 dias: o roteiro que fizemos. 🚲\n\nDia 1: chegada, Museumplein e centro\nDia 2: [paradas]\nDia 3: [paradas]\n\n[dica real]\n\nSalva pra sua viagem a Amsterdam.",
 cta="Salva pra sua viagem a Amsterdam (salvamento).",
 cp="Capa em papel com a Rota (teste T4, variante B).",
 so="Música instrumental da biblioteca ao postar.",
 me="Salvamentos por alcance", hi="Capa de papel (teste T4, variante B).",
 te="T4:B",
 ma=["IMG_1375, IMG_1384, IMG_1393", "Brutos de Amsterdam, dias 1 a 3 (decupagem pendente)", OUTRAS],
 pe=["Decupagem dos 3 dias", "Pronto até 15/01 (viagem)"],
 of="Amsterdam", otr="Decupagem"),

dict(
 d="2027-01-21", h="12:30", f="R", k="lis", pl="DESEJO", nv="B", st="dec",
 t="Lisboa de manhã, com 1 informação",
 ob="Desejo com informação prática (5º ponto B do teste T1). Pré-produzido para a semana da viagem.",
 mo="Brasileiros que sonham com Portugal. Envia; salva.",
 g="Lisboa de manhã cedo.", gt="Afirmação",
 q0="Plano da manhã em Lisboa (decupagem). Placa Marca.",
 sc=[("0–2 s","Gancho","Manhã em Lisboa + Placa Marca + gancho escrito."),
     ("2–10 s","Desejo","4 planos de 1,5 a 2 s."),
     ("10–13 s","Informação","Legenda Informação com 1 dado real (lugar, hora ou preço, conforme a decupagem) (variante B do teste T1)."),
     ("13–15 s","Loop","Volta ao quadro 0.")],
 tl="lisboa de manhã cedo · [1 informação real]",
 na="Sem narração.",
 lg="Lisboa de manhã cedo. ☀️\n\n[1 frase com a informação real]\n\nManda pra quem iria pra Lisboa com você.",
 cta="Manda pra quem iria pra Lisboa com você (envio).",
 cp="Manhã em Lisboa. Texto da capa: “LISBOA”.",
 so="Música instrumental da biblioteca.",
 me="Seguidores por 1.000 visualizações e envios", hi="Desejo + informação (5º ponto B do teste T1).",
 te="T1:B",
 ma=["Brutos de Lisboa (decupagem pendente)"],
 pe=["Decupagem: manhã", "Pronto até 15/01"],
 of="Lisboa", otr="Decupagem"),

dict(
 d="2027-01-23", h="11:00", f="R", k="jan", pl="SERIE", nv="A", st="fut",
 t="Primeiro dia em [cidade 1], ao vivo",
 ob="Série ao vivo: o primeiro Reel com Placar real (hora e gasto anotados no dia). É a prova máxima da promessa da marca.",
 mo="Quem segue o perfil e quem vai a [cidade 1]. Envia para quem vai; segue para ver as próximas cidades.",
 g="Primeiro dia em [cidade]: € [gasto].", gt="Preço",
 q0="Chegada em [cidade 1] (gravada no dia) com a Placa `PRIMEIRO DIA EM / [CIDADE 1]` e o Placar ligando em 2 s.",
 sc=[("0–2 s","Gancho","Chegada + Placa de abertura + gancho escrito."),
     ("2–5 s","Contexto","Placar liga `+00:00 · € 0,00` com Giro; placa sai pela direita; legenda Narrativa com onde e quando."),
     ("5–19 s","Entrega","Cortes de 1,5 a 3 s; Etiqueta de valor em cada compra, com o Placar girando (só valores anotados)."),
     ("19–23 s","Pico","Um destaque só: Carimbo PERRENGUE com data e hora reais ou Ticket SURPREENDE."),
     ("23–26 s","Fechamento","Placa `E ISSO FOI SÓ O / PRIMEIRO DIA.` + Nascer do 1º + bordão.")],
 tl="primeiro dia em [cidade 1]: € [gasto] · placar com hora e gasto reais · e isso foi só o primeiro dia.",
 na="Falas gravadas no dia. Narração só se faltar contexto.",
 lg="Primeiro dia em [cidade 1]: € [gasto real] por pessoa.\n\n[chegada, primeiros lugares, primeira comida, o que deu errado ou surpreendeu]\n\nCotação: € 1 = R$ [cotação do dia].\n\nSegue pra ver o primeiro dia da próxima cidade.",
 cta="Segue pra ver a próxima cidade (seguir).",
 cp="Chegada com a placa e o placar. Texto da capa: “DIA 1: [CIDADE]”.",
 so="Clack, tick e bordão conforme o DS 4.6; música da biblioteca.",
 me="Seguidores por 1.000 visualizações", hi="O formato completo (placa + placar real + objeto) ao vivo converte mais que os primeiros dias do acervo.",
 te="T3:B",
 ma=[VIAGEM],
 pe=["Cidades e ordem da viagem", "Registro de campo: hora de chegada e cada gasto", "Editar no máximo 2 dias depois de gravar"],
 of="Viagem de janeiro", otr="Gravação do dia"),

dict(
 d="2027-01-24", h="19:00", f="R", k="brg", pl="DESEJO", nv="B", st="dec",
 t="Bruges vista do canal",
 ob="Desejo puro (5º ponto A do teste T1). Pré-produzido para a semana da viagem.",
 mo="Quem sonha com a Europa e casais. Envia para o parceiro de viagem.",
 g="Bruges vista do canal.", gt="Afirmação",
 q0="Plano de canal de Bruges (decupagem). Placa Marca.",
 sc=[("0–2 s","Gancho","Canal + Placa Marca + gancho escrito."),
     ("2–12 s","Desejo","5 planos de 1,5 a 2 s, diferentes do Reel de 25/10, sem informação."),
     ("12–14 s","Fecho","Legenda Padrão: “bruges.”"),
     ("14–15 s","Loop","Volta ao quadro 0.")],
 tl="bruges vista do canal · bruges.",
 na="Sem narração.",
 lg="Bruges vista do canal. 🇧🇪\n\nO centro inteiro cabe num bate-volta de Bruxelas, e cada canal parece cenário.\n\nManda pra quem iria pra Bruges com você.",
 cta="Manda pra quem iria pra Bruges com você (envio).",
 cp="Canal de Bruges. Texto da capa: “BRUGES”.",
 so="Música instrumental da biblioteca.",
 me="Seguidores por 1.000 visualizações e envios", hi="Desejo puro (5º ponto A do teste T1).",
 te="T1:A",
 ma=["Brutos de Bruges (decupagem pendente: canais)"],
 pe=["Decupagem: há plano de canal? Se não houver, trocar por ruas e mudar o gancho para “Bruges parece maquete.”", "Pronto até 15/01"],
 of="Bruges", otr="Decupagem"),

# ───────────────────────── Semana 17 (25 a 31/01) ─────────────────────────
dict(
 d="2027-01-26", h="18:30", f="R", k="jan", pl="UTIL", nv="A", st="fut",
 t="Primeira hora em [cidade 2]: € [valor real]",
 ob="Utilidade ao vivo: quanto custa a primeira hora numa cidade nova (transporte do aeroporto ou da estação, primeira comida), com Placar real.",
 mo="Quem vai a [cidade 2]. Salva; envia para quem vai.",
 g="Primeira hora em [cidade 2]: € [valor].", gt="Preço",
 q0="Recibo em close com o total em PD Placar 128 px girando até o valor real, sobre a cena da chegada.",
 sc=[("0–2 s","Gancho","Recibo com o total girando."),
     ("2–5 s","Contexto","Placa `PRIMEIRO DIA EM / [CIDADE 2]` e Placar `+00:00`."),
     ("5–18 s","Entrega","Cada gasto da primeira hora com Etiqueta de valor e Placar girando."),
     ("18–21 s","Pico","Bilhete: a dica real (onde economizar)."),
     ("21–23 s","Fechamento","Placa CTA `SALVA PRA VIAGEM →`.")],
 tl="primeira hora em [cidade 2]: € [valor] · [gastos] · [dica]",
 na="Falas do dia.",
 lg="Primeira hora em [cidade 2]: € [valor] por pessoa.\n\n[transporte]: € [valor]\n[primeira comida]: € [valor]\n[outros]: € [valor]\n\n[dica]\n\nCotação: € 1 = R$ [cotação do dia].\n\nSalva pra sua viagem.",
 cta="Salva pra sua viagem (salvamento).",
 cp="Recibo da primeira hora. Texto da capa: “1ª HORA: € [VALOR]”.",
 so="Impressora térmica, tick; música da biblioteca.",
 me="Salvamentos e envios", hi="Custo da primeira hora ao vivo repete o sinal de envios do Reel de custo de 08/10.",
 te=None,
 ma=[VIAGEM],
 pe=["Registro de campo da primeira hora (hora e cada gasto)"],
 of="Viagem de janeiro", otr="Gravação do dia"),

dict(
 d="2027-01-27", h="18:00", f="C", k="mad", pl="UTIL", nv="—", st="dad",
 t="Madrid em 2 dias: € [total]",
 ob="Salvamento: custo real de Madrid por categoria. Pré-produzido para a semana da viagem.",
 mo="Quem vai à Espanha. Salva para orçar.",
 g="Madrid em 2 dias: € [total].", gt="Preço",
 q0="Capa com foto: Madrid com a Placa G `QUANTO CUSTOU` / `MADRID`.",
 sl=["1 · Capa (foto): Madrid + Placa G + total.",
     "2 · Recibo (segunda capa) por categoria e por pessoa.",
     "3–7 · Fotos + informação dos lugares e dos gastos.",
     "8 · Comparação com Barcelona (custo por dia), se os dados existirem.",
     "9 · Dica (Bilhete).",
     "10 · Encerramento: Placa CTA `SALVA PRA VIAGEM →` + 1º."],
 tl="Slides acima. Etiqueta `QUANTO CUSTOU`.",
 na="Não se aplica (carrossel).",
 lg="Madrid em 2 dias: € [total] por pessoa (≈ R$ [valor]).\n\n[categorias, a preencher]\n\nCotação: € 1 = R$ [PTAX da data da viagem].\n\nSalva pra sua viagem à Espanha.",
 cta="Salva pra sua viagem à Espanha (salvamento).",
 cp="Madrid com a Placa G.",
 so="Música instrumental da biblioteca ao postar.",
 me="Salvamentos por alcance", hi="Custo por cidade (série de custos).",
 te=None,
 ma=["Registro de custos de Madrid (Diego)", "Fotos de Madrid"],
 pe=["Diego: custos de Madrid", "Pronto até 15/01"],
 of="Madrid", otr="Registro de custos"),

dict(
 d="2027-01-28", h="12:30", f="R", k="dis", pl="EXP", nv="B", st="dec",
 t="Disney: o momento em que valeu",
 ob="Identificação e desejo: o momento real em que a Disney valeu a pena (reação filmada). Pré-produzido para a semana da viagem.",
 mo="Fãs da Disney. Envia para quem sonha em ir.",
 g="O momento em que a Disney valeu.", gt="“Eu não esperava isso”",
 q0="A reação real (decupagem). Legenda Emocional.",
 sc=[("0–2 s","Gancho","Reação + legenda Emocional."),
     ("2–12 s","Momento","O momento inteiro, com som direto."),
     ("12–15 s","Fecho","Ticket SURPREENDE se foi acima da expectativa."),
     ("15–16 s","Loop","Volta ao quadro 0.")],
 tl="o momento em que a disney valeu · [momento]",
 na="Sem narração.",
 lg="O momento em que a Disney valeu. ✨\n\n[o que aconteceu, do jeito que foi]\n\nManda pra quem sonha com a Disney.",
 cta="Manda pra quem sonha com a Disney (envio).",
 cp="Reação. Texto da capa: “VALEU AQUI”.",
 so="Som direto (sem trilhas da Disney como música).",
 me="Envios por alcance", hi="Momento emocional real gera envios.",
 te=None,
 ma=["Brutos da Disney (decupagem pendente)"],
 pe=["Decupagem: há reação filmada? Se não houver, trocar por “Disney: a fila que valeu”, só com dado real de espera", "Pronto até 15/01"],
 of="Disneyland Paris", otr="Decupagem"),

dict(
 d="2027-01-30", h="11:00", f="R", k="jan", pl="SERIE", nv="A", st="fut",
 t="Primeiro dia em [cidade 2 ou 3], ao vivo",
 ob="Série ao vivo com Placar real, segunda cidade da viagem.",
 mo="Quem acompanha a viagem e quem vai à cidade. Envia; segue.",
 g="Primeiro dia em [cidade]: [momento real].", gt="Afirmação",
 q0="Chegada com a Placa de abertura e o Placar ligando em 2 s.",
 sc=[("0–2 s","Gancho","Chegada + Placa de abertura + gancho com o momento real."),
     ("2–5 s","Contexto","Placar `+00:00 · € 0,00`."),
     ("5–19 s","Entrega","Cortes; Etiqueta de valor em cada compra."),
     ("19–23 s","Pico","Carimbo ou Ticket (um só, real)."),
     ("23–26 s","Fechamento","Placa de fechamento + Nascer do 1º + bordão.")],
 tl="primeiro dia em [cidade] · [momento] · e isso foi só o primeiro dia.",
 na="Falas do dia.",
 lg="Primeiro dia em [cidade]: [momento real].\n\n[resumo do dia com gastos reais]\n\nCotação: € 1 = R$ [cotação do dia].\n\nManda pra quem vai pra [cidade].",
 cta="Manda pra quem vai pra [cidade] (envio).",
 cp="Chegada com a placa. Texto da capa: “DIA 1: [CIDADE]”.",
 so="Conforme DS 4.6.",
 me="Seguidores por 1.000 visualizações e envios", hi="Gancho de momento (e não de preço) no Reel de série ao vivo: comparar com o de 23/01.",
 te=None,
 ma=[VIAGEM],
 pe=["Registro de campo", "Editar no máximo 2 dias depois de gravar"],
 of="Viagem de janeiro", otr="Gravação do dia"),

dict(
 d="2027-01-31", h="19:00", f="R", k="multi", pl="DESEJO", nv="B", st="dec",
 t="Qual dessas você visitaria primeiro? (sem texto)",
 ob="Comentários e alcance: uma cena por cidade do acervo, sem gancho escrito (5º ponto B do teste T2), terminando em pergunta.",
 mo="Quem sonha com a Europa. Comenta a escolha; envia para quem vai decidir junto.",
 g="(sem texto nos 2 primeiros segundos)", gt="Visual (sem texto)",
 q0="A cena mais bonita do acervo inteiro (a definir pelo melhor desempenho das Leituras 1 e 2). Placa Marca.",
 sc=[("0–2 s","Gancho visual","Melhor cena + Placa Marca. Sem texto."),
     ("2–16 s","Cidades","1 cena por cidade, 1,5 s cada, com o nome em legenda Informação."),
     ("16–19 s","Pergunta","Legenda: “qual você visitaria primeiro?”")],
 tl="(nada até 2 s) · nomes das cidades · qual você visitaria primeiro?",
 na="Sem narração.",
 lg="Qual dessas você visitaria primeiro? 🌍\n\nBarcelona, Amsterdam, Bruxelas, Bruges, Paris, Disneyland Paris, Madrid, Lisboa, Roma, Florença, Veneza ou Milão.\n\nResponde aqui que eu te conto como foi o primeiro dia lá.",
 cta="Responde nos comentários (comentário).",
 cp="Melhor cena do acervo. Texto da capa: “QUAL PRIMEIRO?”",
 so="Música da biblioteca com batida.",
 me="Comentários e retenção média", hi="Sem texto (5º ponto B do teste T2).",
 te="T2:B",
 ma=["1 cena por cidade (acervo)"],
 pe=["Escolher as cenas pelos Reels de melhor retenção das Leituras 1 e 2", "Pronto até 15/01"],
 of="Vários destinos", otr="Acervo"),

# ───────────────────────── Semana 18 (01 a 07/02) ─────────────────────────
dict(
 d="2027-02-02", h="18:30", f="R", k="jan", pl="EXP", nv="B", st="fut",
 t="Vale ou pula: [atração da viagem], ao vivo",
 ob="Utilidade e identificação ao vivo: um veredito rápido de uma atração ou comida da viagem.",
 mo="Quem vai à cidade. Envia; comenta.",
 g="Vale ou pula: [atração]?", gt="Vale a pena?",
 q0="Atração com a Placa `VALE OU PULA` / `[ATRAÇÃO]`.",
 sc=[("0–2 s","Gancho","Atração + Placa Série."),
     ("2–14 s","Prova","Experiência real com preço (Etiqueta de valor)."),
     ("14–18 s","Veredito","Bilhete veredito."),
     ("18–20 s","Loop","Volta ao quadro 0.")],
 tl="vale ou pula: [atração]? · € [valor] · [veredito]",
 na="Falas do dia.",
 lg="Vale ou pula: [atração] em [cidade]?\n\n€ [valor] (≈ R$ [valor]). Veredito: [vale/pula/depende], [motivo].\n\nCotação: € 1 = R$ [cotação do dia].\n\nE você, iria?",
 cta="Responde se iria (comentário).",
 cp="Atração. Texto da capa: “VALE OU PULA?”",
 so="Conforme DS 4.6.",
 me="Envios e comentários", hi="Vale ou pula ao vivo mantém a série com dado fresco.",
 te=None,
 ma=[VIAGEM],
 pe=["Escolher a atração na viagem"],
 of="Viagem de janeiro", otr="Gravação do dia"),

dict(
 d="2027-02-03", h="18:00", f="C", k="jan", pl="UTIL", nv="—", st="fut",
 t="[Cidade 1]: o primeiro dia em números",
 ob="Salvamento: o primeiro dia ao vivo em formato de consulta (horários, gastos, rota), com dados do registro de campo.",
 mo="Quem vai à cidade. Salva para copiar o dia.",
 g="[Cidade 1]: o primeiro dia em números.", gt="Resultado primeiro",
 q0="Capa com foto da chegada + Placa G `PRIMEIRO DIA EM / [CIDADE 1]`.",
 sl=["1 · Capa (foto): chegada + Placa G.",
     "2 · Rota com horários reais (Plex Mono) — segunda capa.",
     "3 · Recibo do dia com todos os gastos.",
     "4–8 · Fotos + informação de cada parada.",
     "9 · Dica (Bilhete).",
     "10 · Encerramento: Placa CTA `SALVA PRA VIAGEM →` + 1º."],
 tl="Slides acima. Etiqueta `ROTEIRO`.",
 na="Não se aplica (carrossel).",
 lg="[Cidade 1]: o primeiro dia em números.\n\n[horários e gastos reais]\n\nCotação: € 1 = R$ [cotação do dia].\n\nSalva pra sua viagem.",
 cta="Salva pra sua viagem (salvamento).",
 cp="Chegada com a Placa G.",
 so="Música instrumental da biblioteca ao postar.",
 me="Salvamentos por alcance", hi="Primeiro dia com horários reais é o carrossel mais completo da marca.",
 te=None,
 ma=[VIAGEM],
 pe=["Registro de campo completo do dia 1 da cidade 1"],
 of="Viagem de janeiro", otr="Registro de campo"),

dict(
 d="2027-02-04", h="12:30", f="R", k="multi", pl="UTIL", nv="A", st="dad",
 t="Qual cidade foi a mais barata?",
 ob="Envio e comentários: o resultado da comparação de custos (carrossel de 06/01) em formato Reel, com a surpresa (se houver).",
 mo="Quem planeja viagem com orçamento. Envia para quem vai decidir junto; comenta palpites.",
 g="A cidade mais barata foi essa.", gt="Resultado primeiro",
 q0="A cidade mais barata, com o Recibo do custo por dia já impresso.",
 sc=[("0–2 s","Gancho","Cidade mais barata + Recibo."),
     ("2–14 s","Ranking","Quadro do mais caro ao mais barato, cena de cada cidade (Snap)."),
     ("14–18 s","Pico","Ticket SURPREENDE se a mais barata foi inesperada (só se foi)."),
     ("18–20 s","Fechamento","Placa CTA `MANDA PRA QUEM VAI →`.")],
 tl="a cidade mais barata foi essa · [ranking] · € [valor]/dia",
 na="Narração curta do Diego (até 6 s).",
 lg="A cidade mais barata da nossa viagem foi [cidade]: € [valor] por dia, por pessoa.\n\n[ranking resumido]\n\nCotações datadas no carrossel de custos do perfil.\n\nManda pra quem vai decidir a viagem com você.",
 cta="Manda pra quem vai decidir a viagem com você (envio).",
 cp="Cidade mais barata com o recibo. Texto da capa: “A MAIS BARATA”.",
 so="Tick, impressora; música da biblioteca.",
 me="Envios por alcance", hi="Comparação entre cidades (teste T5, variante B).",
 te="T5:B",
 ma=["Dados do carrossel de 06/01", "1 cena por cidade"],
 pe=["Depende dos custos de todas as cidades", "Pronto até 15/01"],
 of="Vários destinos (custos)", otr="Registro de custos"),

dict(
 d="2027-02-06", h="11:00", f="R", k="jan", pl="SERIE", nv="A", st="fut",
 t="Primeiro dia em [cidade 3], ao vivo",
 ob="Série ao vivo com Placar real, terceira cidade.",
 mo="Quem acompanha a viagem. Segue; envia.",
 g="Primeiro dia em [cidade 3]: [gancho real].", gt="A definir no dia",
 q0="Chegada com a Placa de abertura e o Placar.",
 sc=[("0–2 s","Gancho","Chegada + Placa + gancho (o tipo que estiver ganhando na Leitura 3)."),
     ("2–5 s","Contexto","Placar."),
     ("5–19 s","Entrega","Cortes; Etiqueta de valor."),
     ("19–23 s","Pico","Carimbo ou Ticket (um só, real)."),
     ("23–26 s","Fechamento","Placa de fechamento + 1º + bordão.")],
 tl="primeiro dia em [cidade 3] · e isso foi só o primeiro dia.",
 na="Falas do dia.",
 lg="Primeiro dia em [cidade 3]: [gancho].\n\n[resumo com gastos reais]\n\nCotação: € 1 = R$ [cotação do dia].\n\nSegue pra ver o balanço da viagem.",
 cta="Segue pra ver o balanço (seguir).",
 cp="Chegada com a placa.",
 so="Conforme DS 4.6.",
 me="Seguidores por 1.000 visualizações", hi="Aplicar o tipo de gancho vencedor da Leitura 3.",
 te=None,
 ma=[VIAGEM],
 pe=["Registro de campo"],
 of="Viagem de janeiro", otr="Gravação do dia"),

dict(
 d="2027-02-07", h="19:00", f="R", k="jan", pl="SERIE", nv="B", st="fut",
 t="3 países, [N] primeiros dias: o balanço",
 ob="Conversão e fechamento: balanço da viagem com o total real e a pergunta “qual a próxima?”.",
 mo="Quem acompanhou. Comenta a próxima cidade; segue.",
 g="[N] primeiros dias. Quanto custou tudo?", gt="Pergunta",
 q0="Recibo longo da viagem imprimindo sobre a última cena.",
 sc=[("0–2 s","Gancho","Recibo da viagem."),
     ("2–14 s","Recap","1 chegada por cidade, Snap."),
     ("14–18 s","Total","Total real por pessoa."),
     ("18–21 s","Fechamento","Placa de fechamento + 1º. Legenda: “qual a próxima?”")],
 tl="[n] primeiros dias · € [total] · qual a próxima?",
 na="Narração curta do Diego (até 6 s), gravada no fim da viagem.",
 lg="[N] primeiros dias em 3 países: € [total] por pessoa.\n\n[resumo]\n\nCotação: € 1 = R$ [cotação].\n\nQual deve ser a próxima cidade? Comenta aqui.",
 cta="Comenta a próxima cidade (comentário).",
 cp="Recibo da viagem. Texto da capa: “QUANTO CUSTOU TUDO”.",
 so="Conforme DS 4.6.",
 me="Comentários e seguidores", hi="Balanço com pergunta abre o próximo ciclo.",
 te=None,
 ma=[VIAGEM],
 pe=["Total da viagem (registro de campo)"],
 of="Viagem de janeiro", otr="Fim da viagem"),
]
