# -*- coding: utf-8 -*-
"""Peças do calendário v3 (parte 2: 02/11 a 29/11/2026). Chaves: ver v3_pecas_1.py."""
from v3_pecas_1 import BCN_MASTER, BCN_TRANS, OUTRAS, ROMA_FOTOS

PECAS = [
# ───────────────────────── Semana 5 (02 a 08/11) ─────────────────────────
dict(
 d="2026-11-03", h="18:30", f="R", k="multi", pl="SERIE", nv="A", st="dec",
 t="8 cidades, 8 primeiros dias",
 ob="Conversão: deixar clara a promessa do perfil para quem chegou pelos Reels de outras cidades. É a “vitrine” da série, para fixar no perfil se converter bem.",
 mo="Quem viu um Reel e visitou o perfil; quem sonha em fazer um mochilão. Segue porque entende o que vai ver; envia para quem quer fazer roteiro por várias cidades.",
 g="8 cidades, 8 primeiros dias.", gt="Resultado primeiro",
 q0="A Placa `PRIMEIRO DIA EM / BARCELONA` sobre a primeira cena da chegada em Barcelona (“Buenos días”).",
 sc=[("0–2 s","Gancho","Barcelona, master 00:00–00:02 + Placa de abertura. Legenda Padrão com o gancho e Destaque em “8”."),
     ("2–18 s","Ritmo","Uma cena de chegada por cidade, 2 s cada, na ordem real da viagem: Barcelona, Amsterdam (IMG_1384), Bruxelas (IMG_2170), Bruges (IMG_2693), Paris (IMG_2730), Disneyland Paris, Madrid, Lisboa. A placa troca o nome da cidade com a virada (troca de texto, 240 ms). Snap entre cidades."),
     ("18–23 s","Promessa","Diego (narração ou fala da apresentação REV8): “aqui eu te mostro o primeiro dia em cada cidade que eu visito.”"),
     ("23–26 s","Fechamento","Placa `E ISSO FOI SÓ O / PRIMEIRO DIA.` + 1º. Legenda: “segue pra ver a próxima.”")],
 tl="8 cidades, 8 primeiros dias · barcelona · amsterdam · bruxelas · bruges · paris · disneyland paris · madrid · lisboa · segue pra ver a próxima",
 na="Reaproveitar a narração aprovada da apresentação (reels/apresentacao/narracao/narracao.m4a, trecho “aqui eu te mostro o primeiro dia em cada cidade que eu visito”) ou gravar uma frase nova de até 4 s.",
 lg="8 cidades, 8 primeiros dias. ✈️\n\nBarcelona, Amsterdam, Bruxelas, Bruges, Paris, Disneyland Paris, Madrid e Lisboa. Em cada uma, eu mostro o primeiro dia como ele foi: a chegada, o que custou, o que deu errado e o que valeu.\n\nTem roteiro, preço real e perrengue também.\n\nSegue pra ver o primeiro dia de cada uma.",
 cta="Segue pra ver o primeiro dia de cada cidade (seguir).",
 cp="Mosaico não: uma cena de chegada forte (Barcelona) com a placa. Texto da capa: “8 PRIMEIROS DIAS”.",
 so="Música instrumental da biblioteca com batida para os cortes; clack a cada troca de placa (máx. 1 efeito a cada 1,5 s).",
 me="Seguidores por 1.000 visualizações", hi="Um Reel que explica a série converte mais visitantes em seguidores que qualquer Reel de cidade isolada.",
 te="T3:A",
 ma=[BCN_MASTER+": 00:00–00:05", "IMG_1384 (Amsterdam), IMG_2170 (Bruxelas), IMG_2693 (Bruges), IMG_2730 (Paris)", "Brutos de chegada da Disney, Madrid e Lisboa (decupagem pendente)", "reels/apresentacao/narracao/narracao.m4a", OUTRAS],
 pe=["Ordem real das cidades na viagem (definir antes de montar)", "1 cena de chegada da Disney, de Madrid e de Lisboa", "Avaliar fixar no perfil se os seguidores por 1.000 visualizações passarem os da apresentação"],
 of="Vários destinos", otr="Uma chegada por cidade"),

dict(
 d="2026-11-04", h="18:00", f="C", k="ita", pl="UTIL", nv="—", st="ok",
 t="Roma de graça (ou quase): o que vimos sem pagar",
 ob="Salvamento: a lista real do que dá para ver em Roma sem ingresso, com os preços de 2026 de quem passou a cobrar. Ângulo diferente do carrossel de custo de 06/10.",
 mo="Quem vai a Roma com orçamento apertado. Salva para o roteiro; envia para quem vai junto.",
 g="Roma de graça (ou quase).", gt="Lista curta",
 q0="Capa: foto do Pincio ao pôr do sol (IMG_5220) com Placa G `QUANTO CUSTOU` / `ROMA` e “de graça (ou quase)”.",
 sl=["1 · Capa (foto em sangria): Pincio, Placa G Série `QUANTO CUSTOU` / `ROMA` + “de graça (ou quase)”.",
     "2 · Quadro (segunda capa): GRÁTIS: Piazza Navona, Piazza di Spagna, Piazza del Popolo, Pincio, Villa Borghese (parque), Basílica de São Pedro, Gianicolo · QUASE: Trevi € 2 (desde 02/2026), Panteão € 7 (desde 07/2026), espelho de Sant'Ignazio € 1.",
     "3 · Foto + informação: Piazza Navona (IMG_5132). Grátis.",
     "4 · Foto + informação: Fontana di Trevi (IMG_5064). De longe, grátis; perto da fonte, € 2 desde fevereiro de 2026.",
     "5 · Foto + informação: Panteão (IMG_5108). € 5 em 2024; € 7 desde julho de 2026.",
     "6 · Foto + informação: Terrazza del Pincio ao pôr do sol (IMG_5220). Grátis.",
     "7 · Foto + informação: Basílica de São Pedro (IMG_6653). Entrada grátis; chegue cedo por causa da fila.",
     "8 · Foto + informação: Sant'Ignazio (IMG_6650). Igreja grátis; o espelho para ver o teto custou € 1.",
     "9 · Foto + informação: Gianicolo ao pôr do sol (IMG_5523). Grátis.",
     "10 · Dica (Bilhete): “o que pesa em roma é comer e dormir, não ver.”",
     "11 · Encerramento: Placa CTA `SALVA PRA VIAGEM →` + 1º."],
 tl="Slides acima. Etiqueta `QUANTO CUSTOU`.",
 na="Não se aplica (carrossel).",
 lg="Roma de graça (ou quase). 🇮🇹\n\nO que a gente viu em Roma sem pagar entrada:\nPiazza Navona, Piazza di Spagna, Piazza del Popolo, Terrazza del Pincio, Villa Borghese, Basílica de São Pedro e o Gianicolo ao pôr do sol.\n\nQuase de graça:\nFontana di Trevi: € 2 para chegar perto (desde fevereiro de 2026)\nPanteão: € 7 (desde julho de 2026; pagamos € 5 em 2024)\nEspelho do teto de Sant'Ignazio: € 1\n\nO que pesa em Roma é comer e dormir, não ver.\n\nCotação: € 1 = R$ 5,88 (02/10/2026).\n\nSalva pra sua viagem a Roma.",
 cta="Salva pra sua viagem a Roma (salvamento).",
 cp="Pincio ao pôr do sol com a Placa G.",
 so="Música instrumental da biblioteca ao postar.",
 me="Salvamentos por alcance", hi="Lista “grátis × quase grátis” é mais salvável que o roteiro com custo total.",
 te="T4:A",
 ma=["IMG_5132 (Navona), IMG_5064 (Trevi), IMG_5108 (Panteão), IMG_5220 (Pincio), IMG_6653 (São Pedro), IMG_6650 (Sant'Ignazio), IMG_5523 (Gianicolo)", ROMA_FOTOS],
 pe=["Reconferir na véspera: entrada gratuita da Basílica de São Pedro, Trevi € 2 e Panteão € 7", "Fotos de Piazza di Spagna, Piazza del Popolo e Villa Borghese: localizar no acervo (só entram no slide 2 se não houver foto)", "IMG_6650 tem Marina: ok (parceira de viagem)"],
 of="Fotos da Itália", otr="Roma, dias 1 a 3"),

dict(
 d="2026-11-05", h="12:30", f="R", k="bcn", pl="UTIL", nv="B", st="ok",
 t="€ 1 cada, só às quartas: 100 Montaditos",
 ob="Envio: dica de preço baixo, concreta e fácil de repassar, com prova filmada.",
 mo="Quem vai à Espanha com orçamento curto. Envia para quem vai junto; salva para lembrar o dia da semana.",
 g="€ 1 cada, só às quartas.", gt="Preço",
 q0="Close dos montaditos na mesa (master ≈ 32:58) com Etiqueta de valor `€ 1` entrando.",
 sc=[("0–2 s","Gancho","Close dos montaditos + Etiqueta de valor `€ 1 ≈ R$ [x]`. Legenda Padrão com Destaque em “1”."),
     ("2–9 s","Contexto","Master 32:58–33:15: “cervejaria 100 Montaditos… hoje é quarta-feira, e quarta-feira é um euro cada montadito. Fica a dica.”"),
     ("9–13 s","Pico","Diego comendo + Bilhete: “dica: quarta à noite.”"),
     ("13–15 s","Loop","Corte para os montaditos do quadro 0.")],
 tl="€ 1 cada, só às quartas · 100 montaditos · dica: quarta à noite",
 na="Sem narração nova.",
 lg="€ 1 cada, só às quartas. 🥪\n\nNa rede 100 Montaditos, na Espanha, os montaditos custavam € 1 cada na quarta-feira, o dia em que a gente foi, em Barcelona. Pedimos vários e uma cerveja para acompanhar.\n\nAntes de ir, confira se a promoção continua e quais itens entram.\n\nCotação: € 1 = R$ [PTAX da data da viagem].\n\nManda pra quem vai pra Espanha com você.",
 cta="Manda pra quem vai pra Espanha com você (envio).",
 cp="Montaditos na mesa. Texto da capa: “€ 1 NA QUARTA”.",
 so="Falas originais + ambiente do bar. *tick* do preço quando existir.",
 me="Envios por alcance", hi="Preço baixo concreto (€ 1) gera envios; comparar com a dica da água (13/10), também de cidade única.",
 te="T5:A",
 ma=[BCN_MASTER+": 32:58–33:20 (dia 3)", BCN_TRANS],
 pe=["Conferir se a promoção de quarta continua em 2026 e quais itens entram (site da rede)", "Data da viagem para a cotação"],
 of="Barcelona, dia 3", otr="Master 32:58–33:20"),

dict(
 d="2026-11-07", h="11:00", f="R", k="par", pl="DESEJO", nv="B", st="dec",
 t="A Torre Eiffel pisca de hora em hora",
 ob="Desejo com informação útil: o brilho da Torre à noite, com o horário que faz a pessoa planejar a noite em Paris.",
 mo="Quem sonha com Paris e casais. Envia para o parceiro (“vamos ver isso”); salva para a noite em Paris.",
 g="A Torre Eiffel pisca a cada hora.", gt="Surpresa",
 q0="A Torre brilhando à noite (plano da decupagem), já com as luzes piscando. Placa Marca `PRIMEIRO DIA →`.",
 sc=[("0–2 s","Gancho","Torre piscando + Placa Marca + legenda Padrão com o gancho."),
     ("2–8 s","Desejo","2 ou 3 planos da Torre à noite; Etiqueta Informação: `BRILHO · 5 MIN · NA HORA CHEIA` (variante B do teste T1)."),
     ("8–12 s","Contexto","IMG_3134 (40–47 s): “agora a gente vai ver a Torre Eiffel de noite, ver ela brilhar.”"),
     ("12–15 s","Loop","Volta à Torre do quadro 0.")],
 tl="a torre eiffel pisca a cada hora · 5 minutos, na hora cheia, depois que escurece",
 na="Sem narração nova.",
 lg="A Torre Eiffel pisca a cada hora. ✨\n\nDepois que escurece, a Torre ganha um brilho de luzes piscando por 5 minutos no começo de cada hora. A gente fechou o único dia em Paris vendo isso.\n\nDica: escolha o lugar uns 10 minutos antes da hora cheia.\n\nManda pra quem vai ver a Torre brilhar com você.",
 cta="Manda pra quem vai ver a Torre brilhar com você (envio).",
 cp="Torre brilhando. Texto da capa: “ELA PISCA?”",
 so="Ambiente da noite + música instrumental da biblioteca.",
 me="Seguidores por 1.000 visualizações e envios", hi="Desejo com 1 informação útil converte mais que desejo puro (2º ponto B do teste T1).",
 te="T1:B",
 ma=["Brutos de Paris: Torre Eiffel à noite (decupagem pendente)", "IMG_3134.MOV (40–47 s)", OUTRAS],
 pe=["Confirmar que existe plano da Torre brilhando. Plano B: trocar por Torre de dia (IMG_2761 e IMG_2978) com o gancho “Onde ver a Torre Eiffel de graça.” (Champ de Mars)", "Reconferir no site oficial (toureiffel.paris) a regra do brilho (5 minutos no começo de cada hora, até o horário de encerramento)"],
 of="Brutos de Paris", otr="Noite do dia 1"),

dict(
 d="2026-11-08", h="19:00", f="R", k="mad", pl="SERIE", nv="B", st="dec",
 t="Primeiro dia em Madrid",
 ob="Série e envio: o primeiro dia em Madrid em 25 segundos, da chegada ao momento que mais marcou.",
 mo="Quem vai à Espanha e decide entre Madrid e Barcelona. Envia para quem vai a Madrid.",
 g="Primeiro dia em Madrid: [momento real].", gt="Afirmação",
 q0="Cena de chegada em Madrid (decupagem) com a Placa `PRIMEIRO DIA EM / MADRID`.",
 sc=[("0–2 s","Gancho","Chegada + Placa de abertura. Gancho escrito com o momento real que mais marcou o dia (definir na decupagem, até 7 palavras)."),
     ("2–5 s","Contexto","Fala de chegada ou legenda Narrativa: “madrid, dia 1 de 2.”"),
     ("5–19 s","Entrega","Cortes de 1,5 a 3 s com os lugares do dia, na ordem. Etiqueta de valor em cada compra registrada."),
     ("19–23 s","Pico","Perrengue (Carimbo, só com data e hora reais) ou surpresa (Ticket). Um só."),
     ("23–26 s","Fechamento","Placa `E ISSO FOI SÓ O / PRIMEIRO DIA.` + 1º + bordão.")],
 tl="primeiro dia em madrid · [lugares do dia] · [valores registrados] · e isso foi só o primeiro dia.",
 na="Só se o bruto não tiver fala de chegada: narração curta do Diego (até 6 s) dizendo onde estão e o plano do dia.",
 lg="Primeiro dia em Madrid: [momento real que abre o Reel].\n\nChegamos [como e quando, a preencher] e o plano do dia 1 era [a preencher].\n\n[2 ou 3 linhas com o que aconteceu de verdade, com preço quando houver]\n\nManda pra quem vai pra Madrid.",
 cta="Manda pra quem vai pra Madrid (envio).",
 cp="Chegada em Madrid com a placa. Texto da capa: “DIA 1: MADRID”.",
 so="Falas originais + música da biblioteca.",
 me="Envios e seguidores por 1.000 visualizações", hi="CTA de envio no Reel de série (variante B do teste T3).",
 te="T3:B",
 ma=["Brutos de Madrid, dia 1 (decupagem pendente)", "Vlog de Madrid (em edição para o YouTube de 05/12)"],
 pe=["Decupagem de Madrid, dia 1: chegada, lugares, comida, pico", "Gancho final depende do momento real escolhido", "Valores gastos no dia 1 (se houver registro)"],
 of="Madrid, dia 1", otr="Decupagem"),

# ───────────────────────── Semana 6 (09 a 15/11) ─────────────────────────
dict(
 d="2026-11-10", h="18:30", f="R", k="ita", pl="EXP", nv="B", st="ok",
 t="€ 1 pra ver esse teto em Roma",
 ob="Surpresa e envio: uma experiência pouco conhecida, barata e bonita, com foto própria.",
 mo="Quem vai a Roma e quem gosta de curiosidade. Envia porque é segredo barato; salva para o roteiro.",
 g="€ 1 pra ver esse teto.", gt="Surpresa",
 q0="Foto do teto pintado de Sant'Ignazio (IMG_6650) com zoom sutil e a Etiqueta de valor `€ 1` já na tela.",
 sc=[("0–2 s","Gancho","IMG_6650 + Etiqueta de valor `€ 1 ≈ R$ 6,40`. Legenda Padrão com o gancho."),
     ("2–7 s","Contexto","Legenda Narrativa: “igreja de sant'ignazio, roma. a entrada é grátis.”"),
     ("7–12 s","Pico","Ticket SURPREENDE: “o espelho mostra o teto sem torcer o pescoço.” Legenda Emocional: “eu não esperava ISSO”."),
     ("12–15 s","Loop","Volta ao teto do quadro 0.")],
 tl="€ 1 pra ver esse teto · igreja de sant'ignazio, roma · entrada grátis · o espelho custa € 1",
 na="Sem narração.",
 lg="€ 1 pra ver esse teto em Roma. 🪞\n\nNa Igreja de Sant'Ignazio, perto do Panteão, a entrada é grátis. Lá dentro, um espelho mostra o teto pintado sem você precisar torcer o pescoço. A gente pagou € 1 (≈ R$ 6,40) para usar.\n\nCotação: € 1 = R$ 6,40 (PTAX de 24/12/2024).\n\nManda pra quem vai pra Roma e ainda não conhece.",
 cta="Manda pra quem vai pra Roma (envio).",
 cp="Teto de Sant'Ignazio. Texto da capa: “€ 1 PRA ISSO”.",
 so="Música instrumental da biblioteca. *ding* do Ticket quando existir.",
 me="Envios por alcance", hi="Experiência barata e pouco conhecida gera envios mesmo vinda de fotos.",
 te=None,
 ma=["IMG_6650 (Sant'Ignazio, 27/12/2024 12:31)", ROMA_FOTOS],
 pe=["Se houver foto do teto no espelho (não veio para o carrossel), usar como segunda cena", "Conferir se o espelho continua cobrando € 1 em 2026 antes de dizer que ainda existe"],
 of="Fotos da Itália", otr="IMG_6650"),

dict(
 d="2026-11-11", h="18:00", f="C", k="brg", pl="UTIL", nv="—", st="dad",
 t="Bate-volta de Bruxelas a Bruges: como fizemos",
 ob="Salvamento: o passo a passo real do bate-volta (transporte, tempo, custo e o que deu para ver), conteúdo de consulta muito buscado.",
 mo="Quem vai a Bruxelas e quer encaixar Bruges. Salva para planejar; envia para quem divide a viagem.",
 g="Bate-volta de Bruxelas a Bruges.", gt="Resultado primeiro",
 q0="Capa em papel (variante B do teste T4): Rota Bruxelas → Bruges com tempo e preço do trajeto.",
 sl=["1 · Capa (papel, variante B): Rota `BRUXELAS → BRUGES` com tempo e preço (a confirmar) + título.",
     "2 · Recibo do bate-volta (segunda capa): transporte ida e volta, comida, extras e total por pessoa.",
     "3 · Como fomos: estação, horário e duração (a confirmar).",
     "4 · Foto: chegada em Bruges.",
     "5 · Foto + informação: rua de compras do centro (IMG_2693).",
     "6 · Foto + informação: waffle de rua (IMG_2690): veredito “vale.”",
     "7–8 · Fotos + informação: os pontos visitados (decupagem).",
     "9 · Dica (Bilhete): o que fariam diferente (a confirmar com o Diego).",
     "10 · Encerramento: Placa CTA `SALVA PRA VIAGEM →` + 1º."],
 tl="Slides acima. Etiqueta `ROTEIRO`.",
 na="Não se aplica (carrossel).",
 lg="Bate-volta de Bruxelas a Bruges: como fizemos. 🚆\n\n[transporte, horário e duração, a preencher]\n[quanto custou o trajeto por pessoa, a preencher]\n\nEm Bruges: [paradas, a preencher], waffle de rua (vale!) e muita caminhada pelo centro.\n\n[dica do que fariam diferente]\n\nCotação: € 1 = R$ [PTAX da data da viagem].\n\nSalva pra encaixar Bruges na sua viagem.",
 cta="Salva pra encaixar Bruges na sua viagem (salvamento).",
 cp="Capa em papel com a Rota (teste T4, variante B).",
 so="Música instrumental da biblioteca ao postar.",
 me="Salvamentos por alcance", hi="Capa de papel gera mais salvamentos que capa de foto (2º ponto B do teste T4).",
 te="T4:B",
 ma=["IMG_2690 a IMG_2693 (Bruges)", "Brutos de Bruges (decupagem pendente)", OUTRAS],
 pe=["Diego: transporte, horários e preço do trajeto Bruxelas–Bruges", "Diego: gastos do dia em Bruges", "Decupagem: paradas do dia, na ordem"],
 of="Bruges", otr="IMG_2690–2693 + decupagem"),

dict(
 d="2026-11-12", h="12:30", f="R", k="multi", pl="UTIL", nv="A", st="dad",
 t="Barcelona ou Madrid: qual escolher?",
 ob="Comentários e envios: a dúvida mais comum de quem vai à Espanha, respondida por quem fez as duas.",
 mo="Quem vai à Espanha pela primeira vez e só tem tempo para uma. Comenta o próprio voto; envia para quem está decidindo.",
 g="Barcelona ou Madrid? Fiz as duas.", gt="Comparação",
 q0="Tela dividida na vertical: Barcelona (Sagrada) à esquerda e Madrid (cena forte) à direita, uma placa pequena em cada metade.",
 sc=[("0–2 s","Gancho","Tela dividida + 2 placas pequenas `BARCELONA` / `MADRID`."),
     ("2–8 s","Critério 1","Dias que ficamos: 3 × 2. Cena de cada uma."),
     ("8–14 s","Critério 2","Para quem é cada uma (opinião do Diego, a confirmar): praia e Gaudí × [a confirmar]."),
     ("14–20 s","Critério 3","Comida: primeira tapa em Barcelona × [comida de Madrid]."),
     ("20–25 s","Veredito","Dois recibos lado a lado ou dois bilhetes: “se for só uma: [escolha do Diego]”, com ✓ de caneta."),
     ("25–27 s","Pergunta","Legenda: “e você, qual escolheria?”")],
 tl="barcelona ou madrid? fiz as duas · 3 dias × 2 dias · [para quem é cada uma] · se for só uma: [escolha]",
 na="Narração do Diego (até 15 s) com a opinião dele nos 3 critérios. Roteiro a fechar com ele.",
 lg="Barcelona ou Madrid? Fiz as duas. 🇪🇸\n\nBarcelona (3 dias): [resumo da opinião do Diego]\nMadrid (2 dias): [resumo da opinião do Diego]\n\nSe for para escolher uma só na primeira viagem: [escolha].\n\nE você, qual escolheria? Comenta aqui.",
 cta="Comenta qual você escolheria (comentário).",
 cp="Tela dividida com as duas placas. Texto da capa: “BCN OU MADRID?”",
 so="Narração + música da biblioteca baixa.",
 me="Comentários e envios por alcance", hi="Comparar duas cidades gera mais envios e comentários que um Reel de cidade única (teste T5, variante B).",
 te="T5:B",
 ma=[BCN_MASTER, "Brutos de Madrid (decupagem pendente)"],
 pe=["Opinião do Diego nos 3 critérios e a escolha final", "Cena forte de Madrid para a tela dividida"],
 of="Barcelona e Madrid", otr="Master BCN + decupagem MAD"),

dict(
 d="2026-11-14", h="11:00", f="R", k="dis", pl="DESEJO", nv="B", st="dec",
 t="Disneyland Paris: o castelo ao vivo",
 ob="Desejo: o momento mais “sonho de infância” da Disney, com gancho escrito (teste T2).",
 mo="Fãs da Disney, famílias e casais. Envia para quem sonha com a Disney; salva como meta.",
 g="Ao vivo, esse castelo é outro.", gt="“Eu não esperava isso”",
 q0="O castelo da Disneyland Paris no plano mais bonito da decupagem (de preferência com luz do fim de tarde). Placa Marca.",
 sc=[("0–2 s","Gancho","Castelo + Placa Marca + gancho escrito (variante A do teste T2)."),
     ("2–11 s","Desejo","4 a 5 planos do parque, cortes no tempo da música. Ticket SURPREENDE só se houver reação real filmada."),
     ("11–14 s","Fecho","Legenda Padrão: “disneyland paris.”"),
     ("14–15 s","Loop","Volta ao castelo.")],
 tl="ao vivo, esse castelo é outro · disneyland paris.",
 na="Sem narração (ou fala real de reação, se houver).",
 lg="Ao vivo, esse castelo é outro. 🏰\n\nDisneyland Paris, num dia em que a gente fez os dois parques.\n\nManda pra quem sonha com a Disney.",
 cta="Manda pra quem sonha com a Disney (envio).",
 cp="Castelo. Texto da capa: “AO VIVO É MAIS”.",
 so="Música instrumental da biblioteca (sem trilhas da Disney).",
 me="Retenção média e envios", hi="Gancho escrito retém mais que só imagem (3º ponto A do teste T2).",
 te="T2:A",
 ma=["Brutos da Disneyland Paris (decupagem pendente: castelo)"],
 pe=["Confirmar plano do castelo; se não houver bom plano, trocar por outro ícone do parque e ajustar o gancho", "Sem música da Disney"],
 of="Disneyland Paris", otr="Decupagem"),

dict(
 d="2026-11-15", h="19:00", f="R", k="bcn", pl="EXP", nv="B", st="ok",
 t="Primeira tapa depois de 18 km",
 ob="Identificação: o fim de um primeiro dia cansativo, com a recompensa (a primeira tapa). Fecha o arco do dia 1 de Barcelona.",
 mo="Quem viaja andando muito e quem ama comida. Comenta a própria “primeira comida” de viagem; envia para quem vai a Barcelona.",
 g="18 km depois, a primeira tapa.", gt="Resultado primeiro",
 q0="Close das patatas bravas com a cerveza na mesa (master ≈ 10:45). Placa `PRIMEIRO DIA EM / BARCELONA`.",
 sc=[("0–2 s","Gancho","Close da tapa + Placa de abertura (é o fim do dia 1). Legenda Padrão com Destaque em “18 km”."),
     ("2–8 s","Contexto","Master 10:12–10:40: “último bichão do dia, muito cansados, a gente andou demais, uns 18 quilômetros”."),
     ("8–14 s","Pico","Master 10:40–10:57: “acabei de pedir a minha primeira tapa de Barcelona, pedi uma papa brava com uma cerveza”. Bilhete: “valeu cada km.”"),
     ("14–17 s","Fechamento","Placa `E ISSO FOI SÓ O / PRIMEIRO DIA.` + 1º + bordão.")],
 tl="18 km depois, a primeira tapa · patatas bravas + cerveza · valeu cada km · e isso foi só o primeiro dia.",
 na="Sem narração nova.",
 lg="18 km depois, a primeira tapa. 🍻\n\nFim do primeiro dia em Barcelona: Camp Nou, Montjuïc, Barceloneta, Ciutadella e Arco do Triunfo, quase tudo a pé.\n\nA recompensa foi a primeira tapa da viagem: patatas bravas e uma cerveza.\n\nQual foi a sua primeira comida na última viagem? Conta aqui.",
 cta="Conta qual foi a sua primeira comida de viagem (comentário).",
 cp="Patatas bravas e cerveza. Texto da capa: “18 KM DEPOIS”.",
 so="Falas originais + ambiente do bar.",
 me="Comentários por alcance", hi="Fechamento emocional do dia (cansaço + recompensa) gera identificação e comentários.",
 te=None,
 ma=[BCN_MASTER+": 10:12–10:57 (fim do dia 1)", "IMG_0816.MP4 (bar à noite, brinde)", BCN_TRANS],
 pe=["Conferir se o IMG_0816 é a mesma noite da primeira tapa (o casamento de brutos aponta o brinde em 639,4 s do master)"],
 of="Barcelona, dia 1", otr="Master 10:12–10:57"),

# ───────────────────────── Semana 7 (16 a 22/11) ─────────────────────────
dict(
 d="2026-11-17", h="18:30", f="R", k="lis", pl="EXP", nv="B", st="dec",
 t="Vale ou pula: a primeira comida em Lisboa",
 ob="Identificação e utilidade: a comida que provamos na passagem curta por Lisboa, com veredito. Mantém a série Vale ou pula rodando por outras cidades.",
 mo="Brasileiros que vão a Portugal. Envia para quem vai a Lisboa; comenta o próprio veredito.",
 g="Vale ou pula: [comida] em Lisboa?", gt="Vale a pena?",
 q0="Close da comida (decupagem) com a Placa `VALE OU PULA` / `[COMIDA] · LISBOA`.",
 sc=[("0–2 s","Gancho","Close + Placa Série."),
     ("2–8 s","Contexto","Onde e quando (fala ou legenda Narrativa)."),
     ("8–15 s","Prova","Primeira mordida e reação real."),
     ("15–18 s","Veredito","Bilhete veredito `vale.` / `pula.` / `depende:` conforme a opinião real."),
     ("18–20 s","Loop","Volta ao close.")],
 tl="vale ou pula: [comida] em lisboa? · [onde] · € [valor] · [veredito]",
 na="Sem narração nova (fala da prova).",
 lg="Vale ou pula: [comida] em Lisboa?\n\n[onde compramos e quanto custou: € valor ≈ R$ valor]\n\nVeredito: [vale/pula/depende], porque [motivo real].\n\nCotação: € 1 = R$ [PTAX da data da viagem].\n\nE você, já provou? Vale ou pula?",
 cta="Responde vale ou pula nos comentários (comentário).",
 cp="Close da comida. Texto da capa: “VALE OU PULA?”",
 so="Som direto + música da biblioteca baixa.",
 me="Comentários e envios", hi="A série Vale ou pula funciona fora de Barcelona e cria hábito de resposta.",
 te=None,
 ma=["Brutos de Lisboa (decupagem pendente: comida provada)"],
 pe=["Identificar na decupagem qual comida foi filmada sendo provada (se nenhuma, trocar por “Vale ou pula: [lugar] em Lisboa?”)", "Preço e veredito do Diego"],
 of="Lisboa", otr="Decupagem"),

dict(
 d="2026-11-18", h="18:00", f="C", k="dis", pl="UTIL", nv="—", st="dad",
 t="2 parques da Disney em 1 dia: como dividimos o dia",
 ob="Salvamento: o plano real para fazer os dois parques num dia só, para quem tem pouco tempo em Paris.",
 mo="Famílias e casais que vão à Disneyland Paris com 1 dia. Salva o plano; envia para quem vai junto.",
 g="2 parques em 1 dia: nosso plano.", gt="Resultado primeiro",
 q0="Capa com foto (variante A do teste T4): castelo ou entrada com a Placa G `ROTEIRO` / `DISNEYLAND PARIS`.",
 sl=["1 · Capa (foto): castelo + Placa G `ROTEIRO` / `DISNEYLAND PARIS` + “2 parques em 1 dia”.",
     "2 · Rota do dia (segunda capa): horário de chegada → parque 1 → troca → parque 2 → saída (horários reais a confirmar).",
     "3 · Como chegamos de Paris (a confirmar).",
     "4–6 · Parque 1: o que fizemos, em ordem (fotos da decupagem).",
     "7–8 · Parque 2: o que fizemos, em ordem.",
     "9 · O que ficou de fora (honesto).",
     "10 · Dica (Bilhete): a principal lição do dia (a confirmar com o Diego).",
     "11 · Encerramento: Placa CTA `SALVA PRA VIAGEM →` + 1º."],
 tl="Slides acima. Etiqueta `ROTEIRO`.",
 na="Não se aplica (carrossel).",
 lg="2 parques da Disneyland Paris em 1 dia: como dividimos o dia. 🏰\n\n[horário de chegada e como fomos]\n[parque 1: o que fizemos]\n[troca de parque: horário]\n[parque 2: o que fizemos]\n[o que ficou de fora]\n\nDica: [lição principal].\n\nSalva pra sua viagem à Disneyland Paris.",
 cta="Salva pra sua viagem à Disney (salvamento).",
 cp="Castelo com a Placa G (teste T4, variante A).",
 so="Música instrumental da biblioteca ao postar (sem trilhas da Disney).",
 me="Salvamentos por alcance", hi="Capa de foto alcança mais não seguidores (teste T4, variante A).",
 te="T4:A",
 ma=["Brutos e fotos da Disneyland Paris (decupagem pendente)"],
 pe=["Diego: horários, ordem dos parques, transporte e lição principal", "Fotos ou quadros de cada parque"],
 of="Disneyland Paris", otr="Decupagem"),

dict(
 d="2026-11-19", h="12:30", f="R", k="ams", pl="UTIL", nv="A", st="dad",
 t="Amsterdam em 3 dias: € [total]",
 ob="Envio e salvamento: o custo real de 3 dias em Amsterdam, a cidade com fama de cara.",
 mo="Quem planeja Amsterdam e tem medo do preço. Salva para orçar; envia para quem vai junto.",
 g="Amsterdam em 3 dias: € [total].", gt="Preço",
 q0="Recibo em close com o total em PD Placar 128 px girando até o valor (sobre cena de Amsterdam).",
 sc=[("0–2 s","Gancho","Recibo com o total girando + cena de canal ao fundo."),
     ("2–6 s","Contexto","Legenda Narrativa: “3 dias, por pessoa, com hospedagem.”"),
     ("6–18 s","Entrega","Snap entre categorias, uma cena por categoria: hospedagem, transporte, comida, passeios. Etiqueta de valor em cada uma."),
     ("18–22 s","Pico","Bilhete: onde dava para economizar (opinião real)."),
     ("22–25 s","Fechamento","Placa CTA `SALVA PRA VIAGEM →`.")],
 tl="amsterdam em 3 dias: € [total] · por pessoa, com hospedagem · [categorias] · [dica]",
 na="Opcional: narração do Diego (até 10 s) explicando onde foi a maior parte do dinheiro.",
 lg="Amsterdam em 3 dias: € [total] por pessoa (≈ R$ [valor]).\n\nHospedagem: € [valor]\nTransporte: € [valor]\nComida: € [valor]\nPasseios: € [valor]\n\n[onde dava para economizar]\n\nCotação: € 1 = R$ [PTAX da data da viagem].\n\nSalva pra planejar Amsterdam.",
 cta="Salva pra planejar Amsterdam (salvamento).",
 cp="Recibo com o total. Texto da capa: “AMSTERDAM: € [TOTAL]”.",
 so="*tick* e impressora térmica quando existirem; música da biblioteca baixa.",
 me="Salvamentos e envios por alcance", hi="Preço total no gancho repete o sinal de envios do “Quanto custa Barcelona” (08/10).",
 te=None,
 ma=["Registro de custos de Amsterdam (Diego)", "Brutos de Amsterdam para as cenas de cada categoria"],
 pe=["Diego: custos de Amsterdam por categoria e por pessoa", "Sem os custos até 12/11, trocar por “Amsterdam: o que fizemos em 3 dias” (Rota) e mover o Reel de custo para quando chegarem"],
 of="Amsterdam", otr="Registro de custos + decupagem"),

dict(
 d="2026-11-21", h="11:00", f="R", k="ita", pl="DESEJO", nv="B", st="dec",
 t="Veneza: sem carro, sem moto, só barco",
 ob="Desejo puro com uma frase factual: a cidade que vira assunto por si só. Primeiro uso dos vídeos ambientais da Itália.",
 mo="Quem sonha com a Itália. Envia para quem iria junto; salva como destino.",
 g="Sem carro, sem moto, só barco.", gt="Afirmação",
 q0="Plano de canal de Veneza com barco passando (vídeo ambiental, se houver). Placa Marca.",
 sc=[("0–2 s","Gancho","Canal com barco + Placa Marca + gancho escrito."),
     ("2–12 s","Desejo","4 a 6 planos de 1,5 a 2 s (canais, pontes, ruelas). Sem informação de preço (variante A do teste T1). Se só houver fotos: zoom sutil 100→104% em cada uma."),
     ("12–14 s","Nome","Legenda Padrão: “veneza.”"),
     ("14–15 s","Loop","Volta ao quadro 0.")],
 tl="sem carro, sem moto, só barco · veneza.",
 na="Sem narração.",
 lg="Sem carro, sem moto, só barco. 🛶\n\nVeneza, na nossa viagem de fim de ano pela Itália.\n\nManda pra quem iria pra Veneza com você.",
 cta="Manda pra quem iria pra Veneza com você (envio).",
 cp="Canal de Veneza. Texto da capa: “SÓ BARCO”.",
 so="Música instrumental da biblioteca + ambiente da água.",
 me="Seguidores por 1.000 visualizações e % de não seguidores", hi="Desejo puro alcança, mas converte menos que desejo com informação (2º ponto A do teste T1).",
 te="T1:A",
 ma=["Vídeos ambientais da Itália (inventário pendente: há vídeos de Veneza?)", "Fotos de Veneza (inventário pendente)"],
 pe=["Inventariar os vídeos e fotos de Veneza (datas e locais)", "Confirmar as datas em Veneza (a viagem foi de 24/12/2024 a 04/01/2025)"],
 of="Itália: Veneza", otr="Inventário pendente"),

dict(
 d="2026-11-22", h="19:00", f="R", k="bcn", pl="UTIL", nv="A", st="ok",
 t="Vale ou pula: La Boqueria",
 ob="Utilidade: veredito honesto sobre o mercado mais famoso de Barcelona, que muita gente coloca no roteiro sem saber o que esperar.",
 mo="Quem vai a Barcelona. Salva para decidir; envia para quem quer “comer no mercado”.",
 g="Vale ou pula: La Boqueria?", gt="Vale a pena?",
 q0="Corredor da Boqueria cheio (master ≈ 19:27) com a Placa `VALE OU PULA` / `LA BOQUERIA`.",
 sc=[("0–2 s","Gancho","Corredor da Boqueria + Placa Série."),
     ("2–9 s","Contexto","Master 19:27–19:45: “mercado muito famoso, conhecido como pega-turista… os preços daqui são muito caros”."),
     ("9–15 s","Comparação","Master 19:45–19:57: “se vocês já foram no Mercadão de São Paulo, vão se sentir num ambiente familiar”. Legenda com Destaque em “Mercadão”."),
     ("15–19 s","Veredito","Bilhete veredito: `depende:` “vale a volta. comprar, nem tanto.”"),
     ("19–21 s","Fechamento","Placa CTA `SALVA PRA VIAGEM →`.")],
 tl="vale ou pula: la boqueria? · fama de pega-turista · é tipo o mercadão de sp · depende: vale a volta, comprar nem tanto",
 na="Sem narração nova.",
 lg="Vale ou pula: La Boqueria? 🍓\n\nO mercado mais famoso de Barcelona fica no meio de La Rambla e tem fama de pega-turista: os preços são altos.\n\nSe você já foi ao Mercadão de São Paulo, a vibe é parecida: várias barracas, muita gente, muita cor.\n\nVeredito: depende. Vale a volta para ver. Para comprar, nem tanto. A gente só deu uma olhada e seguiu.\n\nSalva pra decidir o seu roteiro.",
 cta="Salva pra decidir o seu roteiro (salvamento).",
 cp="Corredor da Boqueria. Texto da capa: “PEGA-TURISTA?”",
 so="Falas originais + ambiente do mercado.",
 me="Salvamentos por alcance", hi="Veredito honesto (“depende”) sobre um lugar famoso gera salvamentos e debate (cidade única, teste T5).",
 te="T5:A",
 ma=[BCN_MASTER+": 19:27–20:00 (dia 2)", BCN_TRANS],
 pe=["Checar trilha sob a fala", "Não citar preços de barracas (não foram registrados)"],
 of="Barcelona, dia 2", otr="Master 19:27–20:00"),

# ───────────────────────── Semana 8 (23 a 29/11, Black Friday 27/11) ─────────────────────────
dict(
 d="2026-11-24", h="18:30", f="R", k="multi", pl="UTIL", nv="A", st="ok",
 t="A passagem é só o começo (antes da Black Friday)",
 ob="Envio e salvamento na semana em que muita gente compra passagem: mostrar, com um recibo real, quanto custa a viagem depois do voo.",
 mo="Quem vai aproveitar a Black Friday para comprar passagem para a Europa. Envia para quem vai junto; salva para orçar.",
 g="A passagem é só o começo.", gt="Preço",
 q0="Recibo longo de Roma imprimindo (Recibo, impressão de cima para baixo) sobre foto do Coliseu.",
 sc=[("0–2 s","Gancho","Recibo de Roma imprimindo + legenda Padrão com o gancho."),
     ("2–8 s","Exemplo real","Roma, 3 dias, por pessoa: € 421,50 com hospedagem (≈ R$ 2.698). Sem hospedagem: € 199,90 (≈ R$ 1.279)."),
     ("8–15 s","Para onde vai","Snap entre categorias com Etiqueta de valor: hospedagem € 221,60 · comida € 130,30 · ingressos € 47,60 · transporte € 22,00."),
     ("15–20 s","Dica","Bilhete: “some isso antes de comprar o voo.”"),
     ("20–22 s","Fechamento","Placa CTA `MANDA PRA QUEM VAI →`.")],
 tl="a passagem é só o começo · roma, 3 dias, por pessoa: € 421,50 · hospedagem 221,60 · comida 130,30 · ingressos 47,60 · transporte 22,00",
 na="Opcional: narração do Diego (até 8 s): “Antes de comprar a passagem, faz essa conta.”",
 lg="A passagem é só o começo. ✈️\n\nExemplo real, Roma, 3 dias, por pessoa, em dezembro de 2024:\nHospedagem: € 221,60 (apartamento dividido por 5, 4 noites)\nComida: € 130,30\nIngressos: € 47,60\nTransporte: € 22,00\nTotal: € 421,50 (≈ R$ 2.698)\n\nSe for comprar passagem nesta Black Friday, some isso antes.\n\nCotação: € 1 = R$ 6,40 (PTAX de 24/12/2024).\n\nManda pra quem vai viajar com você.",
 cta="Manda pra quem vai viajar com você (envio).",
 cp="Recibo de Roma. Texto da capa: “E DEPOIS DO VOO?”",
 so="Impressora térmica + *tick* quando existirem; música da biblioteca baixa.",
 me="Envios por alcance", hi="Conteúdo de custo ligado a um momento do calendário (Black Friday) gera mais envios.",
 te=None,
 ma=["Registro de custos de Roma (planejamento/ESTUDO_CARROSSEL_ROMA.md, seção 4)", ROMA_FOTOS],
 pe=["Os valores são de dez/2024: dizer isso na tela e na legenda (já está)", "Se os custos de Barcelona chegarem antes, avaliar trocar o exemplo por Barcelona (mais buscada)"],
 of="Roma (custos)", otr="Recibo de Roma"),

dict(
 d="2026-11-25", h="18:00", f="C", k="ita", pl="UTIL", nv="—", st="dad",
 t="Florença em 2 dias: € [total]",
 ob="Salvamento: o custo real e o roteiro de Florença, no mesmo padrão do carrossel de Roma (que é a referência de formato).",
 mo="Quem planeja Itália com várias cidades. Salva para orçar; envia para quem vai junto.",
 g="Florença em 2 dias: € [total].", gt="Preço",
 q0="Capa em papel (variante B do teste T4): Recibo de Florença com o total em destaque.",
 sl=["1 · Capa (papel, variante B): Recibo de Florença com total por pessoa e “2 dias”.",
     "2 · Foto: a vista mais forte de Florença no acervo (segunda capa, com a placa M `FLORENÇA`).",
     "3 · Roteiro dia 1 (Rota): paradas reais.",
     "4–6 · Fotos + informação dos lugares do dia 1 (preço ou “grátis”).",
     "7 · Roteiro dia 2 (Rota).",
     "8–9 · Fotos + informação do dia 2.",
     "10 · Dica (Bilhete) real do Diego.",
     "11 · Encerramento: Placa CTA `SALVA PRA VIAGEM →` + 1º."],
 tl="Slides acima. Etiqueta `QUANTO CUSTOU`.",
 na="Não se aplica (carrossel).",
 lg="Florença em 2 dias: € [total] por pessoa (≈ R$ [valor]).\n\n[hospedagem, comida, ingressos e transporte, a preencher]\n\n[roteiro resumido dos 2 dias]\n\nCotação: € 1 = R$ [PTAX da data].\n\nSalva pra sua viagem pela Itália.",
 cta="Salva pra sua viagem pela Itália (salvamento).",
 cp="Recibo de Florença (teste T4, variante B).",
 so="Música instrumental da biblioteca ao postar.",
 me="Salvamentos por alcance", hi="Capa de papel com o total gera mais salvamentos (3º ponto B do teste T4).",
 te="T4:B",
 ma=["Fotos de Florença (inventário pendente)", "Registro de custos de Florença (Diego)"],
 pe=["Diego: custos de Florença por categoria e por pessoa (pendência desde 05/10)", "Lista de lugares visitados e fotos", "Datas em Florença para a cotação"],
 of="Itália: Florença", otr="Inventário pendente"),

dict(
 d="2026-11-26", h="12:30", f="R", k="par", pl="SERIE", nv="B", st="ok",
 t="Primeiro dia em Paris (e era o único)",
 ob="Série e conversão: o dia único em Paris contado do começo ao fim, com o perrengue e a virada da noite.",
 mo="Quem vai a Paris com pouco tempo. Segue porque entende a série; envia para quem vai a Paris.",
 g="Um dia só em Paris. Deu?", gt="Pergunta",
 q0="IMG_2730 em 0 s: os dois chegando, Diego falando para a câmera. Placa `PRIMEIRO DIA EM / PARIS`.",
 sc=[("0–2,5 s","Gancho","IMG_2730 (0,5–3,0 s) + Placa de abertura. Legenda Padrão com o gancho."),
     ("2,5–9 s","Contexto","IMG_2730 (9,7–20,6 s): “nós só vamos passar um dia em Paris e a cidade é muito grande… tentar conhecer o máximo de pontos turísticos”."),
     ("9–13 s","Desenvolvimento","IMG_2761 (1,0–4,5 s): selfie com a Torre Eiffel de dia + planos do dia (decupagem)."),
     ("13–18 s","Perrengue","IMG_3134 (14,0–19,0 s): o Jardim de Luxemburgo fechado. Bilhete: “o jardim ficou pra próxima.”"),
     ("18–22 s","Virada","IMG_3134 (51,0–58,0 s): “foi bom demais, o dia foi lindo… e amanhã tem Disney”."),
     ("22–25 s","Fechamento","Placa `E ISSO FOI SÓ O / PRIMEIRO DIA.` + 1º + bordão. Legenda: “segue pra ver a disney.”")],
 tl="um dia só em paris. deu? · a cidade é muito grande · o jardim ficou pra próxima · amanhã tem disney",
 na="Sem narração nova.",
 lg="Um dia só em Paris. Deu? 🗼\n\nChegamos sabendo que era um dia só, porque o seguinte era da Disney. O plano: ver o máximo possível e comer bem.\n\nDeu para a Torre Eiffel e [paradas do dia]. Não deu para o Jardim de Luxemburgo, que fechou antes de a gente chegar.\n\nResposta: dá para o essencial, não para tudo.\n\nSou o Diego e aqui eu mostro o primeiro dia em cada cidade. Segue pra ver o dia da Disney.",
 cta="Segue pra ver o dia da Disney (seguir).",
 cp="Os dois com a Torre ao fundo (IMG_2761). Texto da capa: “1 DIA EM PARIS”.",
 so="Falas originais + música da biblioteca baixa.",
 me="Seguidores por 1.000 visualizações", hi="CTA de seguir com “próximo episódio” explícito (a Disney) converte mais (teste T3, variante A).",
 te="T3:A",
 ma=["IMG_2730.MOV, IMG_2761.MOV, IMG_3134.MOV", "Brutos de Paris (decupagem para as paradas do meio do dia)", OUTRAS],
 pe=["Selfie horizontal com os dois: na apresentação, o recorte 9:16 não coube os dois em parte dos quadros. Recorte acompanhando quem fala (keyframes de posição), conferido quadro a quadro, sem cortar a Marina no meio do rosto (IMG_2730 e IMG_3134)", "Paradas do dia para a legenda (decupagem)", "Não repetir no Reel os mesmos 6 s do Reel de 15/10 (usar outro trecho do IMG_3134)"],
 of="Paris, dia 1", otr="IMG_2730, IMG_2761, IMG_3134"),

dict(
 d="2026-11-28", h="11:00", f="R", k="mad", pl="DESEJO", nv="B", st="dec",
 t="Madrid em planos (sem informação)",
 ob="Desejo puro: Madrid pela beleza, não pelo preço. Terceiro ponto A do teste T1.",
 mo="Quem sonha com a Espanha. Envia para quem iria junto.",
 g="Madrid merece mais que 2 dias.", gt="Afirmação",
 q0="O plano mais forte de Madrid na decupagem (praça, palácio ou avenida). Placa Marca.",
 sc=[("0–2 s","Gancho","Melhor plano + Placa Marca + gancho escrito."),
     ("2–12 s","Desejo","5 a 6 planos de 1,5 a 2 s, sem preço (variante A do teste T1)."),
     ("12–14 s","Fecho","Legenda Padrão: “madrid.”"),
     ("14–15 s","Loop","Volta ao quadro 0.")],
 tl="madrid merece mais que 2 dias · madrid.",
 na="Sem narração.",
 lg="Madrid merece mais que 2 dias. 🇪🇸\n\nFicamos só 2 dias e saímos com vontade de voltar.\n\nManda pra quem iria pra Madrid com você.",
 cta="Manda pra quem iria pra Madrid com você (envio).",
 cp="Melhor plano de Madrid. Texto da capa: “MADRID”.",
 so="Música instrumental da biblioteca + ambiente.",
 me="Seguidores por 1.000 visualizações e envios", hi="Desejo puro (3º ponto A do teste T1).",
 te="T1:A",
 ma=["Brutos de Madrid (decupagem pendente)"],
 pe=["Decupagem de Madrid", "Confirmar com o Diego a frase do gancho (é opinião dele: “merece mais que 2 dias”)"],
 of="Madrid", otr="Decupagem"),

dict(
 d="2026-11-29", h="19:00", f="R", k="bxl", pl="UTIL", nv="B", st="dec",
 t="Bruxelas em 1 dia: vale parar?",
 ob="Utilidade: veredito sobre parar 1 dia em Bruxelas, dúvida comum de quem faz roteiro por várias cidades.",
 mo="Quem monta roteiro Paris–Amsterdam ou Bélgica. Salva para decidir; envia para quem monta o roteiro.",
 g="Vale parar 1 dia em Bruxelas?", gt="Vale a pena?",
 q0="Melhor plano do centro de Bruxelas (decupagem) com a Placa `VALE OU PULA` / `1 DIA · BRUXELAS`.",
 sc=[("0–2 s","Gancho","Plano do centro + Placa Série."),
     ("2–6 s","Contexto","IMG_2170 (0,2–5,0 s): “primeira parada, Atomium… viemos de metrô” (contexto do dia)."),
     ("6–16 s","Entrega","Cortes com as paradas reais do dia (decupagem), 1,5 a 3 s cada."),
     ("16–20 s","Veredito","Bilhete veredito `vale.` / `depende:` com a opinião real."),
     ("20–22 s","Fechamento","Placa CTA `SALVA PRA VIAGEM →`.")],
 tl="vale parar 1 dia em bruxelas? · [paradas] · [veredito]",
 na="Opcional: narração curta do Diego com o veredito (até 6 s).",
 lg="Vale parar 1 dia em Bruxelas? 🇧🇪\n\nNosso dia: [paradas reais, a preencher]. Começamos pelo Atomium, de metrô.\n\nVeredito: [vale/depende], porque [motivo real].\n\nSalva pra decidir o seu roteiro.",
 cta="Salva pra decidir o seu roteiro (salvamento).",
 cp="Centro de Bruxelas com a placa. Texto da capa: “1 DIA VALE?”",
 so="Falas + música da biblioteca baixa.",
 me="Salvamentos por alcance", hi="“Vale parar?” responde uma dúvida de roteiro e gera salvamentos.",
 te=None,
 ma=["IMG_2170.MP4", "Brutos de Bruxelas (decupagem pendente)", OUTRAS],
 pe=["Decupagem de Bruxelas: paradas do dia", "Veredito do Diego"],
 of="Bruxelas", otr="IMG_2170 + decupagem"),
]
