# -*- coding: utf-8 -*-
"""Peças do calendário v3 (parte 3: 01/12/2026 a 03/01/2027). Chaves: ver v3_pecas_1.py."""
from v3_pecas_1 import BCN_MASTER, BCN_TRANS, OUTRAS, ROMA_FOTOS

PECAS = [
# ───────────────────────── Semana 9 (30/11 a 06/12) ─────────────────────────
dict(
 d="2026-12-01", h="18:30", f="R", k="ita", pl="UTIL", nv="A", st="ok",
 t="Comida em Roma: a regra que segurou o orçamento",
 ob="Salvamento e envio: uma regra simples e real de economia (comida de rua de dia, jantar sentado à noite, mercado de manhã) com o valor total gasto.",
 mo="Quem vai à Itália e quer comer bem sem estourar o orçamento. Salva a regra; envia para quem divide as refeições.",
 g="€ 130 de comida em 3 dias.", gt="Preço",
 q0="Recibo curto com `COMIDA · 3 DIAS · € 130,30` imprimindo sobre foto de rua de Roma.",
 sc=[("0–2 s","Gancho","Recibo curto imprimindo + legenda Padrão com Destaque em “130”."),
     ("2–7 s","Regra 1","Foto de comida de rua de Roma (acervo). Legenda: “de dia: comida de rua.”"),
     ("7–12 s","Regra 2","Foto de jantar (acervo). Legenda: “à noite: sentar e jantar com calma.”"),
     ("12–16 s","Regra 3","Foto de mercado (acervo). Legenda: “de manhã: mercado para água, lanche e o vinho do fim de tarde.”"),
     ("16–20 s","Pico","Bilhete: “comida foi 31% da viagem.”"),
     ("20–22 s","Fechamento","Placa CTA `SALVA PRA VIAGEM →`.")],
 tl="€ 130 de comida em 3 dias · de dia: comida de rua · à noite: jantar sentado · de manhã: mercado · 31% da viagem",
 na="Opcional: narração do Diego (até 10 s) contando a regra com as palavras dele.",
 lg="€ 130 de comida em 3 dias em Roma. 🍝\n\nFoi o que cada um de nós gastou com comida e bebida: € 130,30 (≈ R$ 834). A regra que a gente criou:\n\nDe dia: comida de rua, que também é o melhor da culinária italiana.\nÀ noite: sentar e jantar com calma, gastando mais nos pratos.\nDe manhã: mercado para levar água, lanche e até o vinho do fim de tarde na bolsa.\n\nCafés € 13,10 · mercado € 27,30 · almoços € 33,70 · sorvetes € 13,20 · jantares € 43,00.\n\nCotação: € 1 = R$ 6,40 (PTAX de 24/12/2024).\n\nSalva pra sua viagem à Itália.",
 cta="Salva pra sua viagem à Itália (salvamento).",
 cp="Recibo de comida sobre rua de Roma. Texto da capa: “€ 130 DE COMIDA”.",
 so="Impressora térmica e *tick* quando existirem; música da biblioteca.",
 me="Salvamentos por alcance", hi="Uma regra simples e copiável, com valor real, é mais salva que uma lista de restaurantes.",
 te=None,
 ma=["Registro de custos de Roma (planejamento/ESTUDO_CARROSSEL_ROMA.md, seção 4)", ROMA_FOTOS, "Fotos de comida de rua, jantar e mercado em Roma (localizar no acervo)"],
 pe=["Localizar fotos de comida de rua, jantar e mercado em Roma (se faltar alguma, usar foto do lugar com a legenda da regra)", "R$ 834 = 130,30 × 6,40"],
 of="Roma (custos e fotos)", otr="Comida e bebida, dez/2024"),

dict(
 d="2026-12-02", h="18:00", f="C", k="lis", pl="UTIL", nv="—", st="dec",
 t="Lisboa em 1 noite e 1 manhã: o que coube",
 ob="Salvamento: roteiro curto e real para quem tem pouco tempo em Lisboa (escala ou chegada).",
 mo="Brasileiros com escala ou poucas horas em Lisboa. Salva para a escala; envia para quem vai passar por Lisboa.",
 g="1 noite e 1 manhã em Lisboa.", gt="Resultado primeiro",
 q0="Capa com foto (variante A do teste T4): Lisboa à noite com Placa G `ROTEIRO` / `LISBOA`.",
 sl=["1 · Capa (foto): Lisboa à noite + Placa G `ROTEIRO` / `LISBOA` + “1 noite e 1 manhã”.",
     "2 · Rota (segunda capa): as paradas reais da noite e da manhã, na ordem.",
     "3–5 · Noite: fotos + informação de cada parada.",
     "6–8 · Manhã: fotos + informação de cada parada.",
     "9 · Dica (Bilhete) real do Diego para quem tem pouco tempo.",
     "10 · Encerramento: Placa CTA `SALVA PRA VIAGEM →` + 1º."],
 tl="Slides acima. Etiqueta `ROTEIRO`.",
 na="Não se aplica (carrossel).",
 lg="Lisboa em 1 noite e 1 manhã: o que coube. 🇵🇹\n\nNoite: [paradas reais]\nManhã: [paradas reais]\n\n[valores, se houver registro]\n\nDica para quem tem pouco tempo: [dica do Diego].\n\nSalva pra sua escala em Lisboa.",
 cta="Salva pra sua escala em Lisboa (salvamento).",
 cp="Lisboa à noite com a Placa G (teste T4, variante A).",
 so="Música instrumental da biblioteca ao postar.",
 me="Salvamentos por alcance", hi="Roteiro curto para escala é muito salvo por brasileiros (Lisboa é porta de entrada da Europa).",
 te="T4:A",
 ma=["Brutos e fotos de Lisboa (decupagem pendente)"],
 pe=["Decupagem de Lisboa: paradas da noite e da manhã, na ordem", "Valores gastos (se houver)", "Confirmar se Lisboa foi escala ou destino da viagem (muda a legenda)"],
 of="Lisboa", otr="Decupagem"),

dict(
 d="2026-12-03", h="12:30", f="R", k="bcn", pl="DESEJO", nv="B", st="dec",
 t="Park Güell (sem texto)",
 ob="Desejo puro sem texto de gancho, 3º ponto B do teste T2. O Park Güell é um dos cartões-postais mais buscados de Barcelona.",
 mo="Quem sonha com Barcelona. Envia para quem iria junto; salva como destino.",
 g="(sem texto nos 2 primeiros segundos)", gt="Visual (sem texto)",
 q0="Plano dos mosaicos ou da vista do Park Güell (bruto), em movimento. Só a Placa Marca.",
 sc=[("0–2 s","Gancho visual","Mosaicos ou vista + Placa Marca. Sem texto de gancho."),
     ("2–11 s","Desejo","Bancos de pedra, sala hipóstila (colunas), vista da cidade: 1,5 a 2 s cada."),
     ("11–14 s","Curiosidade","Legenda Narrativa: “as colunas levam a água da chuva para uma cisterna e regam o parque.”"),
     ("14–15 s","Loop","Volta ao quadro 0.")],
 tl="(nada até 11 s) · as colunas levam a água da chuva para uma cisterna e regam o parque.",
 na="Sem narração.",
 lg="Park Güell, Barcelona. 🦎\n\nAs colunas da sala hipóstila foram pensadas por Gaudí para levar a água da chuva da praça de cima até uma cisterna, que ajuda a regar o parque.\n\nFoi o nosso último ponto em Barcelona, com hora marcada.\n\nManda pra quem tem Barcelona na lista.",
 cta="Manda pra quem tem Barcelona na lista (envio).",
 cp="Mosaico do Park Güell. Texto da capa: “PARK GÜELL”.",
 so="Música instrumental da biblioteca + ambiente.",
 me="Retenção média e % de não seguidores", hi="Sem texto (3º ponto B do teste T2).",
 te="T2:B",
 ma=[BCN_MASTER+": 29:39–31:55 (dia 3)", "Brutos do Park Güell (localizar originais sem trilha)", BCN_TRANS],
 pe=["Localizar brutos do Park Güell", "Conferir a explicação da água da chuva (fala em 31:13–31:55) em fonte oficial do parque"],
 of="Barcelona, dia 3", otr="Master 29:39–31:55"),

dict(
 d="2026-12-05", h="11:00", f="R", k="dis", pl="EXP", nv="A", st="dad",
 t="Vale ou pula: Disneyland Paris em 1 dia?",
 ob="Utilidade e identificação: o veredito honesto sobre fazer a Disney de Paris em um dia (com os dois parques).",
 mo="Quem está decidindo se inclui a Disney na viagem a Paris. Salva para decidir; envia para quem vai junto.",
 g="Vale ou pula: Disney em 1 dia?", gt="Vale a pena?",
 q0="Plano da entrada ou do castelo com a Placa `VALE OU PULA` / `DISNEY · 1 DIA`.",
 sc=[("0–2 s","Gancho","Entrada + Placa Série."),
     ("2–8 s","Contexto","O dia em números: horário de chegada, 2 parques, horário de saída (dados do Diego)."),
     ("8–16 s","Prós e contras","Cortes com o que valeu (Ticket, se for o caso) e o que cansou (fala real)."),
     ("16–20 s","Veredito","Bilhete veredito (`vale.` / `depende:` / `pula.`) com a opinião real do Diego."),
     ("20–22 s","Fechamento","Placa CTA `SALVA PRA VIAGEM →`.")],
 tl="vale ou pula: disney em 1 dia? · [números do dia] · [veredito]",
 na="Narração curta do Diego com o veredito (até 8 s), se a fala não estiver nos brutos.",
 lg="Vale ou pula: Disneyland Paris em 1 dia? 🏰\n\nFizemos os dois parques num dia só: [horário de chegada] até [horário de saída].\n\nO que valeu: [a preencher]\nO que pesou: [a preencher]\n\nVeredito: [vale/depende/pula], [motivo real].\n\nSalva pra decidir a sua viagem.",
 cta="Salva pra decidir a sua viagem (salvamento).",
 cp="Castelo com a placa. Texto da capa: “DISNEY EM 1 DIA?”",
 so="Falas + música da biblioteca (sem trilhas da Disney).",
 me="Salvamentos por alcance", hi="Veredito sobre uma decisão cara (incluir a Disney) é salvo por quem planeja.",
 te=None,
 ma=["Brutos da Disneyland Paris (decupagem pendente)"],
 pe=["Diego: horários do dia e veredito", "Não repetir planos do Reel de 31/10 e do carrossel de 18/11"],
 of="Disneyland Paris", otr="Decupagem"),

dict(
 d="2026-12-06", h="19:00", f="R", k="multi", pl="DESEJO", nv="B", st="dec",
 t="Canais: Amsterdam ou Bruges?",
 ob="Comentários e alcance: comparação visual entre duas cidades de canais, com voto do público.",
 mo="Quem sonha com a Europa do norte. Comenta o voto; envia para quem vai decidir junto.",
 g="Amsterdam ou Bruges? Escolhe uma.", gt="Comparação",
 q0="Tela dividida: canal de Amsterdam à esquerda, rua ou canal de Bruges à direita, uma placa pequena em cada metade.",
 sc=[("0–2 s","Gancho","Tela dividida + 2 placas pequenas."),
     ("2–8 s","Amsterdam","3 planos de Amsterdam (tela cheia)."),
     ("8–14 s","Bruges","3 planos de Bruges (tela cheia)."),
     ("14–17 s","Pergunta","Volta à tela dividida. Legenda: “qual você escolheria?”")],
 tl="amsterdam ou bruges? escolhe uma. · qual você escolheria?",
 na="Sem narração.",
 lg="Amsterdam ou Bruges? Escolhe uma. 🛶\n\nAmsterdam: 3 dias, cidade grande, canais por todo lado.\nBruges: bate-volta de 1 dia, centro pequeno que parece cenário.\n\nA gente foi às duas. E você, escolheria qual? Comenta aqui.",
 cta="Comenta a sua escolha (comentário).",
 cp="Tela dividida com as duas placas. Texto da capa: “QUAL VOCÊ ESCOLHE?”",
 so="Música instrumental da biblioteca.",
 me="Comentários por alcance", hi="Comparação visual com voto gera mais comentários que Reel de cidade única.",
 te=None,
 ma=["Brutos de Amsterdam e de Bruges (decupagem pendente)", "IMG_1384 (Amsterdam), IMG_2693 (Bruges)", OUTRAS],
 pe=["Não repetir planos já usados nos Reels de 25/10 e 27/10 (usar outros da decupagem)"],
 of="Amsterdam e Bruges", otr="Decupagem"),

# ───────────────────────── Semana 10 (07 a 13/12) ─────────────────────────
dict(
 d="2026-12-08", h="18:30", f="R", k="ita", pl="DESEJO", nv="B", st="ok",
 t="Roma iluminada no Natal",
 ob="Desejo sazonal com 1 informação útil: Roma no Natal, publicado no começo de dezembro, quando muita gente sonha com o fim de ano na Europa.",
 mo="Quem sonha com Natal na Europa; casais e famílias. Envia para quem passaria o Natal junto; salva para o próximo fim de ano.",
 g="Natal em Roma é assim.", gt="Resultado primeiro",
 q0="Foto da vila de Natal da Villa Borghese (vista ampla, com a Torre Eiffel de luzes) com zoom sutil. Placa Marca.",
 sc=[("0–2 s","Gancho","Vila de Natal (vista ampla) + Placa Marca + gancho escrito."),
     ("2–6 s","Desejo","Árvore-carrossel iluminada (foto não usada no carrossel) com zoom sutil."),
     ("6–10 s","Informação","Etiqueta de valor `VILA DE NATAL · € 17,60` (variante B do teste T1)."),
     ("10–13 s","Desejo","Coliseu à noite (IMG_6652, foto não usada no carrossel)."),
     ("13–15 s","Loop","Volta à vila de Natal.")],
 tl="natal em roma é assim · vila de natal da villa borghese: € 17,60 · roma, dezembro de 2024",
 na="Sem narração.",
 lg="Natal em Roma é assim. 🎄\n\nPassamos o Natal de 2024 em Roma. Na Villa Borghese, a vila de Natal tinha luzes, árvore-carrossel e até uma Torre Eiffel iluminada. Entrada: € 17,60 por pessoa (≈ R$ 113).\n\nÀ noite, o Coliseu iluminado completou o passeio.\n\nCotação: € 1 = R$ 6,40 (PTAX de 24/12/2024).\n\nManda pra quem passaria o Natal em Roma com você.",
 cta="Manda pra quem passaria o Natal em Roma com você (envio).",
 cp="Vila de Natal iluminada. Texto da capa: “NATAL EM ROMA”.",
 so="Música instrumental da biblioteca, clima de fim de ano (sem músicas natalinas com direitos de terceiros fora da biblioteca).",
 me="Envios por alcance e seguidores por 1.000 visualizações", hi="Desejo sazonal com 1 preço converte mais que desejo puro (3º ponto B do teste T1).",
 te="T1:B",
 ma=["Vila de Natal, vista ampla (usada no slide 08 do carrossel REV1)", "Árvore-carrossel da vila de Natal (não usada no carrossel)", "IMG_6652 (Coliseu à noite, não usado no carrossel)", ROMA_FOTOS],
 pe=["Conferir se a vila de Natal da Villa Borghese acontece em 2026 antes de sugerir na legenda (a legenda fala de 2024, então está correta)", "€ 17,60 × 6,40 = R$ 112,64 (≈ R$ 113)"],
 of="Fotos da Itália", otr="Roma, 25 e 26/12/2024"),

dict(
 d="2026-12-09", h="18:00", f="C", k="ita", pl="UTIL", nv="—", st="dad",
 t="Veneza em 2 dias: € [total]",
 ob="Salvamento: custo real e roteiro de Veneza, a cidade com fama de mais cara da Itália.",
 mo="Quem planeja Itália em várias cidades. Salva para orçar; envia para quem vai junto.",
 g="Veneza em 2 dias: € [total].", gt="Preço",
 q0="Capa com foto (variante A do teste T4): canal de Veneza com a Placa G `QUANTO CUSTOU` / `VENEZA`.",
 sl=["1 · Capa (foto): canal de Veneza + Placa G Série `QUANTO CUSTOU` / `VENEZA` + total.",
     "2 · Recibo (segunda capa): hospedagem, transporte (vaporetto?), comida, passeios e total por pessoa.",
     "3 · Rota do dia 1.",
     "4–6 · Fotos + informação do dia 1.",
     "7 · Rota do dia 2.",
     "8–9 · Fotos + informação do dia 2.",
     "10 · Dica (Bilhete) real do Diego.",
     "11 · Encerramento: Placa CTA `SALVA PRA VIAGEM →` + 1º."],
 tl="Slides acima. Etiqueta `QUANTO CUSTOU`.",
 na="Não se aplica (carrossel).",
 lg="Veneza em 2 dias: € [total] por pessoa (≈ R$ [valor]).\n\n[categorias, a preencher]\n[roteiro resumido]\n\nCotação: € 1 = R$ [PTAX da data].\n\nSalva pra sua viagem pela Itália.",
 cta="Salva pra sua viagem pela Itália (salvamento).",
 cp="Canal de Veneza com a Placa G (teste T4, variante A).",
 so="Música instrumental da biblioteca ao postar.",
 me="Salvamentos por alcance", hi="Capa de foto alcança mais não seguidores (teste T4, variante A).",
 te="T4:A",
 ma=["Fotos de Veneza (inventário pendente)", "Registro de custos de Veneza (Diego)"],
 pe=["Diego: custos de Veneza por categoria e por pessoa", "Lista de lugares e fotos", "Datas em Veneza"],
 of="Itália: Veneza", otr="Inventário pendente"),

dict(
 d="2026-12-10", h="12:30", f="R", k="mad", pl="UTIL", nv="A", st="dec",
 t="Madrid em 2 dias: o que deu pra fazer",
 ob="Salvamento: o roteiro real de 2 dias em Madrid, com as paradas e o que valeu.",
 mo="Quem vai a Madrid com pouco tempo. Salva o roteiro; envia para quem vai junto.",
 g="2 dias em Madrid: o que deu.", gt="Resultado primeiro",
 q0="Rota amarela se desenhando sobre a primeira cena de Madrid, com a Placa `ROTEIRO` / `2 DIAS · MADRID`.",
 sc=[("0–2 s","Gancho","Primeira cena + Placa Série `ROTEIRO`."),
     ("2–12 s","Dia 1","Paradas do dia 1 com transição Rota (máx. 2) e cortes secos."),
     ("12–20 s","Dia 2","Paradas do dia 2."),
     ("20–24 s","Pico","Bilhete: a parada que mais valeu (opinião real)."),
     ("24–26 s","Fechamento","Placa CTA `SALVA PRA VIAGEM →`.")],
 tl="2 dias em madrid: o que deu · dia 1: [paradas] · dia 2: [paradas] · [a que mais valeu]",
 na="Opcional: narração do Diego (até 10 s).",
 lg="2 dias em Madrid: o que deu pra fazer. 🇪🇸\n\nDia 1: [paradas reais]\nDia 2: [paradas reais]\n\nA que mais valeu: [opinião do Diego].\n\nSalva pra sua viagem a Madrid.",
 cta="Salva pra sua viagem a Madrid (salvamento).",
 cp="Cena forte de Madrid com a placa. Texto da capa: “2 DIAS EM MADRID”.",
 so="Música da biblioteca + falas, se houver.",
 me="Salvamentos por alcance", hi="Roteiro de cidade única (teste T5, variante A).",
 te="T5:A",
 ma=["Brutos de Madrid (decupagem pendente)", "Vlog de Madrid (YouTube, 05/12)"],
 pe=["Decupagem de Madrid, dias 1 e 2", "Opinião do Diego sobre a parada que mais valeu"],
 of="Madrid", otr="Decupagem"),

dict(
 d="2026-12-12", h="11:00", f="R", k="bcn", pl="EXP", nv="B", st="ok",
 t="McDonald's da Espanha × do Brasil",
 ob="Identificação e comentários: a tradição de provar o McDonald's de cada país, com comparação honesta com o Brasil.",
 mo="Qualquer brasileiro que viaja (é uma comparação que todo mundo tem opinião). Comenta o próprio veredito; envia para quem tem a mesma mania.",
 g="McDonald's da Espanha × do Brasil.", gt="Comparação",
 q0="Close do Mc Crispy Korean BBQ na bandeja (master ≈ 05:18–05:40), com duas placas pequenas `ESPANHA` × `BRASIL`.",
 sc=[("0–2 s","Gancho","Close do sanduíche + 2 placas pequenas."),
     ("2–8 s","Tradição","Master 05:18–05:35: a mania de comer o McDonald's de cada lugar que visita."),
     ("8–14 s","Prova","Master 05:35–06:20: o Mc Crispy Korean BBQ e a batata “bem diferente da do Brasil”."),
     ("14–19 s","Veredito","Master 06:30–06:50: “Melhor do Brasil?” “Ainda o do Brasil ganha.” Bilhete: “brasil 1 × 0 espanha.”"),
     ("19–21 s","Pergunta","Legenda: “e você, prova o mc de cada país?”")],
 tl="mcdonald's da espanha × do brasil · a mania de provar em cada país · batata diferente · brasil 1 × 0 espanha",
 na="Sem narração nova.",
 lg="McDonald's da Espanha × do Brasil. 🍔\n\nTem gente que coleciona ímã. A gente prova o McDonald's de cada país.\n\nEm Barcelona: Mc Crispy Korean BBQ e uma batata bem diferente da nossa. [Valores a confirmar: € 9,70 e € 13,60, se foram em euro.]\n\nVeredito: gostoso, mas o do Brasil ainda ganha.\n\nE você, prova o McDonald's de cada país? Comenta aqui.",
 cta="Comenta se também tem essa mania (comentário).",
 cp="Sanduíche na bandeja com as duas placas. Texto da capa: “ESPANHA × BRASIL”.",
 so="Falas originais + ambiente.",
 me="Comentários e envios por alcance", hi="Comparação com o Brasil (referência que todo brasileiro tem) gera comentários e alcance.",
 te=None,
 ma=[BCN_MASTER+": 05:18–06:50 (dia 1)", BCN_TRANS],
 pe=["Confirmar se os valores ditos (9,70 e 13,60) foram em euro (a transcrição registrou “R$”) e se cada um foi por pessoa", "Checar trilha sob a fala"],
 of="Barcelona, dia 1", otr="Master 05:18–06:50"),

dict(
 d="2026-12-13", h="19:00", f="R", k="par", pl="DESEJO", nv="B", st="dec",
 t="Paris de dia, sem informação",
 ob="Desejo puro: Paris pela atmosfera (4º ponto A do teste T1).",
 mo="Quem sonha com Paris. Envia para quem iria junto.",
 g="Paris num dia de céu azul.", gt="Afirmação",
 q0="Selfie dos dois com a Torre Eiffel e o céu azul (IMG_2761, 1–3 s), Placa Marca.",
 sc=[("0–2 s","Gancho","IMG_2761 (1–3 s) + Placa Marca + gancho escrito."),
     ("2–12 s","Desejo","5 a 6 planos de Paris de dia (decupagem), sem preço."),
     ("12–14 s","Fecho","Legenda Padrão: “paris.”"),
     ("14–15 s","Loop","Volta ao quadro 0.")],
 tl="paris num dia de céu azul · paris.",
 na="Sem narração.",
 lg="Paris num dia de céu azul. 🗼\n\nO nosso único dia em Paris começou assim.\n\nManda pra quem iria pra Paris com você.",
 cta="Manda pra quem iria pra Paris com você (envio).",
 cp="Os dois com a Torre ao fundo. Texto da capa: “PARIS”.",
 so="Música instrumental da biblioteca.",
 me="Seguidores por 1.000 visualizações e envios", hi="Desejo puro (4º ponto A do teste T1).",
 te="T1:A",
 ma=["IMG_2761.MOV", "Brutos de Paris (decupagem pendente)", OUTRAS],
 pe=["Decupagem de Paris de dia", "Não repetir os planos dos Reels de 07/11 e 26/11"],
 of="Paris", otr="IMG_2761 + decupagem"),

# ───────────────────────── Semana 11 (14 a 20/12) ─────────────────────────
dict(
 d="2026-12-15", h="18:30", f="R", k="multi", pl="SERIE", nv="A", st="dad",
 t="Qual primeiro dia foi o melhor?",
 ob="Conversão e comentários: ranking pessoal dos 8 primeiros dias, que só quem viveu pode fazer. Reforça a série e gera discussão.",
 mo="Quem acompanha o perfil e quem conhece alguma das cidades. Comenta discordando; envia para quem foi a uma delas.",
 g="Ranking: o melhor primeiro dia.", gt="Lista",
 q0="Quadro (ranking) grafite com as 8 linhas acendendo de baixo para cima sobre cena da cidade nº 8.",
 sc=[("0–2 s","Gancho","Quadro com o título + cena da cidade em 8º."),
     ("2–18 s","Ranking","Do 8º ao 2º: 2 s por cidade, cena do primeiro dia + linha do Quadro acendendo."),
     ("18–22 s","Pico","1º lugar com cena forte e Bilhete: o motivo em 1 linha."),
     ("22–25 s","Fechamento","Legenda: “concorda? segue pra ver o primeiro dia da próxima.”")],
 tl="ranking: o melhor primeiro dia · 8º [cidade] … 1º [cidade] · [motivo]",
 na="Narração curta do Diego no 1º lugar (até 5 s).",
 lg="Ranking: o melhor primeiro dia da nossa viagem. 🏆\n\n8. [cidade]\n7. [cidade]\n6. [cidade]\n5. [cidade]\n4. [cidade]\n3. [cidade]\n2. [cidade]\n1. [cidade]: [motivo em 1 frase]\n\nConcorda? Segue pra ver o primeiro dia da próxima cidade.",
 cta="Segue pra ver o próximo primeiro dia (seguir).",
 cp="Quadro do ranking. Texto da capa: “O MELHOR 1º DIA”.",
 so="Música da biblioteca; *tick* em cada linha do Quadro (máx. 1 efeito a cada 1,5 s).",
 me="Seguidores por 1.000 visualizações e comentários", hi="Ranking pessoal gera debate e mostra a amplitude do perfil. Aqui o CTA é de seguir; o teste T3 compara com envio.",
 te="T3:A",
 ma=["Uma cena de primeiro dia de cada cidade (mesmo levantamento do Reel de 03/11)"],
 pe=["Diego: ranking das 8 cidades e o motivo do 1º lugar"],
 of="Vários destinos", otr="Primeiro dia de cada cidade"),

dict(
 d="2026-12-16", h="18:00", f="C", k="ita", pl="UTIL", nv="—", st="ok",
 t="Natal em Roma: o que fizemos no dia 25",
 ob="Salvamento sazonal: o roteiro real de um dia de Natal em Roma, para quem vai passar as festas na Itália.",
 mo="Quem vai passar o Natal na Europa (decisão que acontece em dezembro). Salva para planejar; envia para a família.",
 g="Natal em Roma: o nosso dia 25.", gt="Resultado primeiro",
 q0="Capa em papel (variante B do teste T4): Rota do dia 25 com os horários das fotos.",
 sl=["1 · Capa (papel, variante B): Rota do dia 25/12 com horários do EXIF: Trevi 10:08 → Panteão (fachada) 10:50 → Navona → Ponte Sisto → Piazza di Spagna → Piazza del Popolo → Pincio 16:37 → Villa Borghese (vila de Natal).",
     "2 · Foto + informação: Fontana di Trevi às 10h08 do dia 25.",
     "3 · Foto + informação: Panteão (fachada) às 10h50.",
     "4 · Foto + informação: Piazza Navona (IMG_5132).",
     "5 · Foto + informação: Pincio ao pôr do sol, 16h37. Grátis.",
     "6 · Foto + informação: vila de Natal da Villa Borghese. € 17,60 por pessoa.",
     "7 · Dica (Bilhete): “no dia 25, roma é de quem anda: praças, fontes e parques.”",
     "8 · Informação (papel): o que costuma fechar no dia 25 (a confirmar nos sites oficiais em dezembro de 2026).",
     "9 · Encerramento: Placa CTA `SALVA PRA VIAGEM →` + 1º."],
 tl="Slides acima. Etiqueta `ROTEIRO`.",
 na="Não se aplica (carrossel).",
 lg="Natal em Roma: o nosso dia 25. 🎄\n\nNosso primeiro dia em Roma foi justamente 25 de dezembro. O roteiro, com a hora das fotos:\n\n10h08 · Fontana di Trevi\n10h50 · Panteão (por fora)\nPiazza Navona, Ponte Sisto, Piazza di Spagna e Piazza del Popolo\n16h37 · pôr do sol no Pincio\nNoite · vila de Natal da Villa Borghese (€ 17,60 por pessoa, ≈ R$ 113)\n\nNo dia 25, Roma é de quem anda: praças, fontes e parques. [Lista do que fecha no dia 25, a confirmar nos sites oficiais.]\n\nCotação: € 1 = R$ 6,40 (PTAX de 24/12/2024).\n\nSalva se você vai passar o Natal na Europa.",
 cta="Salva se você vai passar o Natal na Europa (salvamento).",
 cp="Capa em papel com a Rota do dia 25 (teste T4, variante B).",
 so="Música instrumental da biblioteca ao postar.",
 me="Salvamentos por alcance", hi="Roteiro sazonal publicado na época da decisão é muito salvo.",
 te="T4:B",
 ma=["IMG_5064, IMG_5108, IMG_5132, IMG_5220 e a vila de Natal", ROMA_FOTOS, "Horários do EXIF (carrosseis/roma-3-dias/rev1/QA_REV1.md)"],
 pe=["Confirmar o horário da vila de Natal (noite?)", "Confirmar em que dia vocês entraram no Panteão (o Panteão costuma fechar em 25/12; a foto das 10h50 é da fachada)", "Lista do que fecha no dia 25 (Coliseu e Museus Vaticanos costumam fechar): conferir nos sites oficiais em dezembro de 2026"],
 of="Fotos da Itália", otr="Roma, 25/12/2024"),

dict(
 d="2026-12-17", h="12:30", f="R", k="bxl", pl="DESEJO", nv="B", st="dec",
 t="Bruxelas em planos",
 ob="Desejo com gancho escrito (4º ponto A do teste T2): Bruxelas costuma ser só “passagem”; mostrar que dá vontade de ficar.",
 mo="Quem monta roteiro pela Bélgica. Envia para quem vai junto.",
 g="Bruxelas não é só passagem.", gt="Afirmação",
 q0="O plano mais bonito do centro de Bruxelas (decupagem). Placa Marca.",
 sc=[("0–2 s","Gancho","Melhor plano + Placa Marca + gancho escrito."),
     ("2–11 s","Desejo","IMG_2178 (Atomium, 1–4 s) + 4 planos do centro (decupagem)."),
     ("11–14 s","Fecho","Legenda Padrão: “bruxelas, 1 dia.”"),
     ("14–15 s","Loop","Volta ao quadro 0.")],
 tl="bruxelas não é só passagem · bruxelas, 1 dia.",
 na="Sem narração.",
 lg="Bruxelas não é só passagem. 🇧🇪\n\nTivemos um dia só e ele rendeu: Atomium de manhã e [paradas do centro].\n\nManda pra quem vai passar pela Bélgica.",
 cta="Manda pra quem vai passar pela Bélgica (envio).",
 cp="Centro de Bruxelas. Texto da capa: “BRUXELAS”.",
 so="Música instrumental da biblioteca.",
 me="Retenção média e envios", hi="Gancho escrito (4º ponto A do teste T2).",
 te="T2:A",
 ma=["IMG_2178.MP4 (Atomium)", "Brutos de Bruxelas (decupagem pendente)", OUTRAS],
 pe=["Decupagem de Bruxelas: centro"],
 of="Bruxelas", otr="IMG_2178 + decupagem"),

dict(
 d="2026-12-19", h="11:00", f="R", k="bcn", pl="UTIL", nv="B", st="ok",
 t="Metrô ilimitado em Barcelona: € 27,50 por 3 dias",
 ob="Salvamento: o passe de transporte que eles usaram e por que valeu, com a dica de onde ficar.",
 mo="Quem vai a Barcelona por 2 a 5 dias. Salva para comprar; envia para quem vai junto.",
 g="Metrô por 3 dias: € 27,50.", gt="Preço",
 q0="Diego e Marina na saída do metrô (master ≈ 00:31, estação Palau Reial) com Etiqueta de valor `€ 27,50`.",
 sc=[("0–2 s","Gancho","Saída da estação + Etiqueta de valor `€ 27,50 · 72 H`."),
     ("2–9 s","Contexto","Master 02:39–03:09: “bairro de Gràcia, mais residencial… por isso compramos um bilhete de metrô e ônibus para usar por 72 horas”."),
     ("9–14 s","Pico","Master 03:09–03:20: “vai pagar 27,50, mas com certeza a gente usaria muito mais”. Bilhete: “valeu a partir do dia 1.”"),
     ("14–17 s","Fechamento","Placa CTA `SALVA PRA VIAGEM →`.")],
 tl="metrô por 3 dias: € 27,50 · metrô e ônibus, 72 h · ficamos em gràcia, fora do centro · valeu",
 na="Sem narração nova.",
 lg="Metrô e ônibus ilimitados por 3 dias em Barcelona: € 27,50. 🚇\n\nFicamos em Gràcia, um bairro residencial e mais tranquilo, fora da muvuca do centro. Por isso compramos o passe de 72 horas e usamos muito mais do que pagamos.\n\n[Nome do passe a confirmar.] Confira o preço atual antes de comprar.\n\nCotação: € 1 = R$ [PTAX da data da viagem].\n\nSalva pra sua viagem a Barcelona.",
 cta="Salva pra sua viagem a Barcelona (salvamento).",
 cp="Saída do metrô com a etiqueta. Texto da capa: “€ 27,50 POR 3 DIAS”.",
 so="Falas originais + ambiente.",
 me="Salvamentos por alcance", hi="Preço de transporte concreto é salvo por quem planeja.",
 te=None,
 ma=[BCN_MASTER+": 00:31–00:50 e 02:39–03:20 (dia 1)", BCN_TRANS],
 pe=["Nome do passe (provável Hola Barcelona 72 h) e se € 27,50 foi por pessoa", "Preço atual em 2026 (TMB) para a legenda", "Data da viagem para a cotação"],
 of="Barcelona, dia 1", otr="Master 00:31–03:20"),

dict(
 d="2026-12-20", h="19:00", f="R", k="ams", pl="EXP", nv="A", st="dad",
 t="Expectativa × realidade: Amsterdam",
 ob="Identificação: o que eles imaginavam de Amsterdam e o que encontraram, em dois bilhetes. Formato que gera comentários.",
 mo="Quem já foi (compara) e quem vai (ajusta a expectativa). Comenta a própria experiência; envia para quem vai.",
 g="O que eu esperava de Amsterdam.", gt="Expectativa × realidade",
 q0="Dois bilhetes `esperado:` (−2°) e `real:` (+3°) sobre plano de canal (decupagem).",
 sc=[("0–2 s","Gancho","Bilhete `esperado:` com a expectativa real do Diego."),
     ("2–8 s","Esperado","Planos que ilustram a expectativa."),
     ("8–16 s","Real","Planos do que encontraram (frio, IMG_1384; cidade, decupagem). Bilhete `real:` circulado."),
     ("16–19 s","Pergunta","Legenda: “e a sua expectativa, bateu?”")],
 tl="o que eu esperava de amsterdam · esperado: [x] · real: [y]",
 na="Narração curta do Diego (até 8 s) com as palavras dele.",
 lg="O que eu esperava de Amsterdam × o que eu encontrei.\n\nEsperado: [expectativa real do Diego]\nReal: [o que encontraram]\n\nE a sua expectativa de Amsterdam, bateu? Comenta aqui.",
 cta="Comenta se a sua expectativa bateu (comentário).",
 cp="Os dois bilhetes sobre o canal. Texto da capa: “ESPERADO × REAL”.",
 so="Narração + música da biblioteca; 2 cliques de caneta por bilhete (máx. 2 bilhetes).",
 me="Comentários por alcance", hi="Expectativa × realidade gera identificação e comentários.",
 te=None,
 ma=["Brutos de Amsterdam (decupagem pendente)", "IMG_1384.MOV"],
 pe=["Diego: uma expectativa e uma realidade de Amsterdam (verdadeiras)"],
 of="Amsterdam", otr="Decupagem"),

# ───────────────────────── Semana 12 (21 a 27/12, Natal) ─────────────────────────
dict(
 d="2026-12-22", h="18:30", f="R", k="ita", pl="UTIL", nv="A", st="ok",
 t="52% do custo de Roma foi isso",
 ob="Envio e salvamento: mostrar onde está o dinheiro de verdade numa viagem (hospedagem) e a solução que eles usaram (dividir apartamento).",
 mo="Grupos de amigos e famílias que viajam juntos. Envia para o grupo da viagem; salva para planejar hospedagem.",
 g="52% do custo de Roma foi isso.", gt="Preço",
 q0="Recibo longo de Roma com a linha da hospedagem destacada em amarelo (Destaque) e `52,6%`.",
 sc=[("0–2 s","Gancho","Recibo de Roma com a linha da hospedagem pulsando uma vez + legenda Padrão."),
     ("2–8 s","Contexto","Foto do Monti (acervo) + legenda: “apartamento no monti, 4 noites, dividido por 5.”"),
     ("8–13 s","Número","Etiqueta de valor `€ 221,60 POR PESSOA`. Legenda: “de € 421,50, € 221,60 foram hospedagem.”"),
     ("13–18 s","Pico","Bilhete: “dividir a casa foi o que mais baixou o custo.”"),
     ("18–20 s","Fechamento","Placa CTA `MANDA PRA QUEM VAI →`.")],
 tl="52% do custo de roma foi isso · apartamento no monti, 4 noites, dividido por 5 · € 221,60 por pessoa · dividir a casa foi o que mais baixou o custo",
 na="Opcional: narração do Diego (até 8 s).",
 lg="52% do custo de Roma foi isso: hospedagem. 🏠\n\nDos € 421,50 que cada um gastou em 3 dias, € 221,60 foram do apartamento (≈ R$ 1.418). Fomos em 5 pessoas e dividimos um apartamento no Monti por 4 noites.\n\nDividir a hospedagem foi o que mais baixou o custo. Quem vai em 2 paga mais.\n\nCotação: € 1 = R$ 6,40 (PTAX de 24/12/2024).\n\nManda pro grupo da sua próxima viagem.",
 cta="Manda pro grupo da sua próxima viagem (envio).",
 cp="Recibo com 52%. Texto da capa: “52% FOI ISSO”.",
 so="Impressora térmica e *tick* quando existirem; música da biblioteca.",
 me="Envios por alcance", hi="Um número surpreendente sobre um custo comum (hospedagem) gera envios para grupos.",
 te=None,
 ma=["Registro de custos de Roma (ESTUDO_CARROSSEL_ROMA.md, seção 4)", ROMA_FOTOS, "Foto do bairro Monti ou do apartamento (localizar)"],
 pe=["Localizar foto do Monti ou do apartamento", "R$ 1.418 = 221,60 × 6,40 (R$ 1.418,24)"],
 of="Roma (custos)", otr="Hospedagem, dez/2024"),

dict(
 d="2026-12-23", h="18:00", f="C", k="dis", pl="UTIL", nv="—", st="dad",
 t="Disneyland Paris em 1 dia: € [total]",
 ob="Salvamento: o custo real de um dia na Disney de Paris (ingresso, transporte, comida), dúvida forte de quem planeja.",
 mo="Famílias e casais que avaliam a Disney de Paris. Salva para orçar; envia para quem vai junto.",
 g="Disney em 1 dia: € [total].", gt="Preço",
 q0="Capa em papel (variante B do teste T4): Recibo da Disney com o total por pessoa.",
 sl=["1 · Capa (papel): Recibo com total por pessoa e “1 dia, 2 parques”.",
     "2 · Foto (segunda capa): castelo com a placa M.",
     "3 · Ingresso: tipo e preço pago (a confirmar).",
     "4 · Transporte Paris–Disney e volta.",
     "5 · Comida no parque.",
     "6 · Extras (se houve).",
     "7 · Dica (Bilhete): onde dá para economizar (opinião real).",
     "8 · Encerramento: Placa CTA `SALVA PRA VIAGEM →` + 1º."],
 tl="Slides acima. Etiqueta `QUANTO CUSTOU`.",
 na="Não se aplica (carrossel).",
 lg="Disneyland Paris em 1 dia: € [total] por pessoa (≈ R$ [valor]).\n\nIngresso: € [valor]\nTransporte: € [valor]\nComida: € [valor]\nExtras: € [valor]\n\n[dica real]\n\nCotação: € 1 = R$ [PTAX da data da viagem].\n\nSalva pra planejar a sua Disney.",
 cta="Salva pra planejar a sua Disney (salvamento).",
 cp="Recibo da Disney (teste T4, variante B).",
 so="Música instrumental da biblioteca (sem trilhas da Disney).",
 me="Salvamentos por alcance", hi="Capa de papel com total (teste T4, variante B).",
 te="T4:B",
 ma=["Registro de custos da Disney (Diego)", "Fotos e quadros da Disney"],
 pe=["Diego: custos da Disney por categoria e por pessoa", "Sem custos até 16/12: trocar por carrossel “Disney de Paris: o que fizemos em cada parque”"],
 of="Disneyland Paris", otr="Registro de custos"),

dict(
 d="2026-12-24", h="12:30", f="R", k="ita", pl="SERIE", nv="B", st="ok",
 t="Nosso primeiro dia em Roma foi no Natal",
 ob="Série e conversão no dia mais simbólico do ano: o primeiro dia em Roma foi 25 de dezembro. Une a promessa da marca com a data.",
 mo="Quem acompanha o perfil e quem sonha com Natal na Europa. Segue pela história; envia para a família.",
 g="Primeiro dia em Roma: no Natal.", gt="Afirmação",
 q0="Fontana di Trevi às 10h08 do dia 25 (IMG_5064) com a Placa `PRIMEIRO DIA EM / ROMA` (Chegada).",
 sc=[("0–2 s","Gancho","Trevi + Placa de abertura (é o primeiro dia real). Legenda Padrão com Destaque em “Natal”."),
     ("2–12 s","O dia","Fotos na ordem do dia 25, 1,5 a 2 s cada, com zoom sutil: Trevi (10h08), Panteão (10h50), Navona, Pincio (16h37). Legenda Informação com a hora de cada foto."),
     ("12–16 s","Pico","Vila de Natal da Villa Borghese. Legenda Emocional: “um natal DIFERENTE”."),
     ("16–19 s","Fechamento","Placa `E ISSO FOI SÓ O / PRIMEIRO DIA.` + 1º + bordão. Legenda: “feliz natal.”")],
 tl="nosso primeiro dia em roma foi no natal · 10:08 trevi · 10:50 panteão · navona · 16:37 pincio · um natal diferente · e isso foi só o primeiro dia.",
 na="Opcional: o Diego grava o bordão “E isso foi só o primeiro dia.” (3 s).",
 lg="Nosso primeiro dia em Roma foi no Natal. 🎄\n\n25 de dezembro de 2024: Fontana di Trevi às 10h08, Panteão, Piazza Navona, pôr do sol no Pincio e a vila de Natal da Villa Borghese à noite.\n\nUm Natal longe de casa, do jeito que a gente nunca tinha passado.\n\nFeliz Natal! Sou o Diego e aqui eu mostro o primeiro dia em cada cidade. Segue pra ver os próximos.",
 cta="Segue pra ver os próximos primeiros dias (seguir).",
 cp="Trevi com a placa. Texto da capa: “1º DIA: NATAL”.",
 so="Música instrumental da biblioteca de clima natalino (da biblioteca do Instagram).",
 me="Seguidores por 1.000 visualizações", hi="A data simbólica + a série aumenta envios para família e seguidores (teste T3, variante A).",
 te="T3:A",
 ma=["IMG_5064, IMG_5108, IMG_5132, IMG_5220, vila de Natal", ROMA_FOTOS],
 pe=["Publicar na véspera (24/12, 12h30) com o carrossel de 16/12 já no perfil", "Confirmar que a vila de Natal foi no dia 25 (o QA diz dia 1 = 25/12)"],
 of="Fotos da Itália", otr="Roma, 25/12/2024"),

dict(
 d="2026-12-26", h="11:00", f="R", k="bcn", pl="DESEJO", nv="B", st="dec",
 t="Vista de Barcelona do alto do Montjuïc",
 ob="Desejo com informação prática (como chegar), 4º ponto B do teste T1.",
 mo="Quem sonha com Barcelona. Envia para quem iria junto; salva para o roteiro.",
 g="A vista que vale a subida.", gt="Afirmação",
 q0="Vista de Barcelona do Montjuïc (IMG_0586), em movimento. Placa Marca.",
 sc=[("0–2 s","Gancho","IMG_0586 (vista) + Placa Marca + gancho escrito."),
     ("2–8 s","Desejo","Planos da subida e do castelo (master 03:09–04:15, ou brutos)."),
     ("8–12 s","Informação","Legenda Informação: `METRÔ + SUBIDA A PÉ` (variante B do teste T1). Etiqueta de valor só se houve pagamento registrado."),
     ("12–15 s","Loop","Volta à vista.")],
 tl="a vista que vale a subida · montjuïc, barcelona · metrô + subida a pé",
 na="Sem narração.",
 lg="A vista que vale a subida. ⛰️\n\nMontjuïc, em Barcelona. O metrô deixa perto e o resto a gente subiu a pé até o castelo. O nome vem de “monte dos judeus”.\n\nManda pra quem vai subir com você.",
 cta="Manda pra quem vai subir com você (envio).",
 cp="Vista de Barcelona do alto. Texto da capa: “VALE A SUBIDA”.",
 so="Música instrumental da biblioteca (o bruto tem músico de rua: trocar o áudio).",
 me="Seguidores por 1.000 visualizações e envios", hi="Desejo + informação prática (4º ponto B do teste T1).",
 te="T1:B",
 ma=["IMG_0586.MOV (Montjuïc, vista)", BCN_MASTER+": 03:09–04:15"],
 pe=["Confirmar se pagaram para entrar no castelo (não citar valor sem registro)", "Conferir a origem do nome (“monte dos judeus”) em fonte oficial"],
 of="Barcelona, dia 1", otr="IMG_0586 + master 03:09–04:15"),

dict(
 d="2026-12-27", h="19:00", f="R", k="mad", pl="EXP", nv="B", st="dec",
 t="Madrid: o momento que eu não esperava",
 ob="Identificação: um momento real de Madrid que surpreendeu (bom ou ruim), contado com a fala do próprio vídeo.",
 mo="Quem vai a Madrid e quem gosta de histórias de viagem. Comenta; envia para quem vai.",
 g="Eu não esperava isso em Madrid.", gt="“Eu não esperava isso”",
 q0="A cena do momento (decupagem), com legenda Emocional “eu não esperava ISSO”.",
 sc=[("0–2 s","Gancho","Cena do momento + legenda Emocional."),
     ("2–14 s","História","Fala real do momento, cortes secos."),
     ("14–18 s","Pico","Ticket SURPREENDE (se foi bom) ou Carimbo PERRENGUE com data e hora reais (se foi ruim). Um só."),
     ("18–20 s","Loop","Volta ao quadro 0.")],
 tl="eu não esperava isso em madrid · [momento] · [desfecho]",
 na="Sem narração nova (fala do momento).",
 lg="Eu não esperava isso em Madrid.\n\n[O que aconteceu, em 2 ou 3 linhas, do jeito que foi.]\n\nJá aconteceu algo assim com você numa viagem? Conta aqui.",
 cta="Conta nos comentários (comentário).",
 cp="Cena do momento. Texto da capa: “EM MADRID?!”",
 so="Falas + música da biblioteca baixa.",
 me="Comentários e envios", hi="Um momento real e inesperado gera mais identificação que roteiro.",
 te=None,
 ma=["Brutos de Madrid (decupagem pendente)"],
 pe=["Decupagem: identificar um momento real de surpresa ou perrengue em Madrid. Se não houver, trocar por “Primeira comida em Madrid” (Vale ou pula)"],
 of="Madrid", otr="Decupagem"),

# ───────────────────────── Semana 13 (28/12 a 03/01, Réveillon) ─────────────────────────
dict(
 d="2026-12-29", h="18:30", f="R", k="multi", pl="EXP", nv="B", st="ok",
 t="Ninguém avisou desse frio",
 ob="Identificação: o frio em várias cidades, dito por eles mesmos, na época em que muitos brasileiros vão para a Europa no inverno.",
 mo="Quem vai para a Europa no fim de ano ou no inverno. Envia para quem vai viajar no frio; comenta a própria experiência.",
 g="Ninguém avisou desse frio.", gt="Afirmação",
 q0="Barceloneta, Marina de casaco: “tá frio pra caramba” (master ≈ 06:55). Placa Marca.",
 sc=[("0–2 s","Gancho","Master ≈ 06:55: “tá frio pra caramba” + Placa Marca."),
     ("2–6 s","Amsterdam","IMG_1384 (0–2 s): “Tá frio?” e IMG_1393 (15–17 s): “tá muito frio”."),
     ("6–10 s","Bruges","IMG_2692 (8–10 s): luvas, casaco e waffle quente."),
     ("10–14 s","Barcelona","Master ≈ 07:00: “a galera daqui não sente frio” (gente no jet ski)."),
     ("14–17 s","Pergunta","Legenda: “qual foi o lugar mais frio que você já foi?”")],
 tl="ninguém avisou desse frio · barcelona · amsterdam · bruges · e tinha gente de jet ski",
 na="Sem narração nova.",
 lg="Ninguém avisou desse frio. 🥶\n\nBarcelona, Amsterdam, Bruges: em todas a primeira frase do dia foi sobre o frio. E em Barcelona ainda tinha gente de jet ski no mar.\n\nSe você vai para a Europa nessa época, leve casaco, luva e paciência.\n\nQual foi o lugar mais frio em que você já esteve? Conta aqui.",
 cta="Conta o lugar mais frio em que você já esteve (comentário).",
 cp="Marina de casaco na praia. Texto da capa: “QUE FRIO É ESSE?”",
 so="Falas originais + música da biblioteca baixa.",
 me="Comentários e envios por alcance", hi="Uma situação comum a quem viaja no inverno gera identificação entre cidades diferentes.",
 te=None,
 ma=[BCN_MASTER+": 06:50–07:21", "IMG_1384, IMG_1393 (Amsterdam), IMG_2692 (Bruges)", OUTRAS],
 pe=["Confirmar o mês da viagem (pela vegetação, parece fim de inverno ou começo de primavera): a legenda não cita mês"],
 of="Vários destinos", otr="Falas sobre o frio"),

dict(
 d="2026-12-30", h="18:00", f="C", k="ita", pl="UTIL", nv="—", st="dad",
 t="Milão em 2 dias: € [total]",
 ob="Salvamento: custo e roteiro reais de Milão, fechando a série de custos por cidade da Itália.",
 mo="Quem planeja Itália em várias cidades (Milão costuma ser a chegada ou a saída). Salva para orçar.",
 g="Milão em 2 dias: € [total].", gt="Preço",
 q0="Capa com foto (variante A do teste T4): foto forte de Milão com a Placa G `QUANTO CUSTOU` / `MILÃO`.",
 sl=["1 · Capa (foto): Milão + Placa G `QUANTO CUSTOU` / `MILÃO` + total.",
     "2 · Recibo (segunda capa) por categoria e por pessoa.",
     "3 · Rota dos 2 dias.",
     "4–8 · Fotos + informação dos lugares.",
     "9 · Dica (Bilhete) real.",
     "10 · Encerramento: Placa CTA `SALVA PRA VIAGEM →` + 1º."],
 tl="Slides acima. Etiqueta `QUANTO CUSTOU`.",
 na="Não se aplica (carrossel).",
 lg="Milão em 2 dias: € [total] por pessoa (≈ R$ [valor]).\n\n[categorias e roteiro, a preencher]\n\nCotação: € 1 = R$ [PTAX da data].\n\nSalva pra sua viagem pela Itália.",
 cta="Salva pra sua viagem pela Itália (salvamento).",
 cp="Milão com a Placa G (teste T4, variante A).",
 so="Música instrumental da biblioteca ao postar.",
 me="Salvamentos por alcance", hi="Capa de foto (teste T4, variante A).",
 te="T4:A",
 ma=["Fotos de Milão (inventário pendente)", "Registro de custos de Milão (Diego)"],
 pe=["Diego: custos de Milão", "Lista de lugares e fotos", "Datas em Milão"],
 of="Itália: Milão", otr="Inventário pendente"),

dict(
 d="2026-12-31", h="12:30", f="R", k="ita", pl="EXP", nv="B", st="dad",
 t="Réveillon na Itália: como foi",
 ob="Identificação sazonal: a virada do ano na viagem pela Itália, publicada no próprio dia 31.",
 mo="Quem sonha em passar o Ano-Novo na Europa. Envia para quem passaria junto; comenta onde vai passar.",
 g="Nosso Réveillon foi em [cidade].", gt="Afirmação",
 q0="Melhor foto ou vídeo da noite de 31/12/2024 (a localizar). Placa Marca.",
 sc=[("0–2 s","Gancho","Melhor imagem da noite + Placa Marca + gancho escrito."),
     ("2–12 s","A noite","Fotos ou vídeos da noite, em ordem."),
     ("12–15 s","Fecho","Legenda Emocional: “feliz ANO-NOVO”."),
     ("15–16 s","Loop","Volta ao quadro 0.")],
 tl="nosso réveillon foi em [cidade] · [momentos] · feliz ano-novo",
 na="Sem narração.",
 lg="Nosso Réveillon foi em [cidade], na Itália. 🥂\n\n[Como foi a noite, do jeito que foi.]\n\nFeliz Ano-Novo! Onde você vai passar a virada? Conta aqui.",
 cta="Conta onde vai passar a virada (comentário).",
 cp="Imagem da noite. Texto da capa: “RÉVEILLON NA ITÁLIA”.",
 so="Música instrumental da biblioteca, clima de festa.",
 me="Envios e comentários", hi="Conteúdo de data comemorativa ligado a uma experiência real gera envios no próprio dia.",
 te=None,
 ma=["Fotos e vídeos da noite de 31/12/2024 (a localizar)"],
 pe=["Diego: em que cidade foi o Réveillon e se há fotos ou vídeos da noite", "Plano B se não houver material da noite: “Fim de ano na Itália: 9 dias em 4 cidades” com fotos de cada cidade"],
 of="Itália", otr="31/12/2024"),

dict(
 d="2027-01-02", h="11:00", f="R", k="dis", pl="UTIL", nv="A", st="dad",
 t="Paris + Disney em 2 dias: dá?",
 ob="Salvamento e comparação: como encaixar Paris e Disney numa viagem curta, com o que eles realmente fizeram (1 dia cada).",
 mo="Quem vai a Paris pela primeira vez e quer a Disney. Salva para planejar; envia para quem vai junto.",
 g="Paris + Disney em 2 dias: dá?", gt="Pergunta",
 q0="Tela dividida: Torre Eiffel (IMG_2761) × castelo da Disney, com `DIA 1` e `DIA 2` em placas pequenas.",
 sc=[("0–2 s","Gancho","Tela dividida + 2 placas pequenas `DIA 1 · PARIS` / `DIA 2 · DISNEY`."),
     ("2–10 s","Dia 1","Paris: o que deu (e o Luxemburgo que ficou de fora)."),
     ("10–18 s","Dia 2","Disney: os 2 parques."),
     ("18–23 s","Veredito","Bilhete: “dá, se você aceitar escolher.” (confirmar com o Diego)"),
     ("23–25 s","Fechamento","Placa CTA `SALVA PRA VIAGEM →`.")],
 tl="paris + disney em 2 dias: dá? · dia 1: paris · dia 2: disney · [veredito]",
 na="Narração curta do Diego com o veredito (até 6 s).",
 lg="Paris + Disney em 2 dias: dá? 🗼🏰\n\nDia 1: Paris. [paradas]. Ficou de fora o Jardim de Luxemburgo.\nDia 2: Disneyland Paris, os dois parques.\n\nVeredito: [opinião do Diego].\n\nSalva pra planejar a sua viagem.",
 cta="Salva pra planejar a sua viagem (salvamento).",
 cp="Tela dividida. Texto da capa: “PARIS + DISNEY?”",
 so="Narração + música da biblioteca.",
 me="Salvamentos e envios", hi="Comparação/combinação de dois destinos (teste T5, variante B).",
 te="T5:B",
 ma=["IMG_2730, IMG_2761, IMG_3134 (Paris)", "Brutos da Disney (decupagem pendente)", OUTRAS],
 pe=["Veredito do Diego", "Usar planos diferentes dos Reels anteriores de Paris e Disney"],
 of="Paris e Disney", otr="Decupagem"),

dict(
 d="2027-01-03", h="19:00", f="R", k="multi", pl="EXP", nv="B", st="dad",
 t="Comida de rua na Europa: nossa nota sincera",
 ob="Identificação e comentários: ranking curto das comidas de rua que eles provaram, com nota honesta.",
 mo="Quem ama comida e viagem. Comenta discordando; envia para quem vai provar.",
 g="Comida de rua da Europa: nota sincera.", gt="Lista",
 q0="Close do churro com chocolate (master ≈ 27:30) com Quadro (ranking) acendendo.",
 sc=[("0–2 s","Gancho","Close + Quadro com o título."),
     ("2–6 s","Item 1","Churros com chocolate quente e de Kinder Bueno, Barcelona (master 27:30–28:00). Nota do Diego."),
     ("6–10 s","Item 2","Empanadas, Barcelona (master 28:54–29:30). Nota."),
     ("10–14 s","Item 3","Waffle de rua, Bruges (IMG_2693). Nota."),
     ("14–18 s","Item 4","Comida de rua em Roma (foto do acervo). Nota."),
     ("18–21 s","Pergunta","Legenda: “qual você provaria primeiro?”")],
 tl="comida de rua da europa: nota sincera · churros (bcn) · empanadas (bcn) · waffle (bruges) · [roma] · [notas]",
 na="Sem narração nova (ou notas em legenda).",
 lg="Comida de rua da Europa: nossa nota sincera. 😋\n\nChurros com chocolate (e um de Kinder Bueno), Barcelona: [nota]\nEmpanadas, Barcelona: [nota]\nWaffle de rua, Bruges: [nota]\n[comida de rua de Roma]: [nota]\n\nQual você provaria primeiro? Comenta aqui.",
 cta="Comenta qual você provaria primeiro (comentário).",
 cp="Churros com chocolate. Texto da capa: “NOTA SINCERA”.",
 so="Falas originais + música da biblioteca.",
 me="Comentários por alcance", hi="Ranking de comida com nota pessoal gera debate.",
 te=None,
 ma=[BCN_MASTER+": 27:30–29:30 (dia 3)", "IMG_2693 (Bruges)", ROMA_FOTOS],
 pe=["Notas do Diego para cada item", "Identificar qual comida de rua de Roma tem foto"],
 of="Vários destinos", otr="Master BCN 27:30–29:30 + Bruges + Roma"),
]
