# -*- coding: utf-8 -*-
"""Peças do calendário v3 (parte 1: 10/10 a 01/11/2026).

Cada peça é um dicionário com chaves curtas; `reconstruir_v3.py` converte para o formato do painel.
Chaves: d (data) · h (hora) · f (R = Reel, C = carrossel) · k (destino) · pl (pilar) · nv (nível de edição)
st (status do material: ok, dec, dad, fut) · t (título) · ob (objetivo) · mo (público e motivação)
g (gancho) · gt (tipo de gancho) · q0 (primeiro quadro) · sc (cenas: tempo, rótulo, texto) · sl (slides)
tl (texto na tela) · na (narração) · lg (legenda) · cta · cp (capa) · so (som) · me (métrica principal)
hi (hipótese) · te (teste) · ma (material) · pe (pendências) · of (origem) · otr (trecho de origem)
"""

BCN_MASTER = "Vlog master de Barcelona (34:08, 4K HLG 16:9, em reels/apresentacao/fonte/, fora do git). Atenção: o B-roll do master tem trilha de violão embutida e alguns trechos têm etiquetas gráficas; para cenas sem fala, usar os brutos originais"
BCN_TRANS = "Transcrição com tempo por palavra: reels/apresentacao/analise/transcricao_palavras.tsv"
OUTRAS = "Brutos do primeiro dia das outras cidades (fonte/outras_cidades/, fora do git). Folhas de quadros em reels/apresentacao/analise_outras/folhas/ e transcrição em analise_outras/transcricao_outras.tsv"
ROMA_FOTOS = "Fotos de Roma já tratadas para o carrossel REV1 (carrosseis/roma-3-dias/fonte/, fora do git; lista com EXIF em carrosseis/roma-3-dias/rev1/QA_REV1.md)"
COT_ROMA_2024 = "€ 1 = R$ 6,40 (PTAX de 24/12/2024)"
COT_2026 = "€ 1 = R$ 5,88 (02/10/2026; atualizar no dia de postar)"

PECAS = [
# ───────────────────────── Semana 1 (09 a 11/10) ─────────────────────────
dict(
 d="2026-10-10", h="11:00", f="R", k="bxl", pl="UTIL", nv="B", st="ok",
 t="Atomium: o cristal de ferro gigante de Bruxelas",
 ob="Descoberta: curiosidade verdadeira sobre um monumento reconhecível, entendida em 2 segundos, para alcançar quem não segue e mostrar que o perfil não é só Barcelona.",
 mo="Quem sonha com a Europa e quem vai a Bruxelas. Envia porque é uma curiosidade fácil de repassar (\"você sabia?\"). Salva quem vai e quer decidir se sai do centro.",
 g="Isso é um cristal de ferro.", gt="Surpresa",
 q0="IMG_2178 em 0,0 s: Atomium inteiro contra o céu azul, plano aberto, sem pessoas na frente. Texto do gancho já na tela.",
 sc=[("0–2 s","Gancho","IMG_2178 (0,0–2,0 s) com zoom sutil 100→104%. Legenda Padrão: “isso é um cristal de ferro.” com Destaque em “ferro”."),
     ("2–6 s","Contexto","IMG_2170 (0,2–5,0 s): “Primeira parada: Atomium. Aqui em Bruxelas, a gente veio de metrô.” Legenda Padrão no tempo da fala."),
     ("6–13 s","Pico","IMG_2170 (36,2–49,2 s): a explicação do cristal ampliado 165 bilhões de vezes e da exposição de 1958. Ticket SABIA? sobe no canto (zona de objeto, lado oposto ao rosto) com “165 bilhões de vezes”."),
     ("13–18 s","Veredito","IMG_2170 (21,2–32,2 s, cortes secos): dá para subir, mas eles não subiram porque fica longe do centro. Legenda Padrão."),
     ("18–20 s","Loop","IMG_2178 (3,0–5,0 s): volta ao plano do quadro 0 para o replay.")],
 tl="isso é um cristal de ferro. · 165 bilhões de vezes maior · feito pra expo de 1958 · dá pra subir, mas fica longe do centro",
 na="Sem narração nova. Usar as falas originais do IMG_2170 (Diego e Marina).",
 lg="Isso é um cristal de ferro. 165 bilhões de vezes maior.\n\nO Atomium foi construído para a Exposição Universal de 1958, em Bruxelas, e representa a estrutura de um cristal de ferro ampliada. De perto, parece coisa de agora.\n\nFoi a nossa primeira parada em Bruxelas. Fomos de metrô. Dá para subir, mas a gente preferiu não subir: ele fica fora do centro e o dia era um só.\n\nVai para a Bélgica? Manda pra quem vai com você.",
 cta="Manda pra quem vai pra Bélgica com você (envio).",
 cp="Quadro do IMG_2178 com o Atomium centralizado. Texto da capa: “CRISTAL DE FERRO?” dentro da área central 3:4.",
 so="Falas originais + som ambiente. Música instrumental da biblioteca do Instagram 8 a 10 dB abaixo da voz. Ticket sem som próprio (SABIA? é a Subida curta).",
 me="Envios por alcance", hi="Uma curiosidade verdadeira sobre um lugar famoso alcança não seguidores sem precisar de preço e abre o rodízio de cidades.",
 te=None,
 ma=["IMG_2178.MP4 (5,9 s, horizontal, SDR): Atomium contra o céu", "IMG_2170.MP4 (62 s, fala): chegada de metrô, explicação e decisão de não subir", OUTRAS],
 pe=["IMG_2170 e IMG_2178 no repositório são cópias 720p (o Atomium fica suave ampliado). Pedir os originais em resolução cheia hoje; se não chegarem a tempo, trocar este Reel de data com o de 13/10 (água, master 4K)", "Os dois brutos são horizontais: conferir o recorte 9:16 do Atomium inteiro no quadro 0", "Não citar preço da subida (não foi registrado). Se quiser citar, conferir em atomium.be no dia"],
 of="Brutos de Bruxelas", otr="IMG_2178 (0–5 s) e IMG_2170 (0–62 s)"),

dict(
 d="2026-10-11", h="19:00", f="R", k="bcn", pl="SERIE", nv="B", st="ok",
 t="Camisa do Bahia no Camp Nou",
 ob="Conversão: mostrar quem é o Diego (soteropolitano, torcedor do Bahia, bem-humorado) dentro do primeiro dia em Barcelona, para dar motivo de seguir a pessoa, e não só a paisagem.",
 mo="Torcedores do Bahia, baianos e brasileiros que gostam de futebol e de viagem. Envia para o amigo tricolor ou para quem vai ao Camp Nou. Segue porque se identifica com o Diego.",
 g="Camisa do Bahia no Camp Nou.", gt="Afirmação",
 q0="Diego em frente ao estádio, de camisa do Bahia, falando para a câmera (master ≈ 02:22). Placa `PRIMEIRO DIA EM / BARCELONA` entra com a Chegada em x 72 · y 640.",
 sc=[("0–2,5 s","Gancho","Master ≈ 02:22: “Estou com a camisa do maior clube do mundo, o Esporte Clube Bahia.” Placa de abertura (é o primeiro dia real). Legenda Padrão com Destaque em “Bahia”."),
     ("2,5–6 s","Contexto","IMG_0502 (2,7–6,0 s): chegando ao Camp Nou, com a fila. Legenda Narrativa: “primeiro dia em barcelona. primeira parada: o barça.”"),
     ("6–10 s","Desenvolvimento","Master 01:21–01:30: a Bola de Ouro do Ronaldinho no museu (“que bizarrice”)."),
     ("10–18 s","Pico","Master ≈ 02:30–02:45: Marina conta que o funcionário viu a camisa e disse “Bahia é o mundo”. Legenda Padrão com Destaque em “mundo”."),
     ("18–22 s","Verdade","Master ≈ 01:45–01:55: o estádio estava em reforma e não deu para entrar no campo."),
     ("22–24 s","Fechamento","Corte seco de volta ao rosto do quadro 0 (loop).")],
 tl="camisa do bahia no camp nou · primeiro dia em barcelona · “bahia é o mundo” · estádio em reforma: só o museu",
 na="Sem narração nova. Falas originais do master (Diego e Marina).",
 lg="Camisa do Bahia no Camp Nou. 💙❤️🤍\n\nPrimeiro dia em Barcelona e a primeira parada foi o museu do Barça. Fui de camisa do Bahia, claro.\n\nQuando tirei o casaco para a foto, o funcionário olhou e mandou: “Bahia é o mundo.”\n\nO estádio estava em reforma e não deu para entrar no campo, mas o museu tem a Bola de Ouro do Ronaldinho, camisas de ídolos e uma sala 360. Ingresso comprado no site oficial: € 31 [confirmar se foi por pessoa].\n\nSou o Diego, de Salvador, e aqui eu mostro o primeiro dia em cada cidade que eu visito. Segue pra ver a próxima.",
 cta="Segue pra ver o primeiro dia da próxima cidade (seguir).",
 cp="Diego de camisa do Bahia com o estádio atrás. Texto da capa: “BAHIA NO CAMP NOU”.",
 so="Som direto das falas. Música da biblioteca só se o trecho tiver trilha embutida que precise ser coberta; nesse caso, trocar o trecho por bruto.",
 me="Seguidores por 1.000 visualizações", hi="Identidade (soteropolitano + Bahia) converte mais que paisagem: esperar mais seguidores por 1.000 visualizações que o POV de 04/10 (≈ 1,5 por 1.000).",
 te="T3:A",
 ma=[BCN_MASTER+": trechos 01:21–01:55 e 02:09–02:50", "IMG_0502.MOV (Camp Nou, chegada com fila)", BCN_TRANS],
 pe=["Ouvir 02:09–02:50 do master: se houver violão sob a fala, procurar o bruto desse trecho (o IMG_0520 está desfocado)", "Confirmar se os € 31 foram por pessoa", "Não afirmar o estado atual da reforma do estádio: dizer “na época”"],
 of="Barcelona, dia 1", otr="Master 01:21–02:50 e IMG_0502"),

# ───────────────────────── Semana 2 (12 a 18/10) ─────────────────────────
dict(
 d="2026-10-13", h="18:30", f="R", k="bcn", pl="UTIL", nv="A", st="ok",
 t="Não compre água em Barcelona",
 ob="Salvamento e envio: dica prática que economiza dinheiro em todos os dias da viagem, com prova filmada.",
 mo="Quem vai a Barcelona (com data marcada ou planejando). Salva para a viagem; envia para o grupo da viagem.",
 g="Não compre água em Barcelona.", gt="Não faça isso",
 q0="Close da garrafa reutilizável na mão (master ≈ 18:05) com a Placa `NÃO FAÇA ISSO / ÁGUA` entrando com a Chegada.",
 sc=[("0–2 s","Gancho","Master ≈ 18:05: a garrafa na mão. Placa variante Não faça: `NÃO FAÇA ISSO` + `ÁGUA`."),
     ("2–9 s","Contexto","Master 18:05–18:20: “compramos essa garrafa ontem… tem várias fontes espalhadas pela cidade para a galera beber água.” A placa sai pela direita. Legenda Padrão."),
     ("9–16 s","Entrega","Master 18:20–18:35: o aplicativo com o mapa das fontes e o ciclo “enche, guarda, procura outra fonte”. Se houver plano da tela do celular ou de uma fonte, inserir aqui (decupagem)."),
     ("16–22 s","Pico","Bilhete na letra do Diego: “dica: garrafa + app de fontes.”"),
     ("22–25 s","Fechamento","Placa CTA `SALVA PRA VIAGEM →`.")],
 tl="não compre água em barcelona · a cidade tem fontes de água potável · tem app com o mapa das fontes · dica: garrafa + app",
 na="Sem narração nova (falas do master). Se o trecho tiver violão por baixo, regravar só a frase “a cidade tem fontes de água potável espalhadas” como narração curta.",
 lg="Não compre água em Barcelona. 💧\n\nA cidade tem fontes de água potável espalhadas pelas ruas. A gente comprou uma garrafa no primeiro dia e foi enchendo nas fontes durante os 3 dias.\n\nPara achar a fonte mais perto, baixamos um app com o mapa das fontes: [nome do app a confirmar].\n\nGarrafa na mochila: menos gasto com água e menos parada para comprar.\n\nSalva pra sua viagem a Barcelona.",
 cta="Salva pra sua viagem a Barcelona (salvamento).",
 cp="Garrafa em primeiro plano com rua de Barcelona ao fundo. Texto da capa: “ÁGUA DE GRAÇA”.",
 so="Som direto. Música da biblioteca baixa. Bilhete com 2 cliques de caneta quando o arquivo PD_clique existir.",
 me="Salvamentos por alcance", hi="Dica que economiza em todos os dias da viagem gera mais salvamentos que dica de um lugar só.",
 te="T5:A",
 ma=[BCN_MASTER+": trecho 18:05–18:35 (dia 2)", BCN_TRANS],
 pe=["Confirmar o nome do app (a transcrição registrou “Fontsep”)", "Procurar nos brutos um plano de uma fonte ou da garrafa sendo enchida", "Conferir na fonte oficial (Aigües de Barcelona / Ajuntament) que as fontes públicas são de água potável e citar a fonte nos comentários se perguntarem"],
 of="Barcelona, dia 2", otr="Master 18:05–18:35"),

dict(
 d="2026-10-14", h="18:00", f="C", k="bcn", pl="UTIL", nv="—", st="ok",
 t="Roteiro do primeiro dia em Barcelona: 18 km a pé",
 ob="Salvamento: o roteiro real do dia 1, na ordem em que aconteceu, com o que cada parada custou. É o carrossel de consulta que quem vai a Barcelona guarda.",
 mo="Quem vai a Barcelona e monta roteiro. Salva para copiar o dia; envia para quem divide a viagem.",
 g="18 km a pé no primeiro dia.", gt="Resultado primeiro",
 q0="Capa: Diego e Marina na Barceloneta ou no Arco do Triunfo (quadro do master), Placa G `PRIMEIRO DIA EM / BARCELONA` na base esquerda e a linha “18 km a pé”.",
 sl=["1 · Capa (foto em sangria): Placa G `PRIMEIRO DIA EM / BARCELONA` + “18 km a pé” em Barlow 500. Teste de miniatura a 25%.",
     "2 · Rota (segunda capa, funciona sozinho): Gràcia → Camp Nou → Montjuïc → Barceloneta → Ciutadella → Arco do Triunfo → primeira tapa. Sem horários (não há registro de hora).",
     "3 · Foto + informação: Gràcia. Ficamos num bairro residencial, com mercado e cafés ao lado. Passe de metrô e ônibus de 72 h: € 27,50 [confirmar se por pessoa].",
     "4 · Foto + informação: museu do Barça (Camp Nou). € 31 no site oficial [confirmar se por pessoa]. Estádio em reforma na época: só o museu.",
     "5 · Foto + informação: Montjuïc. O metrô deixa perto; subimos a pé até o castelo. A Fonte Mágica estava sem espetáculos no período.",
     "6 · Foto + informação: descida a pé até a Barceloneta, passando pelo monumento a Colombo.",
     "7 · Foto + informação: almoço rápido e praia da Barceloneta (frio, mas tinha gente no jet ski).",
     "8 · Foto + informação: cascata do Parc de la Ciutadella e Arco do Triunfo no fim da tarde.",
     "9 · Dica (Bilhete): “compramos o café da manhã do dia seguinte no mercado.” É a regra que segurou o orçamento.",
     "10 · Foto + informação: primeira tapa da viagem: patatas bravas com cerveza.",
     "11 · Encerramento: veredito Bilhete “dá, mas vá de tênis.” + Placa CTA `SALVA PRA VIAGEM →` + símbolo 1º."],
 tl="Slides acima. Contador Plex Mono no canto superior direito, etiqueta de série `ROTEIRO` no superior esquerdo, Rota amarela em y 1360 ligando os slides.",
 na="Não se aplica (carrossel).",
 lg="18 km a pé no primeiro dia em Barcelona. 👟\n\nEsse foi o nosso roteiro do dia 1, na ordem em que aconteceu:\n\n1. Gràcia, o bairro onde ficamos\n2. Museu do Barça, no Camp Nou (€ 31 [confirmar se por pessoa])\n3. Montjuïc, subindo a pé até o castelo\n4. Descida até a Barceloneta, passando pelo Colombo\n5. Almoço rápido e praia\n6. Parc de la Ciutadella e Arco do Triunfo no fim da tarde\n7. Mercado para o café da manhã do dia seguinte\n8. Primeira tapa: patatas bravas e cerveza\n\nDá para fazer tudo a pé e de metrô, mas o corpo sente. Passe de 72 h: € 27,50 [confirmar se por pessoa].\n\nCotação: € 1 = R$ [PTAX da data da viagem].\n\nSalva esse roteiro pra sua viagem a Barcelona.",
 cta="Salva esse roteiro pra sua viagem (salvamento).",
 cp="Foto com Diego e Marina em lugar reconhecível do dia 1 (Barceloneta ou Arco do Triunfo), Placa G e “18 km a pé”.",
 so="Música instrumental da biblioteca do Instagram ao postar (deixa o carrossel elegível para a aba Reels).",
 me="Salvamentos por alcance", hi="Carrossel com capa de foto (pessoa + lugar) alcança mais não seguidores que capa de papel; o roteiro real gera salvamentos.",
 te="T4:A",
 ma=[BCN_MASTER+": quadros do dia 1 (00:00–10:57)", "Brutos IMG_0502 (Camp Nou), IMG_0586 (Montjuïc), IMG_0690 (Barceloneta), IMG_0781 (Arco)", BCN_TRANS],
 pe=["Valores € 31 e € 27,50: confirmar se foram por pessoa", "Cotação: informar a data da viagem para usar a PTAX do dia", "Usar quadros sem etiqueta gráfica do vlog e com tone mapping HDR→SDR (mesma conversão aprovada no Reel de apresentação)", "Conferir no site oficial o estado da Fonte Mágica em 2026 só se for citar como dica atual"],
 of="Barcelona, dia 1", otr="Master 00:00–10:57"),

dict(
 d="2026-10-15", h="12:30", f="R", k="par", pl="EXP", nv="B", st="ok",
 t="Paris: chegamos e o jardim estava fechado",
 ob="Identificação e utilidade: perrengue real, com a dica que evita repetir o erro. Mostra que o perfil conta o que deu errado.",
 mo="Quem vai a Paris e quem já perdeu um passeio por horário. Comenta a própria história; envia para quem vai a Paris.",
 g="Chegamos e o jardim estava fechado.", gt="Afirmação",
 q0="IMG_3134 em 0 s: Diego e Marina falando em frente ao portão gradeado do Jardim de Luxemburgo, luz de fim de tarde.",
 sc=[("0–2 s","Gancho","IMG_3134 (0,0–3,0 s): “Infelizmente, tínhamos um planejamento de um pôr do sol aqui dentro.” Legenda Padrão com o gancho escrito."),
     ("2–8 s","Contexto","IMG_3134 (5,0–9,0 s e 14,0–19,0 s): Jardim de Luxemburgo, a ansiedade da Marina e “a gente deixou por último… não conseguiu entrar”."),
     ("8–14 s","Pico","IMG_3134 (19,0–27,0 s): “vai uma dica: fica aberto de 7h30 até 18h30”. Bilhete: “dica: o horário muda com a estação. vá cedo.”"),
     ("14–19 s","Virada","IMG_3134 (40,0–50,0 s): “agora a gente vai ver a Torre Eiffel de noite, ver ela brilhar.”"),
     ("19–21 s","Fechamento","IMG_3134 (60,0–63,0 s): sorriso final (“foi bom demais”). Corte seco.")],
 tl="chegamos e o jardim estava fechado · era o plano do pôr do sol · dica: o horário muda com a estação · vá cedo",
 na="Sem narração nova (falas originais).",
 lg="Chegamos e o Jardim de Luxemburgo estava fechado. 🔒\n\nO plano era ver o pôr do sol lá dentro. Deixamos para o fim do dia e, quando chegamos, o portão já estava trancado: naquele dia, fechava às 18h30.\n\nO horário de fechamento muda conforme a época do ano. Antes de ir, confira no site oficial e vá mais cedo.\n\nPara salvar o fim de tarde, fomos ver a Torre Eiffel brilhar à noite.\n\nJá perdeu um passeio por causa de horário? Conta aqui.",
 cta="Conta nos comentários se já perdeu um passeio por horário (comentário).",
 cp="Os dois diante do portão fechado. Texto da capa: “FECHADO.”",
 so="Falas originais + ambiente da rua. Música da biblioteca baixa.",
 me="Comentários e envios por alcance", hi="Perrengue real com dica gera mais comentários do que dica sem história.",
 te=None,
 ma=["IMG_3134.MOV (65,5 s, fala, HDR→SDR)", OUTRAS],
 pe=["Confirmar a data da visita (o horário do Jardim de Luxemburgo muda por mês; conferir em senat.fr antes de postar)", "Selfie horizontal com os dois: na apresentação, o recorte 9:16 não coube os dois em parte dos quadros. Recorte acompanhando quem fala (keyframes de posição), conferido quadro a quadro, sem cortar a Marina no meio do rosto"],
 of="Brutos de Paris", otr="IMG_3134 (0–63 s)"),

dict(
 d="2026-10-17", h="11:00", f="R", k="ita", pl="DESEJO", nv="B", st="dec",
 t="Dois pores do sol de graça em Roma",
 ob="Desejo com utilidade leve: dois lugares bonitos e gratuitos, com a hora real da foto. Primeiro Reel da Itália feito de fotos.",
 mo="Quem sonha com Roma e casais que planejam viagem. Envia para quem iria junto; salva para o roteiro.",
 g="Dois pores do sol grátis em Roma.", gt="Lista curta",
 q0="Foto do pôr do sol no Gianicolo (IMG_5523) com zoom sutil; Placa Marca `PRIMEIRO DIA →` com a Chegada.",
 sc=[("0–2 s","Gancho","IMG_5523 (Gianicolo) com zoom 100→104%. Legenda Padrão: “dois pores do sol grátis em roma.” com Destaque em “grátis”."),
     ("2–6 s","Lugar 1","IMG_5220 (Terrazza del Pincio). Legenda Informação: `PINCIO · FOTO 16:37 · 25/12`."),
     ("6–10 s","Lugar 2","IMG_5523 (Gianicolo, alto de Trastevere). Legenda Informação: `GIANICOLO · FOTO 16:45 · 27/12`."),
     ("10–13 s","Dica","Se houver vídeo ou outra foto do mesmo fim de tarde, entra aqui (decupagem). Legenda Padrão: “em dezembro, chegue antes das 16h30.”"),
     ("13–15 s","Loop","Volta ao Gianicolo do quadro 0.")],
 tl="dois pores do sol grátis em roma · pincio (25/12, 16:37) · gianicolo (27/12, 16:45) · em dezembro, chegue antes das 16h30",
 na="Sem narração.",
 lg="Dois pores do sol de graça em Roma. 🌅\n\n1. Terrazza del Pincio, em cima da Piazza del Popolo. Foto tirada às 16h37 do dia 25 de dezembro.\n2. Gianicolo, no alto de Trastevere. Foto às 16h45 do dia 27.\n\nNenhum dos dois cobra entrada. Em dezembro o sol se põe cedo em Roma: chegue antes das 16h30 para pegar a luz.\n\nManda pra quem vai ver o pôr do sol com você em Roma.",
 cta="Manda pra quem vai ver o pôr do sol com você (envio).",
 cp="Gianicolo ao pôr do sol. Texto da capa: “PÔR DO SOL GRÁTIS”.",
 so="Música instrumental da biblioteca (sem letra). Sem efeitos sonoros.",
 me="Envios por alcance e seguidores por 1.000 visualizações", hi="Desejo com 1 informação útil (grátis + hora) converte mais que desejo puro.",
 te="T1:B",
 ma=["IMG_5220 (Pincio, 25/12/2024 16:37)", "IMG_5523 (Gianicolo, 27/12/2024 16:45)", ROMA_FOTOS, "Vídeos ambientais da Itália: localizar se há planos desses dois fins de tarde"],
 pe=["Procurar no acervo vídeos ou outras fotos do Pincio e do Gianicolo (se não houver, o Reel fica só com as 2 fotos e 12 s)", "Conferir o horário do pôr do sol em Roma no fim de dezembro (timeanddate) antes de publicar a dica das 16h30"],
 of="Fotos da Itália", otr="IMG_5220 e IMG_5523"),

dict(
 d="2026-10-18", h="19:00", f="R", k="brg", pl="EXP", nv="A", st="ok",
 t="Vale ou pula: waffle de rua em Bruges",
 ob="Identificação e utilidade: prova real de comida típica, com veredito. Formato de série (Vale ou pula) que cria expectativa para os próximos.",
 mo="Quem vai à Bélgica e quem ama comida de rua. Envia para quem vai dividir o waffle; comenta o próprio veredito.",
 g="Vale ou pula: waffle em Bruges?", gt="Vale a pena?",
 q0="IMG_2693 em 0 s: Diego com o waffle na mão na rua de Bruges. Placa `VALE OU PULA` / `WAFFLE · BRUGES` com a Chegada.",
 sc=[("0–2 s","Gancho","IMG_2693 (0–2 s) + Placa Série `VALE OU PULA` / `WAFFLE · BRUGES`."),
     ("2–7 s","Contexto","IMG_2690 (0–5 s): o balcão take away e o waffle em pedaços com cobertura. Legenda Narrativa: “bruges, balcão de rua.”"),
     ("7–14 s","Prova","IMG_2692 (0–7 s) e IMG_2691 (0–5 s): Marina provando. Cortes secos."),
     ("14–20 s","Pico","IMG_2693 (7–12 s): reação do Diego (“muito, muito”). Legenda Padrão."),
     ("20–23 s","Veredito","Bilhete veredito: `vale.` com ✓ verde circulado."),
     ("23–25 s","Loop","IMG_2693 (13–15 s): Diego segue andando pela rua.")],
 tl="vale ou pula: waffle em bruges? · balcão de rua, take away · [preço a confirmar] · vale.",
 na="Sem narração nova.",
 lg="Vale ou pula: waffle em Bruges? 🧇\n\nCompramos no balcão de rua, take away, e comemos andando pelo centro. [sabor e cobertura a confirmar] por € [valor] (≈ R$ [valor]).\n\nVeredito: vale. Doce, quente e perfeito para o frio que estava.\n\nCotação: € 1 = R$ [PTAX da data da viagem].\n\nVai para a Bélgica? Manda pra quem vai dividir o waffle com você.",
 cta="Manda pra quem vai dividir o waffle com você (envio).",
 cp="Diego mordendo o waffle na rua. Texto da capa: “VALE OU PULA?”",
 so="Som direto da rua + música da biblioteca baixa. Bilhete com cliques de caneta (quando o arquivo existir).",
 me="Envios por alcance", hi="A série Vale ou pula com prova real gera envios entre quem vai viajar junto.",
 te=None,
 ma=["IMG_2693.MOV (15,5 s, Diego comendo, vertical)", "IMG_2690.MP4 (26,6 s), IMG_2691.MP4 (11,7 s), IMG_2692.MP4 (23,8 s): Marina provando", OUTRAS],
 pe=["IMG_2690 a IMG_2692 são cópias 720p: pedir os originais em resolução cheia (o IMG_2693, do Diego, é 4K)", "Confirmar sabor, cobertura e preço do waffle (a transcrição do IMG_2690 menciona dois chocolates, um deles “com álcool”: confirmar antes de citar)", "Confirmar o veredito com o Diego (a reação filmada é positiva)", "Data da viagem para a cotação"],
 of="Brutos de Bruges", otr="IMG_2690 a IMG_2693"),

# ───────────────────────── Semana 3 (19 a 25/10) ─────────────────────────
dict(
 d="2026-10-20", h="18:30", f="R", k="ams", pl="SERIE", nv="B", st="ok",
 t="Primeira hora em Amsterdam: frio e fome",
 ob="Conversão e série: a primeira hora real numa cidade nova, do aeroporto à primeira decisão do dia. É a promessa do perfil em 25 segundos.",
 mo="Quem vai a Amsterdam e quem sonha com a primeira viagem. Segue porque entende a série (o primeiro dia de cada cidade).",
 g="Primeira hora em Amsterdam: frio e fome.", gt="Afirmação",
 q0="IMG_1384 em 3 s: Diego sorrindo na rua de tijolos, Marina atrás com a mala. Placa `PRIMEIRO DIA EM / AMSTERDAM` com a Chegada.",
 sc=[("0–2,5 s","Gancho","IMG_1384 (2,0–4,5 s) + Placa de abertura. Legenda Padrão com Destaque em “fome”."),
     ("2,5–8 s","Chegada","IMG_1375 (0,2–8,0 s): “Chegamos em Amsterdam, acabamos de pousar… com frio, a caminho do hotel.” Placa sai pela direita."),
     ("8–12 s","Rua","IMG_1384 (0,0–2,0 s e 4,0–7,0 s): “Tá frio? Chegamos!” e a rua de tijolos."),
     ("12–18 s","Decisão","IMG_1393 (0,2–15,2 s, cortes secos): Museumplein, “não vamos vir aqui hoje… vamos deixar os museus para depois”."),
     ("18–24 s","Pico","IMG_1393 (22,2–32,2 s): “aproveitar para comer, porque estamos morrendo de fome, e tomar uma cerveja… terra da Heineken e da Amstel”. Bilhete: “prioridade da 1ª hora: comer.”"),
     ("24–27 s","Fechamento","Placa `E ISSO FOI SÓ O / PRIMEIRO DIA.` com o 1º nascendo e o bordão em legenda.")],
 tl="primeira hora em amsterdam: frio e fome · acabamos de pousar · museus? deixamos pra depois · prioridade: comer",
 na="Sem narração nova. O bordão “E isso foi só o primeiro dia.” pode ser gravado pelo Diego (3 s) ou ficar só na placa.",
 lg="Primeira hora em Amsterdam: frio e fome. 🥶\n\nPousamos, pegamos o caminho da hospedagem e a primeira coisa que a cidade fez foi lembrar que estava frio.\n\nMalas deixadas, passamos pela Museumplein, a Praça dos Museus, e decidimos deixar os museus para outro dia. No primeiro, o plano era o centro.\n\nPrioridade da primeira hora: comer e tomar uma cerveja na terra da Heineken.\n\nSou o Diego e aqui eu mostro o primeiro dia em cada cidade. Segue pra ver o resto de Amsterdam.",
 cta="Segue pra ver o resto de Amsterdam (seguir).",
 cp="Diego sorrindo na rua de tijolos com a mala atrás. Texto da capa: “1ª HORA: AMSTERDAM”.",
 so="Falas originais + ambiente. Clack da placa quando PD_clack existir. Música da biblioteca baixa.",
 me="Seguidores por 1.000 visualizações", hi="O formato “primeira hora” com fala real converte mais que paisagem e explica a série a quem não conhece.",
 te="T3:A",
 ma=["IMG_1375.MOV (17 s, aeroporto)", "IMG_1384.MOV (11,3 s, rua com malas, vertical)", "IMG_1393.MOV (33,3 s, Museumplein)", OUTRAS],
 pe=["Selfie horizontal com os dois: na apresentação, o recorte 9:16 não coube os dois em parte dos quadros. Recorte acompanhando quem fala (keyframes de posição), conferido quadro a quadro, sem cortar a Marina no meio do rosto (IMG_1375 e IMG_1393)", "Se houver plano da primeira comida e da cerveja (decupagem), colocar no pico em vez do Bilhete", "Não citar temperatura (não foi registrada)"],
 of="Brutos de Amsterdam, dia 1", otr="IMG_1375, IMG_1384, IMG_1393"),

dict(
 d="2026-10-21", h="18:00", f="C", k="bcn", pl="UTIL", nv="—", st="ok",
 t="Barcelona: o Gaudí que dá pra ver de graça (e o que pagamos)",
 ob="Salvamento: ajudar a decidir onde pagar entrada em Barcelona, com o que a gente realmente fez.",
 mo="Quem vai a Barcelona com orçamento definido. Salva para decidir os ingressos; envia para quem está montando o roteiro.",
 g="Gaudí de graça: só por fora.", gt="Afirmação",
 q0="Capa: fachada da Casa Batlló (quadro do master ≈ 20:51) com Placa G `QUANTO CUSTOU` / `GAUDÍ · BARCELONA`.",
 sl=["1 · Capa (foto em sangria): Casa Batlló, Placa G Série `QUANTO CUSTOU` / `GAUDÍ · BARCELONA` + “o que dá pra ver de graça”.",
     "2 · Quadro (segunda capa): VIMOS POR FORA (grátis): Casa Vicens, Casa Batlló, Casa Milà, Palau Güell, postes da Plaça Reial · PAGAMOS PARA ENTRAR: Sagrada Família (€ 25), Park Güell (€ [confirmar]).",
     "3 · Foto + informação: Casa Vicens, uma das primeiras obras de Gaudí. Patrimônio da UNESCO desde 2005. Vimos por fora.",
     "4 · Foto + informação: Casa Batlló. Cada um vê uma coisa na fachada: a gente viu máscara de carnaval. Vimos por fora.",
     "5 · Foto + informação: Casa Milà, no Passeig de Gràcia, a avenida das lojas de grife. Vimos por fora.",
     "6 · Foto + informação: Palau Güell, no caminho do almoço. Vimos por fora.",
     "7 · Foto + informação: Plaça Reial. Os postes são uma das primeiras obras de Gaudí, feita quando ele era jovem.",
     "8 · Foto + informação: Sagrada Família. € 25 por pessoa. Valeu cada centavo para a gente. Compre antes.",
     "9 · Foto + informação: Park Güell, com hora marcada (a nossa foi 13h30). € [confirmar].",
     "10 · Dica (Bilhete): “escolha 1 ou 2 para entrar. o resto, veja por fora.”",
     "11 · Encerramento: Placa CTA `SALVA PRA VIAGEM →` + símbolo 1º."],
 tl="Slides acima. Etiqueta de série `QUANTO CUSTOU`, contador e Rota.",
 na="Não se aplica (carrossel).",
 lg="Gaudí de graça em Barcelona: só por fora. 🏛️\n\nEntrar em todas as obras de Gaudí pesa no orçamento. A gente escolheu duas para entrar e viu o resto por fora:\n\nVimos por fora (grátis): Casa Vicens, Casa Batlló, Casa Milà, Palau Güell e os postes da Plaça Reial.\nPagamos para entrar: Sagrada Família (€ 25 por pessoa) e Park Güell (€ [confirmar]).\n\nA Sagrada Família valeu cada centavo. Se for escolher uma só, é ela.\n\nCotação: € 1 = R$ [PTAX da data da viagem].\n\nSalva pra montar o seu roteiro de Barcelona.",
 cta="Salva pra montar o seu roteiro (salvamento).",
 cp="Casa Batlló com a Placa G e a frase da capa.",
 so="Música instrumental da biblioteca ao postar.",
 me="Salvamentos por alcance", hi="A comparação grátis × pago é mais salvável do que uma lista de pontos turísticos.",
 te="T4:A",
 ma=[BCN_MASTER+": dias 2 e 3 (Casa Vicens ≈ 11:42, Plaça Reial ≈ 15:14, Palau Güell ≈ 16:01, Casa Batlló ≈ 20:51, Casa Milà ≈ 22:09, Sagrada ≈ 23:55, Park Güell ≈ 29:39)", BCN_TRANS],
 pe=["Preço do Park Güell pago pela dupla", "Não citar o preço da Casa Batlló (no vídeo foi um palpite, “acho que em torno de 15 euros”)", "Conferir a data de UNESCO da Casa Vicens (2005) e o crédito dos postes da Plaça Reial a Gaudí", "Quadros sem etiqueta gráfica do vlog"],
 of="Barcelona, dias 2 e 3", otr="Master 11:42–31:55"),

dict(
 d="2026-10-22", h="12:30", f="R", k="ita", pl="UTIL", nv="B", st="ok",
 t="Roma agora cobra pra ver isso",
 ob="Envio e salvamento: informação nova e verificável que muda o orçamento de quem vai a Roma, ilustrada com fotos próprias.",
 mo="Quem vai a Roma nos próximos meses. Envia na hora para quem vai junto; salva para o roteiro.",
 g="Roma agora cobra pra ver isso.", gt="Surpresa",
 q0="Foto da Fontana di Trevi (IMG_5064) com zoom sutil e Etiqueta de valor `€ 2` já na tela.",
 sc=[("0–2 s","Gancho","IMG_5064 (Trevi, 25/12/2024) com Etiqueta de valor `€ 2 ≈ R$ 11,76`. Legenda Padrão com o gancho."),
     ("2–6 s","Trevi","Legenda Padrão: “desde fevereiro de 2026, chegar perto da fonte custa € 2. de longe, continua grátis.”"),
     ("6–10 s","Panteão","IMG_5108 (Panteão). Etiqueta de valor `€ 7 ≈ R$ 41,16`. Legenda: “em 2024 a gente pagou € 5. desde julho de 2026, € 7.”"),
     ("10–13 s","Dica","Legenda Padrão: “some € 9 por pessoa no orçamento de roma.”"),
     ("13–15 s","Loop","Volta à Trevi do quadro 0.")],
 tl="roma agora cobra pra ver isso · trevi: € 2 desde 02/2026 · panteão: € 5 (2024) → € 7 desde 07/2026 · +€ 9 por pessoa",
 na="Sem narração.",
 lg="Roma agora cobra pra ver isso. 💶\n\nFontana di Trevi: desde 2 de fevereiro de 2026, chegar perto da fonte custa € 2 (≈ R$ 11,76). Olhar de longe continua grátis.\n\nPanteão: em dezembro de 2024 a gente pagou € 5. Desde 1º de julho de 2026, custa € 7 (≈ R$ 41,16).\n\nSão € 9 a mais por pessoa no orçamento de Roma.\n\nCotação: € 1 = R$ 5,88 (02/10/2026).\n\nManda pra quem vai pra Roma.",
 cta="Manda pra quem vai pra Roma (envio).",
 cp="Fontana di Trevi com a etiqueta € 2. Texto da capa: “ROMA COBRA ISSO”.",
 so="Música instrumental da biblioteca. *tick* do preço quando PD_tick existir.",
 me="Envios por alcance", hi="Novidade verificável de preço gera mais envios do que dica atemporal.",
 te="T5:A",
 ma=["IMG_5064 (Trevi, 25/12/2024 10:08)", "IMG_5108 (Panteão, fachada)", ROMA_FOTOS],
 pe=["Reconferir os preços de 2026 na véspera (Comune di Roma para a Trevi; site oficial do Panteão) e atualizar a cotação do dia"],
 of="Fotos da Itália", otr="IMG_5064, IMG_5108"),

dict(
 d="2026-10-24", h="11:00", f="R", k="bcn", pl="DESEJO", nv="B", st="dec",
 t="Sagrada Família: projetada como uma floresta",
 ob="Desejo com curiosidade: o interior que surpreendeu, em 15 segundos, com uma frase que explica o que a pessoa está vendo.",
 mo="Quem sonha com Barcelona e quem gosta de arquitetura. Envia para quem tem a Sagrada Família na lista; salva como destino.",
 g="Ela foi projetada como uma floresta.", gt="Afirmação",
 q0="Contra-plongée das colunas internas se abrindo como galhos (bruto do interior). Placa Marca `PRIMEIRO DIA →` com a Chegada.",
 sc=[("0–2 s","Gancho","Colunas internas, câmera subindo. Placa Marca. Legenda Padrão com o gancho escrito (variante A do teste T2)."),
     ("2–6 s","Contexto","Master ≈ 24:35–25:06 (ou bruto equivalente): “a igreja foi projetada como uma floresta… as pilastras se ramificam como árvores e se encontram no teto”. Legenda Padrão."),
     ("6–11 s","Desejo","3 planos de 1,5 a 2 s do interior, cortes secos, zoom sutil nos planos parados."),
     ("11–14 s","Prova","Fachada às 9h30, cheia (master ≈ 23:55). Legenda: “9h30 e já estava cheia.”"),
     ("14–16 s","Loop","Volta às colunas do quadro 0.")],
 tl="ela foi projetada como uma floresta · as colunas viram galhos · 9h30 e já estava cheia",
 na="Sem narração nova: a explicação é da fala original (24:35–25:06).",
 lg="Ela foi projetada como uma floresta. 🌳\n\nAs colunas da Sagrada Família se ramificam como árvores e se encontram no teto. E o som foi pensado para ecoar pelas colunas e se espalhar pela igreja inteira.\n\nFomos às 9h30 e já estava cheia. Pagamos € 25 por pessoa, com ingresso comprado antes.\n\nManda pra quem tem a Sagrada Família na lista.",
 cta="Manda pra quem tem a Sagrada Família na lista (envio).",
 cp="Colunas internas vistas de baixo. Texto da capa: “UMA FLORESTA?”",
 so="Ambiente da igreja bem baixo + música instrumental da biblioteca. Não usar a música que toca dentro da igreja como trilha.",
 me="Envios por alcance e retenção média", hi="Gancho escrito que explica a imagem retém mais nos 3 primeiros segundos do que só a imagem (comparar com o Reel de Bruges, 25/10).",
 te="T2:A",
 ma=[BCN_MASTER+": 23:55–25:51 (dia 3)", "IMG_1192.MOV (Sagrada, dia 3)", "Brutos do interior: localizar os originais sem trilha"],
 pe=["Localizar os brutos do interior da Sagrada Família (o master tem violão no B-roll)", "Preço de 2026 para citar como dica, se perguntarem"],
 of="Barcelona, dia 3", otr="Master 23:55–25:51"),

dict(
 d="2026-10-25", h="19:00", f="R", k="brg", pl="DESEJO", nv="B", st="dec",
 t="Bruges em 15 segundos (sem texto)",
 ob="Desejo puro: a cidade que parece cenário, sem gancho escrito, para medir se a imagem sozinha segura a atenção.",
 mo="Quem sonha com a Europa e casais. Envia para o parceiro de viagem (“vamos?”); salva como destino.",
 g="(sem texto nos 2 primeiros segundos)", gt="Visual (sem texto)",
 q0="O plano mais forte de Bruges na decupagem (rua de casas com empena ou canal), já em movimento. Só a Placa Marca `PRIMEIRO DIA →` com a Chegada, sem legenda de gancho.",
 sc=[("0–2 s","Gancho visual","Melhor plano de Bruges em movimento + Placa Marca. Sem texto de gancho (variante B do teste T2)."),
     ("2–12 s","Desejo","5 a 6 planos de 1,5 a 2 s: ruas, fachadas, IMG_2693 (13–15 s: Diego andando na rua de compras). Cortes no tempo da música."),
     ("12–14 s","Nome","Legenda Narrativa curta: “bruges, bélgica. bate-volta de bruxelas.”"),
     ("14–15 s","Loop","Corte seco para o plano do quadro 0.")],
 tl="(nada até 12 s) · bruges, bélgica. bate-volta de bruxelas.",
 na="Sem narração.",
 lg="Bruges, na Bélgica, em 15 segundos. 🇧🇪\n\nFizemos bate-volta saindo de Bruxelas e passamos o dia andando pelo centro, que parece cenário de filme.\n\nManda pra quem iria pra Bruges com você.",
 cta="Manda pra quem iria pra Bruges com você (envio).",
 cp="Rua de Bruges com fachadas de empena. Texto da capa: “BRUGES”.",
 so="Música instrumental da biblioteca, cortes no tempo da batida; ambiente da rua por baixo.",
 me="Retenção média e % de não seguidores", hi="Sem texto, o Reel de desejo retém menos nos 3 primeiros segundos do que com gancho escrito (comparar com a Sagrada, 24/10).",
 te="T2:B",
 ma=["IMG_2693.MOV (rua de Bruges)", "Brutos de Bruges (decupagem pendente: ruas, fachadas, canais)", OUTRAS],
 pe=["Decupagem dos brutos de Bruges: listar planos de rua, fachada e canal com minutagem", "Confirmar o trajeto do bate-volta (trem? duração?) para a legenda e para o carrossel de 11/11"],
 of="Brutos de Bruges", otr="Decupagem"),

# ───────────────────────── Semana 4 (26/10 a 01/11) ─────────────────────────
dict(
 d="2026-10-27", h="18:30", f="R", k="ams", pl="DESEJO", nv="B", st="dec",
 t="Amsterdam: imagina morar nessa rua",
 ob="Desejo puro, sem informação: medir quantos seguidores um Reel só de atmosfera traz, comparado ao mesmo formato com preço.",
 mo="Quem sonha com a Europa. Envia para quem “moraria ali”; salva como destino dos sonhos.",
 g="Imagina morar nessa rua.", gt="Desejo",
 q0="Plano de rua com canal e casas estreitas de Amsterdam (decupagem), luz do dia. Placa Marca `PRIMEIRO DIA →` com a Chegada.",
 sc=[("0–2 s","Gancho","Melhor plano de canal ou rua residencial + Placa Marca + legenda Padrão “imagina morar nessa rua.”"),
     ("2–12 s","Desejo","5 a 6 planos de 1,5 a 2 s: canais, bicicletas, fachadas, IMG_1384 (4–6 s, a rua de tijolos). Sem informação (variante A do teste T1)."),
     ("12–14 s","Fecho","Legenda Padrão: “amsterdam.”"),
     ("14–15 s","Loop","Corte seco para o quadro 0.")],
 tl="imagina morar nessa rua · amsterdam.",
 na="Sem narração.",
 lg="Imagina morar nessa rua. 🚲\n\nAmsterdam, entre um canal e outro, no nosso primeiro dia na cidade.\n\nManda pra quem moraria aqui com você.",
 cta="Manda pra quem moraria aqui com você (envio).",
 cp="Canal com casas estreitas. Texto da capa: “AMSTERDAM”.",
 so="Música instrumental da biblioteca; ambiente por baixo.",
 me="Seguidores por 1.000 visualizações e envios por alcance", hi="Desejo puro alcança muitos não seguidores, mas converte menos que desejo com informação (comparar com Roma, 17/10).",
 te="T1:A",
 ma=["IMG_1384.MOV (rua de tijolos)", "Brutos de Amsterdam (decupagem pendente: canais, bicicletas, fachadas)", OUTRAS],
 pe=["Decupagem dos brutos de Amsterdam", "Se os planos de canal forem de outro dia, trocar “no nosso primeiro dia” por “em Amsterdam” na legenda"],
 of="Brutos de Amsterdam", otr="Decupagem"),

dict(
 d="2026-10-28", h="18:00", f="C", k="par", pl="UTIL", nv="—", st="dec",
 t="Paris em 1 dia: o que deu e o que faltou",
 ob="Salvamento: o roteiro real de um dia só em Paris, incluindo o que não deu certo.",
 mo="Quem vai a Paris com pouco tempo (escala, combinação com Disney). Salva o roteiro; envia para quem vai em poucos dias.",
 g="Paris em 1 dia: o que deu.", gt="Resultado primeiro",
 q0="Capa em papel (variante B do teste T4): Rota do dia com as paradas e o selo reduzido PERRENGUE na parada do Jardim de Luxemburgo.",
 sl=["1 · Capa (papel, variante B): título “Paris em 1 dia: o que deu e o que faltou” + Rota com as paradas reais + selo reduzido PERRENGUE no Luxemburgo.",
     "2 · Foto: a chegada (IMG_2730): “nós só vamos passar um dia em Paris… amanhã é Disney”.",
     "3–7 · Uma foto por parada real, na ordem do dia (a definir na decupagem). Cada slide: lugar + 1 frase + valor se houve.",
     "8 · Foto + informação: Torre Eiffel de dia, no Champ de Mars (IMG_2761).",
     "9 · O que faltou: Jardim de Luxemburgo fechado (IMG_3134). Selo reduzido PERRENGUE. “O horário muda com a estação: vá cedo.”",
     "10 · Foto: a Torre brilhando à noite (se houver plano).",
     "11 · Encerramento: Bilhete veredito “1 dia dá para o essencial, não para tudo.” + Placa CTA `SALVA PRA VIAGEM →` + 1º."],
 tl="Slides acima. Etiqueta de série `ROTEIRO`.",
 na="Não se aplica (carrossel).",
 lg="Paris em 1 dia: o que deu e o que faltou. 🗼\n\nTínhamos um dia só em Paris (no seguinte era Disney). O roteiro real:\n\n[paradas na ordem, a preencher com a decupagem]\n\nO que faltou: o Jardim de Luxemburgo. Deixamos para o fim do dia e ele já estava fechado. O horário muda com a estação, então vá cedo.\n\nO que salvou a noite: a Torre Eiffel brilhando.\n\nSalva pra sua viagem a Paris.",
 cta="Salva pra sua viagem a Paris (salvamento).",
 cp="Capa em papel com a Rota (teste T4, variante B).",
 so="Música instrumental da biblioteca ao postar.",
 me="Salvamentos por alcance e % de não seguidores", hi="Capa de papel (roteiro visível) gera mais salvamentos, mas alcança menos não seguidores que capa de foto.",
 te="T4:B",
 ma=["IMG_2730.MOV (chegada)", "IMG_2761.MOV (selfie na Torre, Champ de Mars)", "IMG_3134.MOV (Jardim fechado)", "IMG_2978 (Torre Eiffel, usado na apresentação)", "Brutos de Paris (decupagem pendente para as paradas do meio do dia e a Torre à noite)", OUTRAS],
 pe=["Decupagem de Paris: lista das paradas do dia, na ordem, com minutagem", "Valores gastos em Paris (se houver registro)", "Confirmar se há plano da Torre brilhando à noite"],
 of="Brutos de Paris", otr="IMG_2730, IMG_2761, IMG_3134 + decupagem"),

dict(
 d="2026-10-29", h="12:30", f="R", k="bcn", pl="EXP", nv="B", st="ok",
 t="Casa Batlló: o que você vê nessa janela?",
 ob="Comentários e identificação: uma pergunta simples e divertida sobre uma fachada famosa, com a resposta de cada um.",
 mo="Qualquer pessoa que gosta de viagem ou arquitetura. Comenta a própria resposta; envia para um amigo para ver o que ele enxerga.",
 g="O que você vê nessa janela?", gt="Pergunta",
 q0="Close da fachada da Casa Batlló (master ≈ 20:51). Placa Hook `O QUE VOCÊ VÊ?` / `BATLLÓ` com módulo `?`.",
 sc=[("0–2 s","Gancho","Fachada em close + Placa Hook."),
     ("2–8 s","Contexto","Master ≈ 20:51–21:10: “Casa Batlló, uma das mais famosas de Gaudí… parece que foi feita no mar… várias pessoas enxergam várias coisas nessa janela.”"),
     ("8–14 s","Pico","Master ≈ 21:10–21:30: “eu enxergo máscara de carnaval”, “tubarão”, “caveira”. Legenda Padrão com Destaque em cada resposta."),
     ("14–17 s","Pergunta","Fachada de novo. Legenda Padrão: “e você, vê o quê?”"),
     ("17–18 s","Loop","Corte seco para o quadro 0.")],
 tl="o que você vê nessa janela? · máscara de carnaval · tubarão · caveira · e você?",
 na="Sem narração nova.",
 lg="O que você vê nessa janela? 👀\n\nCasa Batlló, de Gaudí, no Passeig de Gràcia, em Barcelona. Cada pessoa enxerga uma coisa diferente na fachada.\n\nEu vi máscara de carnaval. Já ouvi tubarão e caveira.\n\nE você, vê o quê? Responde aqui.",
 cta="Responde nos comentários o que você vê (comentário).",
 cp="Fachada da Casa Batlló. Texto da capa: “O QUE VOCÊ VÊ?”",
 so="Falas originais + música da biblioteca baixa.",
 me="Comentários por alcance", hi="Pergunta aberta e fácil sobre um lugar famoso gera conversa e alcance, mesmo sem utilidade.",
 te=None,
 ma=[BCN_MASTER+": 20:51–21:39 (dia 2)", BCN_TRANS],
 pe=["Ouvir o trecho para checar trilha sob a fala", "Responder os comentários na primeira hora (é o sinal que este Reel testa)"],
 of="Barcelona, dia 2", otr="Master 20:51–21:39"),

dict(
 d="2026-10-31", h="11:00", f="R", k="dis", pl="SERIE", nv="B", st="dec",
 t="2 parques da Disneyland Paris em 1 dia",
 ob="Série e conversão: um primeiro dia ousado (dois parques) contado do jeito que foi. A Disney é um dos destinos mais buscados por brasileiros.",
 mo="Famílias, casais e fãs da Disney que vão a Paris. Envia para quem sonha com a Disney; segue para ver a próxima cidade.",
 g="2 parques da Disney em 1 dia.", gt="Afirmação",
 q0="Entrada do parque ou castelo (decupagem), com a Placa `PRIMEIRO DIA EM / DISNEYLAND PARIS` (14 letras: 104 px).",
 sc=[("0–2 s","Gancho","Melhor plano da entrada + Placa de abertura."),
     ("2–6 s","Contexto","Fala de chegada (decupagem) ou legenda Narrativa: “2 parques. 1 dia.”"),
     ("6–18 s","Entrega","Cortes de 1,5 a 3 s: parque 1 → troca de parque → parque 2, na ordem real. Legenda Padrão com o que foi feito em cada um."),
     ("18–22 s","Pico","O momento de maior emoção filmado (decupagem): castelo, show ou atração. Ticket SURPREENDE só se algo superou a expectativa de verdade."),
     ("22–25 s","Fechamento","Placa `E ISSO FOI SÓ O / PRIMEIRO DIA.` + 1º + bordão.")],
 tl="2 parques da disney em 1 dia · parque 1 · troca · parque 2 · [veredito]",
 na="Se não houver fala de chegada no bruto, narração curta do Diego (até 8 s): “Dois parques, um dia só. Deu? Deu, mas…” [completar com o veredito real].",
 lg="2 parques da Disneyland Paris em 1 dia. 🏰\n\nTínhamos um dia só para a Disney e decidimos fazer os dois parques: [ordem real dos parques e horários aproximados, a preencher].\n\n[o que deu certo e o que ficou de fora, a preencher com o Diego]\n\nSou o Diego e aqui eu mostro o primeiro dia em cada lugar. Manda pra quem sonha com a Disney.",
 cta="Manda pra quem sonha com a Disney (envio).",
 cp="Castelo ou entrada com a placa. Texto da capa: “2 PARQUES, 1 DIA”.",
 so="Falas originais + música da biblioteca. Não usar música da Disney (direitos).",
 me="Seguidores por 1.000 visualizações e envios", hi="CTA de envio no formato de série gera mais envios, mas menos seguidores, do que o CTA de seguir (teste T3).",
 te="T3:B",
 ma=["Brutos da Disneyland Paris (decupagem pendente)", "Vlog da Disney (em edição para o YouTube de 21/11)"],
 pe=["Decupagem da Disney: chegada, troca de parque, pico, saída", "Ordem real dos parques e o veredito do Diego", "Não usar trilhas, personagens em close ou shows com música de direitos reservados como trilha"],
 of="Disneyland Paris", otr="Decupagem"),

dict(
 d="2026-11-01", h="19:00", f="R", k="lis", pl="DESEJO", nv="B", st="dec",
 t="Lisboa à noite (sem texto)",
 ob="Desejo puro sem texto de gancho: Lisboa é um dos destinos europeus mais queridos por brasileiros. Segundo ponto do teste T2.",
 mo="Brasileiros que sonham com Portugal. Envia para quem iria junto; salva como próxima viagem.",
 g="(sem texto nos 2 primeiros segundos)", gt="Visual (sem texto)",
 q0="O plano noturno mais forte de Lisboa na decupagem (rua iluminada, miradouro ou elétrico), em movimento. Só a Placa Marca `PRIMEIRO DIA →`.",
 sc=[("0–2 s","Gancho visual","Plano noturno em movimento + Placa Marca. Sem texto de gancho."),
     ("2–12 s","Desejo","5 a 6 planos noturnos de 1,5 a 2 s, cortes no tempo da música."),
     ("12–14 s","Nome","Legenda Narrativa: “lisboa, primeira noite.”"),
     ("14–15 s","Loop","Corte para o quadro 0.")],
 tl="(nada até 12 s) · lisboa, primeira noite.",
 na="Sem narração.",
 lg="Lisboa, na primeira noite. 🌙\n\nChegamos à noite e tínhamos só até a manhã seguinte. Saímos para andar mesmo assim.\n\nManda pra quem iria pra Lisboa com você.",
 cta="Manda pra quem iria pra Lisboa com você (envio).",
 cp="Rua iluminada de Lisboa. Texto da capa: “LISBOA À NOITE”.",
 so="Música instrumental da biblioteca (evitar fado com letra, que compete com a imagem); ambiente por baixo.",
 me="Retenção média e % de não seguidores", hi="Sem texto, o Reel de desejo retém menos nos 3 primeiros segundos (2º ponto do teste T2).",
 te="T2:B",
 ma=["Brutos de Lisboa (decupagem pendente: noite)"],
 pe=["Decupagem dos brutos de Lisboa", "Confirmar o roteiro real da noite e da manhã (legenda e carrossel de 02/12)"],
 of="Brutos de Lisboa", otr="Decupagem"),
]
